-- Dead-column cleanup (#31, architecture review 2026-09-24 item 2). BREAKING: schema_version 10 -> 11.
--   * drops company.SUWeb, company.SUContact1, part.is_lot_tracked, tables logs + release_notes
--   * renames company.SUNotes -> notes, SUSupplierCode -> supplier_code,
--     SUNumOfLNKs -> supplier_part_count, SUNumOfPOs -> po_count
--   * re-creates the two company count trigger functions (plpgsql bodies are stored as text,
--     so a column rename does not rewrite them) and patches stored named_queries SQL.
--
-- Pinned to ArxDev: the guard below aborts on any other database. A human edits the guard
-- to run it elsewhere (never default to ArxProd). Idempotent; runs in one transaction:
--   psql -v ON_ERROR_STOP=1 -d ArxDev -f 20260926092325_31_dead_column_cleanup.sql

BEGIN;

DO $$ BEGIN
  IF lower(current_database()) <> 'arxdev' THEN
    RAISE EXCEPTION 'Pinned to ArxDev (connected to %); edit this guard to run elsewhere', current_database();
  END IF;
END $$;

-- First Postgres migration: the ledger may not exist yet (same shape as schema_migrations.sql).
CREATE TABLE IF NOT EXISTS schema_migrations (
    id         INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id BIGINT    NOT NULL,
    is_applied BOOLEAN   NOT NULL,
    tstamp     TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

-- Preview: stored queries naming a dropped object. These are NOT auto-fixed - review by hand.
SELECT id, name, sql FROM named_queries
WHERE sql ~* '\m(suweb|sucontact1|is_lot_tracked|logs|release_notes)\M';

ALTER TABLE company DROP COLUMN IF EXISTS suweb;
ALTER TABLE company DROP COLUMN IF EXISTS sucontact1;
ALTER TABLE part    DROP COLUMN IF EXISTS is_lot_tracked;
DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS release_notes;

DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    ('sunotes', 'notes'), ('susuppliercode', 'supplier_code'),
    ('sunumoflnks', 'supplier_part_count'), ('sunumofpos', 'po_count')
  ) AS v(old_name, new_name)
  LOOP
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = current_schema() AND table_name = 'company' AND column_name = r.old_name) THEN
      EXECUTE format('ALTER TABLE company RENAME COLUMN %I TO %I', r.old_name, r.new_name);
    END IF;
  END LOOP;
END $$;

-- Same bodies as SQL/postgres/triggers.sql; the CREATE TRIGGER statements are unchanged.
CREATE OR REPLACE FUNCTION trg_supplier_part_company_count() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE company s
        SET supplier_part_count = (SELECT COUNT(*) FROM supplier_part sp WHERE sp.supplier_id = s.id)
        WHERE s.id IN (SELECT supplier_id FROM newtab WHERE supplier_id IS NOT NULL);
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE company s
        SET supplier_part_count = (SELECT COUNT(*) FROM supplier_part sp WHERE sp.supplier_id = s.id)
        WHERE s.id IN (SELECT supplier_id FROM oldtab WHERE supplier_id IS NOT NULL);
    ELSE  -- UPDATE: a moved row changes the count of both the old and new supplier.
        UPDATE company s
        SET supplier_part_count = (SELECT COUNT(*) FROM supplier_part sp WHERE sp.supplier_id = s.id)
        WHERE s.id IN (
            SELECT supplier_id FROM newtab WHERE supplier_id IS NOT NULL
            UNION
            SELECT supplier_id FROM oldtab WHERE supplier_id IS NOT NULL);
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION trg_PO_company_count() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE company s
        SET po_count = (SELECT COUNT(*) FROM purchase_order p WHERE p.supplier_id = s.id)
        WHERE s.id IN (SELECT supplier_id FROM newtab WHERE supplier_id IS NOT NULL);
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE company s
        SET po_count = (SELECT COUNT(*) FROM purchase_order p WHERE p.supplier_id = s.id)
        WHERE s.id IN (SELECT supplier_id FROM oldtab WHERE supplier_id IS NOT NULL);
    ELSE  -- UPDATE
        UPDATE company s
        SET po_count = (SELECT COUNT(*) FROM purchase_order p WHERE p.supplier_id = s.id)
        WHERE s.id IN (
            SELECT supplier_id FROM newtab WHERE supplier_id IS NOT NULL
            UNION
            SELECT supplier_id FROM oldtab WHERE supplier_id IS NOT NULL);
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

UPDATE named_queries SET sql = regexp_replace(sql, '\msunotes\M', 'notes', 'gi') WHERE sql ~* '\msunotes\M';
UPDATE named_queries SET sql = regexp_replace(sql, '\msusuppliercode\M', 'supplier_code', 'gi') WHERE sql ~* '\msusuppliercode\M';
UPDATE named_queries SET sql = regexp_replace(sql, '\msunumoflnks\M', 'supplier_part_count', 'gi') WHERE sql ~* '\msunumoflnks\M';
UPDATE named_queries SET sql = regexp_replace(sql, '\msunumofpos\M', 'po_count', 'gi') WHERE sql ~* '\msunumofpos\M';

UPDATE app_config SET setting_value = '11' WHERE setting_key = 'schema_version' AND setting_value = '10';

INSERT INTO schema_migrations (version_id, is_applied)
SELECT 20260926092325, TRUE
WHERE NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version_id = 20260926092325);

COMMIT;
