-- migrate_740_unit_table.sql
-- Traceability epic (#736) slice 3 (#740): add the `unit` table — the Tier-3 serialized
-- instance, the keystone the identity model previously lacked. See
-- docs/plans/736-traceability-data-model.md §4.1 / §7 slice 3 and SQL/unit.sql.
--
-- ADDITIVE and INERT: no code reads or writes `unit` until slice 8. An older binary never
-- touches the table, so this is backwards-compatible — schema_version is deliberately NOT
-- bumped (per the config.ExpectedSchemaVersion contract: only non-backward-compatible
-- changes bump; new tables are ignored by an older binary).
--
-- Provenance invariant (Q5): CK_unit_provenance enforces that every unit carries at least a
-- lot_id or a build_id — a unit with both NULL is orphaned and defeats traceability. A
-- CHECK alone can't confirm which one the app should set; app-level assignment at creation
-- (slice 8) does that. serial_number is UNIQUE per part_id (UQ_unit_serial).
--
-- SAFETY: pinned to ArxDev via the USE below. To apply to ArxProd, remove/change that single
-- line — nothing else in the script names a database. This is a script for a human to run,
-- not for an agent (see CLAUDE.md "ArxProd is off-limits").
--
-- Idempotent (guarded on the table not already existing; safe to re-run). Postgres
-- equivalent follows in comments (for the #625 migration).

USE ArxDev;   -- SAFETY: pinned to ArxDev. Remove/change this line to apply to ArxProd.

-- ------------------------------------------------------------------
-- 1. Create the unit table with its FKs, provenance CHECK, unique serial, and index.
-- ------------------------------------------------------------------
IF OBJECT_ID('dbo.unit', 'U') IS NULL
BEGIN
    CREATE TABLE unit (
      id             INT           PRIMARY KEY IDENTITY,
      part_id        INT           NOT NULL,
      lot_id         INT           NULL,
      build_id       INT           NULL,
      serial_number  VARCHAR(255)  NOT NULL,
      created_at     DATETIME      NOT NULL CONSTRAINT DF_unit_created   DEFAULT GETDATE(),
      is_active      BIT           NOT NULL CONSTRAINT DF_unit_is_active DEFAULT 1,
      CONSTRAINT CK_unit_provenance CHECK (lot_id IS NOT NULL OR build_id IS NOT NULL),
      CONSTRAINT UQ_unit_serial     UNIQUE (part_id, serial_number)
    );

    ALTER TABLE dbo.unit ADD CONSTRAINT FK_unit_part  FOREIGN KEY (part_id)  REFERENCES dbo.part (id);
    ALTER TABLE dbo.unit ADD CONSTRAINT FK_unit_lot   FOREIGN KEY (lot_id)   REFERENCES dbo.lot (id);
    ALTER TABLE dbo.unit ADD CONSTRAINT FK_unit_build FOREIGN KEY (build_id) REFERENCES dbo.build (id);
    CREATE INDEX IX_unit_part ON dbo.unit (part_id, is_active);
END;
-- Postgres:
--   CREATE TABLE IF NOT EXISTS unit (
--     id             INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     part_id        INTEGER       NOT NULL,
--     lot_id         INTEGER       NULL,
--     build_id       INTEGER       NULL,
--     serial_number  VARCHAR(255)  NOT NULL,
--     created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     is_active      BOOLEAN       NOT NULL DEFAULT TRUE,
--     CONSTRAINT CK_unit_provenance CHECK (lot_id IS NOT NULL OR build_id IS NOT NULL),
--     CONSTRAINT UQ_unit_serial     UNIQUE (part_id, serial_number)
--   );
--   ALTER TABLE unit ADD CONSTRAINT FK_unit_part  FOREIGN KEY (part_id)  REFERENCES part (id);
--   ALTER TABLE unit ADD CONSTRAINT FK_unit_lot   FOREIGN KEY (lot_id)   REFERENCES lot (id);
--   ALTER TABLE unit ADD CONSTRAINT FK_unit_build FOREIGN KEY (build_id) REFERENCES build (id);
--   CREATE INDEX IF NOT EXISTS IX_unit_part ON unit (part_id, is_active);
