-- build: one manufacturing build event — consume components, produce output (#675).
-- Part of the #568 lot control epic. Each row records building `qty` of the output
-- part (`part_id`) from its `bom` component lines. The build handler writes, in one
-- transaction: an inventory_transaction 'issue' row per component consumed and one
-- 'receipt' row for the output produced (see recordInventoryTxn), keeping
-- part.stock_on_hand in sync on both sides.
-- output_lot_id is a nullable placeholder for the produced lot; lot control is a
-- later PR in the epic, so there is no lot table or FK yet.
-- Requires part to exist first (FK on part_id).

DROP TABLE IF EXISTS build CASCADE;

CREATE TABLE build (
  id             INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id        INTEGER       NOT NULL,                          -- FK to part.id (output/parent part built).
  output_lot_id  INTEGER       NULL,                              -- Produced lot; wired to lot table in a later PR (#568).
  qty            NUMERIC(15,5) NOT NULL DEFAULT 1,                -- Number of output parts built.
  build_date     DATE          NOT NULL DEFAULT CURRENT_DATE,
  username       VARCHAR(128)  NOT NULL DEFAULT '',               -- App user login handle.
  note           TEXT,                                            -- Optional free-text comment.
  created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE build ADD CONSTRAINT FK_build_part FOREIGN KEY (part_id) REFERENCES part (id);
CREATE INDEX IX_build_part ON build (part_id, build_date);

-- FK_inv_txn_build (inventory_transaction.build_id → build.id, #677) is added here,
-- after build is created, so inventory_transaction can be created first in run order.
ALTER TABLE inventory_transaction ADD CONSTRAINT FK_inv_txn_build FOREIGN KEY (build_id) REFERENCES build (id);
