-- company: supplier, manufacturer, and vendor records.
-- SUNumOfLNKs and SUNumOfPOs are denormalized counts, kept in sync by triggers
-- (SQL/postgres/triggers.sql — run last, after all tables exist).

DROP TABLE IF EXISTS company CASCADE;

CREATE TABLE company (
  id                INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              VARCHAR(127)   NOT NULL CONSTRAINT UQ_company_name UNIQUE,
  SUWeb             VARCHAR(127),                     -- dead column; see FUTURE_GOALS.md
  SUContact1        VARCHAR(127),                     -- dead column; see FUTURE_GOALS.md
  SUNotes           VARCHAR(4000),
  date_modified     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
  is_active         BOOLEAN        DEFAULT TRUE,
  is_supplier       BOOLEAN        DEFAULT TRUE,      -- Can sell parts to you.
  is_manufacturer   BOOLEAN        DEFAULT FALSE,     -- Makes parts; may also be a supplier.
  SUNumOfLNKs       INTEGER        DEFAULT 0,         -- Denormalized count of supplier_part rows.
  SUNumOfPOs        INTEGER        DEFAULT 0,         -- Denormalized count of PO rows.
  SUSupplierCode    VARCHAR(12),
  default_contact        INTEGER   NULL,              -- FK to contact.id. NULL = none assigned.
  primary_attachment_id  INTEGER   NULL               -- FK to company_attachment.supplier_attachment_id.
);

ALTER TABLE company ADD CONSTRAINT FK_company_default_contact    FOREIGN KEY (default_contact)        REFERENCES contact (id);
ALTER TABLE company ADD CONSTRAINT FK_company_primary_attachment FOREIGN KEY (primary_attachment_id) REFERENCES company_attachment (supplier_attachment_id);
