-- company_attachment: file and URL attachments linked to a company.
-- file_path holds either a LOCAL:... path or a full https:// URL.
-- (The SQL Server _Test clone table is intentionally not ported - see README.)

DROP TABLE IF EXISTS company_attachment CASCADE;

CREATE TABLE company_attachment (
    supplier_attachment_id  INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id             INTEGER        NOT NULL,   -- FK to company.id (logical).
    file_path               VARCHAR(1024)  NOT NULL,
    notes                   VARCHAR(512),
    sort_order              INTEGER,
    is_active               BOOLEAN        NOT NULL DEFAULT TRUE,
    hash                    CHAR(64)       -- SHA-256 hex of the attachment (#71); NULL = not yet backfilled.
);
