-- company: supplier, manufacturer, and vendor records.
-- supplier_part_count and po_count are denormalized counts, kept in sync by triggers
-- (SQL/postgres/triggers.sql — run last, after all tables exist).

DROP TABLE IF EXISTS company CASCADE;

CREATE TABLE company (
  id                INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              VARCHAR(127)   NOT NULL CONSTRAINT UQ_company_name UNIQUE,
  notes             VARCHAR(4000),
  date_modified     TIMESTAMPTZ    DEFAULT now(),
  is_active         BOOLEAN        DEFAULT TRUE,
  is_supplier       BOOLEAN        DEFAULT TRUE,      -- Can sell parts to you.
  is_manufacturer   BOOLEAN        DEFAULT FALSE,     -- Makes parts; may also be a supplier.
  supplier_part_count INTEGER      DEFAULT 0,         -- Denormalized count of supplier_part rows.
  po_count          INTEGER        DEFAULT 0,         -- Denormalized count of PO rows.
  supplier_code     VARCHAR(12),                      -- folder stub for supplier/PO folders
  default_contact        INTEGER   NULL,              -- FK to contact.id. NULL = none assigned.
  primary_attachment_id  INTEGER   NULL,              -- FK to company_attachment.supplier_attachment_id.
  bulk_order_delimiter   VARCHAR(10) NOT NULL DEFAULT 'comma',   -- 'comma' | 'tab' | 'newline'; PO bulk-order copy-to-clipboard (#80)
  bulk_order_pn_source   VARCHAR(10) NOT NULL DEFAULT 'internal' -- 'internal' | 'vendor'; which PN the bulk-order copy uses
);

ALTER TABLE company ADD CONSTRAINT FK_company_default_contact    FOREIGN KEY (default_contact)        REFERENCES contact (id);
ALTER TABLE company ADD CONSTRAINT FK_company_primary_attachment FOREIGN KEY (primary_attachment_id) REFERENCES company_attachment (supplier_attachment_id);
