-- contact: contacts associated with suppliers.
-- company_id links to company.id (FK deferred - see #213).

DROP TABLE IF EXISTS contact CASCADE;

CREATE TABLE contact (
  id                  INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name        VARCHAR(127)   NOT NULL,
  address             VARCHAR(255),
  city                VARCHAR(64),
  zipcode             VARCHAR(10),
  state               VARCHAR(64),
  country             VARCHAR(127),
  phone_1             VARCHAR(32),
  phone_2             VARCHAR(32),
  fax                 VARCHAR(32),
  website             VARCHAR(500),
  email               VARCHAR(127),
  is_active           BOOLEAN        DEFAULT TRUE,
  company_id          INTEGER,                       -- FK to company.id.
  updated_at          TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
  notes               VARCHAR(4000)
);

ALTER TABLE contact ADD CONSTRAINT FK_contact_company FOREIGN KEY (company_id) REFERENCES company (id);
