-- form_events: audit trail for state changes on form (locked, unlocked, …).
-- form_id FKs to form.id.

DROP TABLE IF EXISTS form_events CASCADE;

CREATE TABLE form_events (
  id          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id     INTEGER      NOT NULL REFERENCES form (id),  -- FK to form.id.
  event_type  VARCHAR(50)  NOT NULL,                        -- 'locked', 'unlocked', 'archived', …
  username    VARCHAR(255),                                 -- OS username at time of event.
  event_date  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  comments    TEXT                                          -- User-supplied comment (required on unlock).
);
