-- form: test form definitions. One form per part number / product type.
-- part_number_id is a logical reference to part.id (no FK constraint).
-- test_order is a comma-separated list of form_row.id values in display order.

DROP TABLE IF EXISTS form CASCADE;

CREATE TABLE form (
  id                INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number_id    INTEGER      NOT NULL,           -- Logical reference to part.id.
  test_order        TEXT,                            -- Comma-separated form_row.id values.
  is_locked         BOOLEAN      NOT NULL DEFAULT FALSE, -- TRUE = locked from structural changes.
  is_active         BOOLEAN      NOT NULL DEFAULT TRUE,  -- FALSE = archived; hidden from UI.
  record_types      VARCHAR(500),                    -- Comma-separated allowed record types. NULL = free-text.
  instrument_types  VARCHAR(500),                    -- Comma-separated instrument types. NULL = free-text.
  revision          INTEGER      NOT NULL DEFAULT 0  -- Number of releases (#260). 0 = never released.
);
