-- form_record: a single test session for one serial number against one form.
-- part_id FKs to part.id (real FK as of #742; was a logical reference).
-- test_order is a snapshot of form.test_order at record creation.

DROP TABLE IF EXISTS form_record CASCADE;

CREATE TABLE form_record (
  id                     INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id                INTEGER      NOT NULL,             -- FK to form.id.
  part_id                INTEGER,                            -- FK to part.id (the assembly under test).
  record_date            TIMESTAMP,
  serial_number          VARCHAR(64),
  subject_part_number    VARCHAR(64),                       -- Denormalized PN at record creation.
  subject_pn_description  VARCHAR(64),                      -- Denormalized PN description.
  test_order             TEXT,                              -- Snapshot of form.test_order.
  comments               TEXT,
  instrument_type        VARCHAR(100),                      -- Matched against form_row.instrument_types.
  is_locked              BOOLEAN      NOT NULL DEFAULT FALSE, -- TRUE = locked (Complete or Approved).
  is_approved            BOOLEAN      NOT NULL DEFAULT FALSE, -- TRUE = reviewer-approved.
  is_active              BOOLEAN      NOT NULL DEFAULT TRUE,  -- FALSE = soft-deleted.
  created_at             TIMESTAMP,
  updated_at             TIMESTAMP,
  form_revision          INTEGER,                            -- Snapshot of form.revision (#260). NULL pre-#260.
  lot_id                 INTEGER,                            -- FK to lot.id (#677, nullable). Lot the tested unit belongs to.
  build_id               INTEGER,                            -- FK to build.id (#677, nullable). Build that produced the tested unit.
  unit_id                INTEGER                             -- FK to unit.id (#742, Q8, nullable). Serialized unit under test; NULL for batch records.
);

-- FK deferred (mirrors SQL Server set):
-- ALTER TABLE form_record ADD CONSTRAINT FK_form_record_form FOREIGN KEY (form_id) REFERENCES form (id);
-- ALTER TABLE form_record ADD CONSTRAINT FK_form_record_lot  FOREIGN KEY (lot_id)  REFERENCES lot (id);
-- ALTER TABLE form_record ADD CONSTRAINT FK_form_record_build FOREIGN KEY (build_id) REFERENCES build (id);
-- Real FKs from #742 (§4.4):
ALTER TABLE form_record ADD CONSTRAINT FK_form_record_part FOREIGN KEY (part_id) REFERENCES part (id);
ALTER TABLE form_record ADD CONSTRAINT FK_form_record_unit FOREIGN KEY (unit_id) REFERENCES unit (id);
CREATE INDEX IX_form_record_unit ON form_record (unit_id);
