-- form_row: individual test step / parameter definitions within a form.
-- form_id FKs to form.id (deferred - added manually below, matching SQL Server set).
-- type encodes row role: 0 = measurable test, 1/2/3 = heading level.

DROP TABLE IF EXISTS form_row CASCADE;

CREATE TABLE form_row (
  id                  INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id             INTEGER      NOT NULL,             -- FK to form.id.
  archive_id          INTEGER,
  revision            INTEGER,
  type                INTEGER,                            -- 0 = test row; 1/2/3 = heading level.
  category            VARCHAR(255),
  sheet_name          VARCHAR(255),
  parameter           VARCHAR(255),
  specification       VARCHAR(255),
  spec_units          VARCHAR(255),
  spec_min            VARCHAR(255),
  spec_max            VARCHAR(255),
  spec_nom            VARCHAR(255),
  default_result      VARCHAR(255),
  hide_formula        VARCHAR(255),                      -- 'HIDE' excludes this row from display.
  archived            BOOLEAN      NOT NULL DEFAULT FALSE, -- TRUE = retired step.
  pf_type             VARCHAR(50),                       -- 'range' (default/NULL = range check).
  granularity         VARCHAR(10)  NOT NULL DEFAULT 'unit' -- #744: unit|lot. Existing rows are per-unit tests.
                                   CONSTRAINT CK_form_row_granularity CHECK (granularity IN ('lot', 'unit')),
  instrument_types    VARCHAR(255),
  format              VARCHAR(255),
  comment             VARCHAR(500),
  created_at          TIMESTAMP,
  updated_at          TIMESTAMP
);

-- FK deferred (mirrors SQL Server set):
-- ALTER TABLE form_row ADD CONSTRAINT FK_form_row_form FOREIGN KEY (form_id) REFERENCES form (id);
