-- form_row_history: audit trail for changes to form_row rows.
-- Populated by trg_form_row_history (AFTER UPDATE) in
-- SQL/postgres/triggers.sql. It reads the app user from the session GUC
-- current_setting('arx.username') — set by the app via the dialect's
-- SetAuditUser — in place of SQL Server's CONTEXT_INFO().

DROP TABLE IF EXISTS form_row_history CASCADE;

CREATE TABLE form_row_history (
  id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_row_id   INTEGER      NOT NULL,              -- FK to form_row.id.
  changed_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  changed_by    VARCHAR(128) NOT NULL DEFAULT CURRENT_USER,  -- set by trigger when ported.
  -- snapshot of values before the update
  type          INTEGER,
  parameter     VARCHAR(255),
  specification VARCHAR(255),
  spec_units    VARCHAR(255),
  spec_min      VARCHAR(255),
  spec_max      VARCHAR(255),
  spec_nom      VARCHAR(255),
  default_result VARCHAR(255),
  hide_formula  VARCHAR(255),
  pf_type       VARCHAR(50),
  instrument_types VARCHAR(255),
  format        VARCHAR(255),
  comment       VARCHAR(500),
  category      VARCHAR(255),
  sheet_name    VARCHAR(255)
);
