-- form: test form definitions. One form per part number / product type.
-- part_number_id -> part.id (the FORM's own PN; real FK since #744).
-- test_order is a comma-separated list of form_row.id values in display order.

DROP TABLE IF EXISTS form CASCADE;

CREATE TABLE form (
  id                INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number_id    INTEGER      NOT NULL,           -- FK to part.id (the FORM's own PN). Real FK since #744.
  test_order        TEXT,                            -- Comma-separated form_row.id values.
  is_locked         BOOLEAN      NOT NULL DEFAULT FALSE, -- TRUE = locked from structural changes.
  is_active         BOOLEAN      NOT NULL DEFAULT TRUE,  -- FALSE = archived; hidden from UI.
  form_type         VARCHAR(20)  NOT NULL DEFAULT 'test' -- Kind of quality document (#744). Orthogonal to record_types.
                                 CONSTRAINT CK_form_type CHECK (form_type IN ('inspection', 'test', 'calibration', 'checklist', 'batch record')),
  record_types      VARCHAR(500),                    -- Comma-separated allowed record types. NULL = free-text. Orthogonal to form_type.
  instrument_types  VARCHAR(500),                    -- Comma-separated instrument types. NULL = free-text.
  revision          INTEGER      NOT NULL DEFAULT 0  -- Number of releases (#260). 0 = never released.
);

ALTER TABLE form ADD CONSTRAINT FK_form_part FOREIGN KEY (part_number_id) REFERENCES part (id); -- #744: was a logical reference.
