-- form_record: a single test session for one serial number against one form.
-- part_id FKs to part.id (logical reference; no FK constraint).
-- test_order is a snapshot of form.test_order at record creation.

DROP TABLE IF EXISTS form_record CASCADE;

CREATE TABLE form_record (
  id                     INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id                INTEGER      NOT NULL,             -- FK to form.id.
  part_id                INTEGER,                            -- FK to part.id (logical).
  record_date            TIMESTAMP,
  serial_number          VARCHAR(64),
  subject_part_number    VARCHAR(64),                       -- Denormalized PN at record creation.
  subject_pn_description  VARCHAR(64),                      -- Denormalized PN description.
  test_order             TEXT,                              -- Snapshot of form.test_order.
  comments               TEXT,
  instrument_type        VARCHAR(100),                      -- Matched against form_row.instrument_types.
  is_locked              BOOLEAN      NOT NULL DEFAULT FALSE, -- TRUE = locked (Complete or Approved).
  is_approved            BOOLEAN      NOT NULL DEFAULT FALSE, -- TRUE = reviewer-approved.
  is_active              BOOLEAN      NOT NULL DEFAULT TRUE,  -- FALSE = soft-deleted.
  created_at             TIMESTAMP,
  updated_at             TIMESTAMP,
  form_revision          INTEGER                             -- Snapshot of form.revision (#260). NULL pre-#260.
);

-- FK deferred (mirrors SQL Server set):
-- ALTER TABLE form_record ADD CONSTRAINT FK_form_record_form FOREIGN KEY (form_id) REFERENCES form (id);
