-- genealogy: edge table recording provenance — which parent lot/unit was consumed
-- into which child lot/unit (traceability epic #736 slice 4, #741; widened from the
-- former lot_genealogy, #676/#568). Each endpoint is a lot OR a unit; the
-- exactly-one-parent / exactly-one-child CHECKs (Q11) guarantee every edge names
-- precisely one parent FK and one child FK. Existing lot->lot rows stay valid (unit
-- columns NULL). Many-to-many. Recurse child_*_id -> parent_*_id to trace an output
-- back to its raw vendor lots / serialized children.
-- Requires lot and unit to exist first (FKs below).

DROP TABLE IF EXISTS genealogy CASCADE;

CREATE TABLE genealogy (
  id              INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_lot_id   INTEGER        NULL,             -- FK to lot.id  (consumed component lot).
  parent_unit_id  INTEGER        NULL,             -- FK to unit.id (consumed component unit).
  child_lot_id    INTEGER        NULL,             -- FK to lot.id  (produced output lot).
  child_unit_id   INTEGER        NULL,             -- FK to unit.id (produced output unit).
  qty_consumed    NUMERIC(15,5)  NOT NULL DEFAULT 0,   -- Quantity of the parent consumed into the child.
  CONSTRAINT CK_gen_one_parent CHECK (
    (CASE WHEN parent_lot_id  IS NULL THEN 0 ELSE 1 END) +
    (CASE WHEN parent_unit_id IS NULL THEN 0 ELSE 1 END) = 1),
  CONSTRAINT CK_gen_one_child CHECK (
    (CASE WHEN child_lot_id  IS NULL THEN 0 ELSE 1 END) +
    (CASE WHEN child_unit_id IS NULL THEN 0 ELSE 1 END) = 1)
);

ALTER TABLE genealogy ADD CONSTRAINT FK_gen_parent_lot  FOREIGN KEY (parent_lot_id)  REFERENCES lot (id);
ALTER TABLE genealogy ADD CONSTRAINT FK_gen_parent_unit FOREIGN KEY (parent_unit_id) REFERENCES unit (id);
ALTER TABLE genealogy ADD CONSTRAINT FK_gen_child_lot   FOREIGN KEY (child_lot_id)   REFERENCES lot (id);
ALTER TABLE genealogy ADD CONSTRAINT FK_gen_child_unit  FOREIGN KEY (child_unit_id)  REFERENCES unit (id);
CREATE INDEX IX_gen_parent_lot  ON genealogy (parent_lot_id);
CREATE INDEX IX_gen_parent_unit ON genealogy (parent_unit_id);
CREATE INDEX IX_gen_child_lot   ON genealogy (child_lot_id);
CREATE INDEX IX_gen_child_unit  ON genealogy (child_unit_id);
