-- inventory_transaction: append-only ledger of stock movements (#272 / #274).
-- Every row carries a SIGNED qty; a part's on-hand = SUM(qty).
-- part.stock_on_hand is a cached copy maintained by the app (not a trigger).
-- Requires po_line to exist first (FK on po_line_id).

DROP TABLE IF EXISTS inventory_transaction CASCADE;

CREATE TABLE inventory_transaction (
  id          INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id     INTEGER       NOT NULL,                                                    -- FK to part.id.
  txn_type    VARCHAR(20)   NOT NULL CONSTRAINT CK_inv_txn_type CHECK (txn_type IN ('receipt','issue','adjustment','count')),
  qty         NUMERIC(16,8) NOT NULL,                                                     -- Signed.
  txn_date    DATE          NOT NULL DEFAULT CURRENT_DATE,
  username    VARCHAR(128)  NOT NULL DEFAULT '',
  reference   VARCHAR(255),
  note        TEXT,
  po_line_id  INTEGER       NULL,                                                        -- FK to po_line.id for receipts (#269).
  lot_id      INTEGER       NULL,                                                        -- FK to lot.id (#676): lot touched by this movement; NULL if part not lot-tracked.
  build_id    INTEGER       NULL,                                                        -- FK to build.id (#677): build event that produced this row; NULL otherwise.
  created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE inventory_transaction ADD CONSTRAINT FK_inv_txn_PN      FOREIGN KEY (part_id)    REFERENCES part (id);
ALTER TABLE inventory_transaction ADD CONSTRAINT FK_inv_txn_po_line FOREIGN KEY (po_line_id) REFERENCES po_line (id);
-- FK_inv_txn_lot (lot_id → lot.id) is added in SQL/postgres/lot.sql, after lot exists.
-- FK_inv_txn_build (build_id → build.id) is added in SQL/postgres/build.sql, after build exists.
CREATE INDEX IX_inv_txn_part ON inventory_transaction (part_id, txn_date);
