-- logs: audit log of SQL operations performed by the application.

DROP TABLE IF EXISTS logs CASCADE;

CREATE TABLE logs (
  id           INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username     VARCHAR(127),
  date_logged  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  sql_string   TEXT
);
