-- lot: one lot (batch) instance of a part (#676, part of the #568 lot control epic).
-- Created at goods receipt for a lot-tracked purchased part (po_line_id set,
-- lot_number defaults to the PO number) or by a build producing a lot-tracked output
-- (po_line_id NULL). vendor_lot_number captures the supplier's own lot ID.
-- part.is_lot_tracked gates which parts get a lot. Requires part and po_line first;
-- build must also exist for the deferred output-lot FK at the bottom.

DROP TABLE IF EXISTS lot CASCADE;

CREATE TABLE lot (
  id                 INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id            INTEGER       NOT NULL,                        -- FK to part.id (the part this lot is of).
  lot_number         VARCHAR(255)  NOT NULL DEFAULT '',             -- Internal lot #; defaults to PO number / build ref, editable.
  vendor_lot_number  VARCHAR(255)  NULL,                            -- Supplier's own lot/batch ID (purchased lots); NULL otherwise.
  source             VARCHAR(10)   NULL CONSTRAINT CK_lot_source CHECK (source IN ('purchase', 'build', 'adjust')), -- How the lot originated (#744): purchase/build/adjust. NULL = not yet classified.
  po_line_id         INTEGER       NULL,                            -- FK to po_line.id for purchased receipts; NULL for manufactured lots.
  created_at         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_active          BOOLEAN       NOT NULL DEFAULT TRUE
);

ALTER TABLE lot ADD CONSTRAINT FK_lot_part    FOREIGN KEY (part_id)    REFERENCES part (id);
ALTER TABLE lot ADD CONSTRAINT FK_lot_po_line FOREIGN KEY (po_line_id) REFERENCES po_line (id);
CREATE INDEX IX_lot_part ON lot (part_id, is_active);

-- Wire the lot_id references other tables carry, now that lot exists (added here so
-- those tables can be created before lot in the run order):
--   build.output_lot_id (#675 placeholder → lot, #676)
--   inventory_transaction.lot_id (#676): lot a receipt/issue/adjustment touched
ALTER TABLE build ADD CONSTRAINT FK_build_output_lot FOREIGN KEY (output_lot_id) REFERENCES lot (id);
ALTER TABLE inventory_transaction ADD CONSTRAINT FK_inv_txn_lot FOREIGN KEY (lot_id) REFERENCES lot (id);
