-- lot_genealogy: self-referencing edge table linking a consumed parent lot to the
-- child lot it was built into (#676, part of the #568 lot control epic). A build
-- writes one row per lot-tracked component lot consumed, but only when the output
-- part is itself lot-tracked (so a child lot exists). Many-to-many, mirroring bom's
-- parent/child shape one level down at the lot-instance level. Recurse
-- child_lot_id -> parent_lot_id to trace an output lot back to raw vendor lots.
-- Requires lot to exist first (FKs below).

DROP TABLE IF EXISTS lot_genealogy CASCADE;

CREATE TABLE lot_genealogy (
  id             INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_lot_id  INTEGER        NOT NULL,             -- FK to lot.id (the consumed component lot).
  child_lot_id   INTEGER        NOT NULL,             -- FK to lot.id (the produced output lot).
  qty_consumed   NUMERIC(15,5)  NOT NULL DEFAULT 0    -- Quantity of the parent lot consumed into the child.
);

ALTER TABLE lot_genealogy ADD CONSTRAINT FK_lot_gen_parent FOREIGN KEY (parent_lot_id) REFERENCES lot (id);
ALTER TABLE lot_genealogy ADD CONSTRAINT FK_lot_gen_child  FOREIGN KEY (child_lot_id)  REFERENCES lot (id);
CREATE INDEX IX_lot_gen_child  ON lot_genealogy (child_lot_id);
CREATE INDEX IX_lot_gen_parent ON lot_genealogy (parent_lot_id);
