-- mfg_part: one row per (internal part, manufacturer, manufacturer PN).
-- part_id FKs to part.id. mfg_id FKs to company.id.

DROP TABLE IF EXISTS mfg_part CASCADE;

CREATE TABLE mfg_part (
  id               INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id          INTEGER       NOT NULL,    -- FK to part.id.
  mfg_id           INTEGER       NOT NULL,    -- FK to company.id (the manufacturer).
  mfg_part_number  VARCHAR(100)  NOT NULL,    -- Manufacturer's part number.
  description      VARCHAR(250),
  is_active        BOOLEAN       NOT NULL DEFAULT TRUE   -- Soft-delete; FALSE = deleted.
);

ALTER TABLE mfg_part ADD CONSTRAINT FK_mfg_part_pn  FOREIGN KEY (part_id) REFERENCES part (id);
ALTER TABLE mfg_part ADD CONSTRAINT FK_mfg_part_mfg FOREIGN KEY (mfg_id)  REFERENCES company (id);
-- One active row per (part, manufacturer, mfg_part_number). Partial index lets a
-- soft-deleted MPN be re-added.
CREATE UNIQUE INDEX UQ_mfg_part_combo ON mfg_part (part_id, mfg_id, mfg_part_number) WHERE is_active;
