-- named_queries: library of named, parameterized SELECT queries used for
-- spec_nom auto-fill. Referenced in spec_nom as: query:name(@param={test_id}).
--
-- Structure only. The standard rows are seeded in seed_test_data.sql; a
-- migrated ArxProd gets their Postgres text from
-- migrations/20260926120000_28_named_queries_postgres_text.sql.

DROP TABLE IF EXISTS named_queries CASCADE;

CREATE TABLE named_queries (
  id          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(100) NOT NULL CONSTRAINT UQ_named_queries_name UNIQUE,  -- key used in spec_nom.
  description VARCHAR(500),
  sql         TEXT         NOT NULL,          -- parameterized SELECT; @param_name syntax.
  params      VARCHAR(255),                   -- comma-separated expected param names.
  result_type VARCHAR(10)  NOT NULL DEFAULT 'list', -- 'list' | 'single' | 'multi'.
  is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_at  TIMESTAMPTZ DEFAULT now()
);
