-- named_queries: library of named, parameterized SELECT queries used for
-- spec_nom auto-fill. Referenced in spec_nom as: query:name(@param={test_id}).
--
-- Structure only. The SQL Server seed rows are intentionally NOT ported: the
-- stored `sql` column holds engine-specific query text (TRY_CAST, CONVERT,
-- LIKE '%' + @pn + '%', is_active = 1) that will not run on Postgres. Those rows
-- are reference *data* carrying T-SQL and belong to the ArxProd -> Postgres data
-- migration, translated there (see SQL/postgres/README.md).

DROP TABLE IF EXISTS named_queries CASCADE;

CREATE TABLE named_queries (
  id          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(100) NOT NULL CONSTRAINT UQ_named_queries_name UNIQUE,  -- key used in spec_nom.
  description VARCHAR(500),
  sql         TEXT         NOT NULL,          -- parameterized SELECT; @param_name syntax.
  params      VARCHAR(255),                   -- comma-separated expected param names.
  result_type VARCHAR(10)  NOT NULL DEFAULT 'list', -- 'list' | 'single' | 'multi'.
  is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_at  TIMESTAMPTZ DEFAULT now()
);
