-- part: the core parts catalog. The part_number COLUMN is the human-readable PN.
-- attachment_count and po_line_count are denormalized counts. On SQL Server they
-- are maintained by triggers; those are NOT yet ported to Postgres (see
-- SQL/postgres/README.md), so the columns are unmaintained here for now.
-- price_id / default_supplier_id / unit_id FKs are mostly deferred - see #213.

DROP TABLE IF EXISTS part CASCADE;

CREATE TABLE part (
  id                  INTEGER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number         VARCHAR(255)     NOT NULL CONSTRAINT UQ_part_number_part_number UNIQUE,
  category            VARCHAR(10)      DEFAULT 'BUY'
                                       CONSTRAINT CK_part_number_category CHECK (category IN ('', 'ASM', 'BUY', 'DWG', 'DOC', 'FORM', 'MFG', 'OPS', 'RAW', 'SVC', 'TOOL')),
  revision            VARCHAR(10)      DEFAULT '',
  title               VARCHAR(255)     DEFAULT '',
  detail              VARCHAR(255)     DEFAULT '',
  release_status      VARCHAR(255)     NOT NULL DEFAULT 'U',   -- U = Under Review, A = Active, D = Deprecated.
  requested_by        VARCHAR(50)      DEFAULT '',
  notes               TEXT             DEFAULT '',
  user_field_1        VARCHAR(255)     DEFAULT '',
  user_field_2        VARCHAR(255)     DEFAULT '',
  user_field_3        VARCHAR(255)     DEFAULT '',
  user_field_4        VARCHAR(255)     DEFAULT '',
  user_field_5        VARCHAR(255)     DEFAULT '',
  user_field_6        VARCHAR(255)     DEFAULT '',
  user_field_7        VARCHAR(255)     DEFAULT '',
  user_field_8        VARCHAR(255)     DEFAULT '',
  user_field_9        VARCHAR(255)     DEFAULT '',
  user_field_10       VARCHAR(255)     DEFAULT '',
  created_date        DATE             DEFAULT CURRENT_DATE,
  last_rollup_cost    NUMERIC(16,8)    NULL,
  last_rollup_at      TIMESTAMP        NULL,
  attachment_count    INTEGER          DEFAULT 0,             -- Denormalized; see header note.
  primary_attachment_id INTEGER        DEFAULT 0,
  current_cost        NUMERIC(16,8)    DEFAULT 0,
  is_active           BOOLEAN          DEFAULT TRUE,
  po_line_count       INTEGER          DEFAULT 0,             -- Denormalized; see header note.
  modified_date       DATE             DEFAULT CURRENT_DATE,
  price_id            INTEGER          DEFAULT 0,             -- FK to price; deferred (#213).
  default_supplier_id INTEGER          NULL,                 -- FK to company.id; deferred (#465/#213).
  unit_id             INTEGER          NULL,                 -- FK to unit.unit_id.
  stock_on_hand       NUMERIC(16,8)    NOT NULL DEFAULT 0,   -- Cached inventory balance (#272); app-maintained.
  reorder_min         NUMERIC(16,8)    NULL                  -- Reorder point (#273); NULL = none.
);

ALTER TABLE part ADD CONSTRAINT FK_part_number_unit FOREIGN KEY (unit_id) REFERENCES unit (unit_id);
