-- part: the core parts catalog. The part_number COLUMN is the human-readable PN.
-- attachment_count and po_line_count are denormalized counts, maintained by
-- triggers (SQL/postgres/triggers.sql).
-- price_id / default_supplier_id / uom_id FKs are all enforced now (#735, follow-up to #213).

DROP TABLE IF EXISTS part CASCADE;

CREATE TABLE part (
  id                  INTEGER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number         VARCHAR(255)     NOT NULL CONSTRAINT UQ_part_number_part_number UNIQUE,
  category            VARCHAR(10)      DEFAULT 'BUY'
                                       CONSTRAINT CK_part_number_category CHECK (category IN ('', 'ASM', 'BUY', 'DWG', 'DOC', 'FORM', 'MFG', 'OPS', 'RAW', 'SVC', 'TOOL')),
  revision            VARCHAR(10)      DEFAULT '',
  description         VARCHAR(255)     DEFAULT '',
  detail              VARCHAR(255)     DEFAULT '',
  release_status      VARCHAR(255)     NOT NULL DEFAULT 'U'
                                       CONSTRAINT CK_part_number_release_status CHECK (release_status IN ('U','A','D')),  -- U = Under Review, A = Active, D = Deprecated (#542); CHECK added #540/#542.
  requested_by        VARCHAR(50)      DEFAULT '',
  notes               TEXT             DEFAULT '',
  user_field_1        VARCHAR(255)     DEFAULT '',
  user_field_2        VARCHAR(255)     DEFAULT '',
  user_field_3        VARCHAR(255)     DEFAULT '',
  user_field_4        VARCHAR(255)     DEFAULT '',
  user_field_5        VARCHAR(255)     DEFAULT '',
  user_field_6        VARCHAR(255)     DEFAULT '',
  user_field_7        VARCHAR(255)     DEFAULT '',
  user_field_8        VARCHAR(255)     DEFAULT '',
  user_field_9        VARCHAR(255)     DEFAULT '',
  user_field_10       VARCHAR(255)     DEFAULT '',
  created_date        DATE             DEFAULT CURRENT_DATE,
  last_rollup_cost    NUMERIC(16,8)    NULL,
  last_rollup_at      TIMESTAMP        NULL,
  attachment_count    INTEGER          DEFAULT 0,             -- Denormalized; see header note.
  primary_attachment_id INTEGER        NULL,
  current_cost        NUMERIC(16,8)    DEFAULT 0,
  is_active           BOOLEAN          DEFAULT TRUE,
  po_line_count       INTEGER          DEFAULT 0,             -- Denormalized; see header note.
  modified_date       DATE             DEFAULT CURRENT_DATE,
  price_id            INTEGER          NULL,                  -- FK to price.id.
  default_supplier_id INTEGER          NULL,                 -- FK to company.id.
  uom_id              INTEGER          NULL,                 -- FK to uom.uom_id.
  stock_on_hand       NUMERIC(16,8)    NOT NULL DEFAULT 0,   -- Cached inventory balance (#272); app-maintained.
  reorder_min         NUMERIC(16,8)    NULL,                 -- Reorder point (#273); NULL = none.
  is_lot_tracked      BOOLEAN          NOT NULL DEFAULT FALSE, -- Lot/batch control (#676); receipt/build create a lot row when TRUE.
  tracking_mode       VARCHAR(10)      NOT NULL DEFAULT 'none'
                                       CONSTRAINT CK_part_number_tracking_mode CHECK (tracking_mode IN ('none', 'lot', 'serial', 'lot_serial'))
                                       -- Traceability epic (#736) slice 6 (#743): additive/inert, see SQL/part.sql.
);

ALTER TABLE part ADD CONSTRAINT FK_part_number_uom FOREIGN KEY (uom_id) REFERENCES uom (uom_id);
ALTER TABLE part ADD CONSTRAINT FK_part_default_supplier FOREIGN KEY (default_supplier_id) REFERENCES company (id);
ALTER TABLE part ADD CONSTRAINT FK_part_price FOREIGN KEY (price_id) REFERENCES price (id);
ALTER TABLE part ADD CONSTRAINT FK_part_primary_attachment FOREIGN KEY (primary_attachment_id) REFERENCES part_attachment (id);
