-- part_attachment: file and URL attachments linked to a part.
-- Deletions are soft-delete only (is_active = FALSE); never hard-delete rows.
-- attachment_count on part is maintained by a trigger on SQL Server; that trigger
-- is NOT yet ported to Postgres (see SQL/postgres/README.md).

DROP TABLE IF EXISTS part_attachment CASCADE;

CREATE TABLE part_attachment (
  id             INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id        INTEGER NOT NULL REFERENCES part (id),  -- FK to part.id.
  file_name      VARCHAR(1000),  -- File path or URL.
  category       VARCHAR(500),   -- Attachment category (options in app_config 'attachment_categories').
  part_revision  VARCHAR(10),
  sort_order     INTEGER        DEFAULT 1,
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  comment        VARCHAR(500)    -- Free-text note (#585).
);
