-- po_line: Purchase Order line items. Each row is one line on a PO.
-- po_id FKs to purchase_order.id. part_id FKs to part.id (nullable).
-- part.po_line_count is a denormalized count maintained by a trigger on SQL Server;
-- that trigger is NOT yet ported to Postgres (see SQL/postgres/README.md).

DROP TABLE IF EXISTS po_line CASCADE;

CREATE TABLE po_line (
  id                   INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_id                INTEGER        NOT NULL,       -- FK to purchase_order.id.
  part_number_snapshot VARCHAR(255),                 -- Denormalized part number at time of order.
  revision_snapshot    VARCHAR(10),                  -- Denormalized revision at time of order.
  part_id              INTEGER,                        -- FK to part.id. Nullable.
  line_number          INTEGER        NOT NULL,       -- Line item number on the PO.
  description          TEXT,                          -- Description at time of order.
  qty                  NUMERIC(11,2)  NOT NULL,       -- Quantity ordered.
  unit_cost            NUMERIC(16,8)  NOT NULL DEFAULT 0,
  vendor_part_number   VARCHAR(55),
  lead_time_days       INTEGER,                        -- Quoted lead time (#270). NULL = not quoted.
  received_qty         NUMERIC(11,2)  NOT NULL DEFAULT 0,  -- Cumulative qty received (#269).
  date_received        DATE                            -- Most recent receipt date (#269). NULL = none.
);

ALTER TABLE po_line ADD CONSTRAINT FK_po_line_po   FOREIGN KEY (po_id)   REFERENCES purchase_order (id);
ALTER TABLE po_line ADD CONSTRAINT FK_po_line_part FOREIGN KEY (part_id) REFERENCES part (id);
