-- price: quantity-break pricing for parts by supplier.
-- Multiple rows per part/supplier represent quantity-break pricing; inactive rows
-- are retained as price history.

DROP TABLE IF EXISTS price CASCADE;

CREATE TABLE price (
  id             INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id        INTEGER        NOT NULL,    -- FK to part.id.
  supplier_id    INTEGER        NOT NULL,    -- FK to company.id.
  price_ea       NUMERIC(13,6)  DEFAULT 0,   -- Per-unit price.
  price_pack     NUMERIC(13,6)  DEFAULT 0,   -- Total price for pack_size units.
  pack_size      NUMERIC(13,6)  DEFAULT 1,   -- Units per pack.
  is_active      BOOLEAN        DEFAULT TRUE,
  effective_date DATE           DEFAULT CURRENT_DATE
);

ALTER TABLE price ADD CONSTRAINT FK_price_PN       FOREIGN KEY (part_id)     REFERENCES part (id);
ALTER TABLE price ADD CONSTRAINT FK_price_company  FOREIGN KEY (supplier_id) REFERENCES company (id);
-- Only one active row per (part, supplier, pack_size) at a time. Inactive rows
-- (price history) are exempt via the partial predicate.
CREATE UNIQUE INDEX UQ_price_active_combo ON price (part_id, supplier_id, pack_size) WHERE is_active;
