-- purchase_order: Purchase Orders. 'number' is the human-readable PO number.
-- supplier_id = who the PO is sent to; receiver_id = bill-to / ship-to.
-- PO numbers are auto-assigned via po_number_seq. The app call site currently
-- emits T-SQL 'NEXT VALUE FOR'; on Postgres it must use nextval('po_number_seq')
-- (app-side change, not covered by this DDL - see SQL/postgres/README.md).
-- po_count on company is a denormalized count maintained by a trigger
-- (SQL/postgres/triggers.sql).

-- Sequence used to generate PO numbers.
CREATE SEQUENCE IF NOT EXISTS po_number_seq AS integer START WITH 1 INCREMENT BY 1 NO CYCLE;

DROP TABLE IF EXISTS purchase_order CASCADE;

CREATE TABLE purchase_order (
  -- Identity
  id                    INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number                VARCHAR(32)    NOT NULL CONSTRAINT UQ_purchase_order_number UNIQUE,

  -- Supplier
  supplier_id           INTEGER        NOT NULL,        -- FK to company.id.
  supplier_name         VARCHAR(127),                   -- Denormalized at time of order.
  supplier_contact      VARCHAR(127),
  supplier_contact_id   INTEGER,                         -- FK to contact.id. NULL for legacy/none.
  supplier_address      VARCHAR(255),
  supplier_city         VARCHAR(64),
  supplier_state        VARCHAR(64),
  supplier_zipcode      VARCHAR(10),
  supplier_country      VARCHAR(127),
  supplier_phone_number VARCHAR(32),
  supplier_fax_number   VARCHAR(32),
  supplier_email        VARCHAR(127),

  -- Receiver / Ship-To
  receiver_id           INTEGER,                         -- FK to company.id. Nullable.
  receiver_name         VARCHAR(255),
  receiver_contact      VARCHAR(127),
  receiver_contact_id   INTEGER,                         -- FK to contact.id. NULL for legacy/none.
  receiver_address      VARCHAR(255),
  receiver_city         VARCHAR(64),
  receiver_state        VARCHAR(64),
  receiver_zipcode      VARCHAR(10),
  receiver_country      VARCHAR(127),
  receiver_phone        VARCHAR(32),
  receiver_fax          VARCHAR(32),
  receiver_email        VARCHAR(127),

  -- Order details
  orderer               VARCHAR(255),
  account_id            VARCHAR(127),
  date_ordered          DATE,
  date_requested        DATE,
  date_closed           DATE,
  date_printed          DATE,
  date_modified         TIMESTAMPTZ    DEFAULT now(),

  -- Financials
  tax1                  NUMERIC(10,5),
  shipping_cost         NUMERIC(10,5),
  misc_cost             NUMERIC(10,5),
  total_cost            NUMERIC(16,8),

  -- Notes & status
  notes                 TEXT,                            -- Prints on PO document.
  internal_notes        TEXT           DEFAULT '',       -- Internal-only.
  is_active             BOOLEAN        DEFAULT TRUE,      -- Derived from status - do not set directly.
  status                VARCHAR(20)    DEFAULT 'draft' CONSTRAINT CK_purchase_order_status CHECK (status IN ('rfq','draft','open','sent','partially_received','closed','cancelled')),
  approval_status       VARCHAR(20)    DEFAULT 'not_submitted' CONSTRAINT CK_purchase_order_approval_status CHECK (approval_status IN ('not_submitted','pending','approved','rejected')),
  rfq_group_id          INTEGER                          -- RFQ grouping (#270). NULL for ordinary POs.
);

ALTER TABLE purchase_order ADD CONSTRAINT FK_purchase_order_company  FOREIGN KEY (supplier_id) REFERENCES company (id);
ALTER TABLE purchase_order ADD CONSTRAINT FK_purchase_order_receiver FOREIGN KEY (receiver_id) REFERENCES company (id);
ALTER TABLE purchase_order ADD CONSTRAINT FK_purchase_order_supplier_contact FOREIGN KEY (supplier_contact_id) REFERENCES contact (id);
ALTER TABLE purchase_order ADD CONSTRAINT FK_purchase_order_receiver_contact FOREIGN KEY (receiver_contact_id) REFERENCES contact (id);

-- purchase_order_history: append-only activity log for a PO (#271 + #267).
-- event_type='status'   -> a lifecycle transition (from_status -> to_status).
-- event_type='approval' -> an approval action in `action`, with optional `note`.
DROP TABLE IF EXISTS purchase_order_history CASCADE;

CREATE TABLE purchase_order_history (
  id          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_id       INTEGER      NOT NULL,                                          -- FK to purchase_order.id.
  event_type  VARCHAR(20)  NOT NULL CONSTRAINT CK_purchase_order_history_event CHECK (event_type IN ('status','approval')),
  from_status VARCHAR(20),
  to_status   VARCHAR(20),
  action      VARCHAR(20),
  note        TEXT,
  changed_by  VARCHAR(128) NOT NULL DEFAULT '',
  changed_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

ALTER TABLE purchase_order_history ADD CONSTRAINT FK_purchase_order_history_po FOREIGN KEY (po_id) REFERENCES purchase_order (id);
CREATE INDEX IX_purchase_order_history_po ON purchase_order_history (po_id, changed_at);
