-- record_events: audit trail for state changes on form_record.
-- form_record_id FKs to form_record.id.

DROP TABLE IF EXISTS record_events CASCADE;

CREATE TABLE record_events (
  id             INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_record_id INTEGER      NOT NULL REFERENCES form_record (id),  -- FK to form_record.id.
  event_type     VARCHAR(50)  NOT NULL,                              -- 'locked', 'unlocked', …
  username       VARCHAR(255),                                       -- OS username at time of event.
  event_date     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  comments       TEXT                                                -- User-supplied comment.
);
