-- record_events: audit trail for state changes on test_record.
-- test_record_id FKs to test_record.id.

DROP TABLE IF EXISTS record_events CASCADE;

CREATE TABLE record_events (
  id             INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_record_id INTEGER      NOT NULL REFERENCES test_record (id),  -- FK to test_record.id.
  event_type     VARCHAR(50)  NOT NULL,                              -- 'locked', 'unlocked', …
  username       VARCHAR(255),                                       -- OS username at time of event.
  event_date     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  comments       TEXT                                                -- User-supplied comment.
);
