-- release_notes: application version history and changelog.
-- show_users controls whether a release note is surfaced to users in the UI.

DROP TABLE IF EXISTS release_notes CASCADE;

CREATE TABLE release_notes (
  id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version       VARCHAR(8)   DEFAULT '0.0.0',       -- Semantic version string.
  notes         TEXT         DEFAULT '',
  date_changed  DATE         DEFAULT CURRENT_DATE,
  show_users    BOOLEAN      DEFAULT FALSE,
  username      VARCHAR(64)  DEFAULT ''
);
