-- supplier_part: sourcing links - maps internal parts to supplier catalog entries.
-- SUNumOfLNKs on company is a denormalized count maintained by a trigger
-- (SQL/postgres/triggers.sql).

DROP TABLE IF EXISTS supplier_part CASCADE;

CREATE TABLE supplier_part (
  id                 INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  supplier_id        INTEGER        NOT NULL,    -- FK to company.id (who you buy from).
  part_id            INTEGER        NOT NULL,    -- FK to part.id (the internal part).
  mfg_part_id        INTEGER,                    -- FK to mfg_part.id. NULL = buying direct.
  uom_id             INTEGER,                    -- FK to uom.uom_id. NULL = same as part's base unit.

  supplier_pn        VARCHAR(55),                -- Supplier's own part number / SKU.
  supplier_desc      VARCHAR(100),

  min_increment      NUMERIC(11,2),              -- Minimum order increment (qty).
  setup_cost         NUMERIC(11,2),              -- One-time setup / tooling cost.
  lead_time          VARCHAR(55),                -- Lead time as descriptive text.

  preference         INTEGER        DEFAULT 1    -- Supplier preference order (1 = preferred).
);

ALTER TABLE supplier_part ADD CONSTRAINT FK_supplier_part_company  FOREIGN KEY (supplier_id)  REFERENCES company (id);
ALTER TABLE supplier_part ADD CONSTRAINT FK_supplier_part_pn       FOREIGN KEY (part_id)      REFERENCES part (id);
ALTER TABLE supplier_part ADD CONSTRAINT FK_supplier_part_mfg_part FOREIGN KEY (mfg_part_id)  REFERENCES mfg_part (id);
ALTER TABLE supplier_part ADD CONSTRAINT FK_supplier_part_uom      FOREIGN KEY (uom_id)       REFERENCES uom (uom_id);
