-- test_definition_history: audit trail for changes to test_definition rows.
-- On SQL Server this is populated by trg_test_definition_history (AFTER UPDATE),
-- which recovers the app user from CONTEXT_INFO(). That trigger is NOT yet ported
-- to Postgres (see SQL/postgres/README.md and design §3); until it is, this table
-- is not populated. The Postgres equivalent, if the trigger survives review, reads
-- the username from a session GUC (current_setting('arx.username')) instead of
-- CONTEXT_INFO().

DROP TABLE IF EXISTS test_definition_history CASCADE;

CREATE TABLE test_definition_history (
  id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id       INTEGER      NOT NULL,              -- FK to test_definition.id.
  changed_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  changed_by    VARCHAR(128) NOT NULL DEFAULT CURRENT_USER,  -- set by trigger when ported.
  -- snapshot of values before the update
  type          INTEGER,
  parameter     VARCHAR(255),
  specification VARCHAR(255),
  spec_units    VARCHAR(255),
  spec_min      VARCHAR(255),
  spec_max      VARCHAR(255),
  spec_nom      VARCHAR(255),
  default_result VARCHAR(255),
  hide_formula  VARCHAR(255),
  pf_type       VARCHAR(50),
  instrument_types VARCHAR(255),
  format        VARCHAR(255),
  comment       VARCHAR(500),
  category      VARCHAR(255),
  sheet_name    VARCHAR(255)
);
