-- unit: one serialized instance (Tier-3 identity) of a part (#740, traceability epic
-- #736 slice 3 — the keystone). Postgres port of SQL/unit.sql; see that file's header for
-- the full rationale. A serial becomes a real row with FKs, not a parsed string, replacing
-- the old trace_id / is_batch approach (docs/plans/736-traceability-data-model.md §4.1).
--
-- Created lazily one at a time at test time (Q5); exists only for serial / lot_serial
-- tracking_mode. lot_id set for a serialized unit inside a lot, build_id for a build-sourced
-- unit — both individually nullable; a `manual` unit (#799: pre-existing serial, no test
-- record) may legitimately have neither, distinguished by source. serial_number is a
-- STRING, UNIQUE per part_id.
--
-- Additive/unused until slice 8. Requires part, lot, and build to exist first (FKs below).

DROP TABLE IF EXISTS unit CASCADE;

CREATE TABLE unit (
  id             INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id        INTEGER       NOT NULL,                        -- FK to part.id (the part this unit is an instance of).
  lot_id         INTEGER       NULL,                            -- FK to lot.id; set for a serialized unit inside a lot, NULL for serial-only parts.
  build_id       INTEGER       NULL,                            -- FK to build.id; set for a build-sourced unit, NULL otherwise.
  serial_number  VARCHAR(255)  NOT NULL,                        -- Serial entered at test time; STRING (non-numeric allowed), UNIQUE per part_id.
  created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_active      BOOLEAN       NOT NULL DEFAULT TRUE,           -- Soft-delete / scrap flag.
  source         VARCHAR(10)   NOT NULL DEFAULT 'test' CHECK (source IN ('test', 'manual')), -- How the unit was minted (#799): test (test-record save) or manual (back-filled pre-existing serial, no test record).
  CONSTRAINT UQ_unit_serial     UNIQUE (part_id, serial_number)
);

ALTER TABLE unit ADD CONSTRAINT FK_unit_part  FOREIGN KEY (part_id)  REFERENCES part (id);
ALTER TABLE unit ADD CONSTRAINT FK_unit_lot   FOREIGN KEY (lot_id)   REFERENCES lot (id);
ALTER TABLE unit ADD CONSTRAINT FK_unit_build FOREIGN KEY (build_id) REFERENCES build (id);
CREATE INDEX IX_unit_part ON unit (part_id, is_active);
