-- unit: reference list of units of measure.
-- unit_type groups entries for UI display: count | volume | length | mass | package.

DROP TABLE IF EXISTS unit CASCADE;

CREATE TABLE unit (
    unit_id       INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abbreviation  VARCHAR(20)  NOT NULL,   -- Short form: EA, mL, kg, REEL, …
    display_name  VARCHAR(50)  NOT NULL,   -- Long form: Each, Milliliter, …
    unit_type     VARCHAR(20)  NOT NULL    -- count | volume | length | mass | package
);

INSERT INTO unit (abbreviation, display_name, unit_type) VALUES
    ('EA',    'Each',         'count'),
    ('PC',    'Piece',        'count'),
    ('mL',    'Milliliter',   'volume'),
    ('L',     'Liter',        'volume'),
    ('oz',    'Fluid Ounce',  'volume'),
    ('mm',    'Millimeter',   'length'),
    ('m',     'Meter',        'length'),
    ('IN',    'Inch',         'length'),
    ('FT',    'Foot',         'length'),
    ('g',     'Gram',         'mass'),
    ('kg',    'Kilogram',     'mass'),
    ('lb',    'Pound',        'mass'),
    ('PK',    'Pack',         'package'),
    ('REEL',  'Reel',         'package'),
    ('BOX',   'Box',          'package'),
    ('BTL',   'Bottle',       'package'),
    ('SPOOL', 'Spool',        'package');
