-- users: application user accounts (issue #267 approvals, #249 record unlock, etc.).

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL,
    display_name  VARCHAR(128) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    can_approve_po BOOLEAN     NOT NULL DEFAULT FALSE,  -- may approve/reject POs (#267).
    can_approve_records BOOLEAN NOT NULL DEFAULT FALSE, -- may approve/unlock records (#249).
    is_admin      BOOLEAN      NOT NULL DEFAULT FALSE,  -- may manage user accounts (create/reset/deactivate/grant) (#750).
    default_po_contact_id  INTEGER NULL,               -- per-user default PO receiver contact (#463).
    default_po_receiver_id INTEGER NULL,               -- per-user default PO receiver company (#463).
    accent_color  VARCHAR(20)  NULL,                   -- per-user UI accent theme key (#537).
    default_route VARCHAR(255) NULL,                   -- per-user landing page after login (#282).
    timezone      VARCHAR(64) NOT NULL DEFAULT 'America/Los_Angeles',  -- per-user IANA timezone for calendar-day bucketing of UTC audit timestamps (#847).
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT UQ_users_username UNIQUE (username)
);
