// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appconfig.sql

package dbq

import (
	"context"
)

const getAppSetting = `-- name: GetAppSetting :one

SELECT setting_value FROM app_config WHERE setting_key = $1
`

// app_config key/value settings (#190, #248). sqlc generates internal/dbq/appconfig.sql.go from
// this file; the service is appconfig.go. Infrastructure shared by every handler (company logo,
// DigiKey credentials, schema-version gate, Settings), so it is not tied to one domain.
func (q *Queries) GetAppSetting(ctx context.Context, settingKey string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAppSetting, settingKey)
	var setting_value string
	err := row.Scan(&setting_value)
	return setting_value, err
}

const upsertAppSetting = `-- name: UpsertAppSetting :exec
INSERT INTO app_config (setting_key, setting_value) VALUES ($1, $2)
ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value, updated_at = CURRENT_TIMESTAMP
`

type UpsertAppSettingParams struct {
	SettingKey   string
	SettingValue string
}

func (q *Queries) UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertAppSetting, arg.SettingKey, arg.SettingValue)
	return err
}
