// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package dbq

import (
	"context"
)

const companyFileInUse = `-- name: CompanyFileInUse :one
SELECT EXISTS (SELECT 1 FROM company_attachment
               WHERE file_path = $1 AND is_active = TRUE
                 AND supplier_attachment_id <> $2)
`

type CompanyFileInUseParams struct {
	FilePath  string
	ExcludeID int
}

func (q *Queries) CompanyFileInUse(ctx context.Context, arg CompanyFileInUseParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, companyFileInUse, arg.FilePath, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCompanyAttachment = `-- name: CreateCompanyAttachment :exec
INSERT INTO company_attachment (supplier_id, file_path, notes, sort_order, hash)
VALUES ($1, $2, $3::text, $4,
        $5::text)
`

type CreateCompanyAttachmentParams struct {
	SupplierID int
	FilePath   string
	Notes      string
	SortOrder  *int
	Hash       string
}

func (q *Queries) CreateCompanyAttachment(ctx context.Context, arg CreateCompanyAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createCompanyAttachment,
		arg.SupplierID,
		arg.FilePath,
		arg.Notes,
		arg.SortOrder,
		arg.Hash,
	)
	return err
}

const createGeneratedAttachment = `-- name: CreateGeneratedAttachment :exec
INSERT INTO part_attachment (part_id, file_name, part_revision, category, hash)
VALUES ($1, $2::text, $3::text, $4::text,
        $5::text)
`

type CreateGeneratedAttachmentParams struct {
	PartID       int
	FileName     string
	PartRevision string
	Category     string
	Hash         string
}

func (q *Queries) CreateGeneratedAttachment(ctx context.Context, arg CreateGeneratedAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createGeneratedAttachment,
		arg.PartID,
		arg.FileName,
		arg.PartRevision,
		arg.Category,
		arg.Hash,
	)
	return err
}

const createPartAttachment = `-- name: CreatePartAttachment :exec
INSERT INTO part_attachment (part_id, file_name, part_revision, category, sort_order, comment,
                             supplier_part_id, mfg_part_id, hash)
VALUES ($1, $2::text, $3::text, $4::text,
        $5, $6::text, $7, $8,
        $9::text)
`

type CreatePartAttachmentParams struct {
	PartID         int
	FileName       string
	PartRevision   string
	Category       string
	SortOrder      *int
	Comment        string
	SupplierPartID *int
	MfgPartID      *int
	Hash           string
}

func (q *Queries) CreatePartAttachment(ctx context.Context, arg CreatePartAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createPartAttachment,
		arg.PartID,
		arg.FileName,
		arg.PartRevision,
		arg.Category,
		arg.SortOrder,
		arg.Comment,
		arg.SupplierPartID,
		arg.MfgPartID,
		arg.Hash,
	)
	return err
}

const ensureCompanyPrimary = `-- name: EnsureCompanyPrimary :exec
UPDATE company SET primary_attachment_id = (
    SELECT a.supplier_attachment_id FROM company_attachment a
    WHERE a.supplier_id = company.id AND a.is_active = TRUE
    ORDER BY COALESCE(a.sort_order, 0), a.supplier_attachment_id LIMIT 1)
WHERE company.id = $1 AND (company.primary_attachment_id IS NULL OR NOT EXISTS (
    SELECT 1 FROM company_attachment x
    WHERE x.supplier_attachment_id = company.primary_attachment_id AND x.is_active = TRUE))
`

// EnsureCompanyPrimary is EnsurePartPrimary for a company (#121).
func (q *Queries) EnsureCompanyPrimary(ctx context.Context, supplierID int) error {
	_, err := q.db.ExecContext(ctx, ensureCompanyPrimary, supplierID)
	return err
}

const ensurePartPrimary = `-- name: EnsurePartPrimary :exec
UPDATE part SET primary_attachment_id = (
    SELECT a.id FROM part_attachment a
    WHERE a.part_id = part.id AND a.is_active = TRUE
      AND COALESCE(a.category, '') NOT IN ($1::text, $2::text)
    ORDER BY COALESCE(a.sort_order, 0), a.id LIMIT 1)
WHERE part.id = $3 AND (part.primary_attachment_id IS NULL OR NOT EXISTS (
    SELECT 1 FROM part_attachment x WHERE x.id = part.primary_attachment_id AND x.is_active = TRUE))
`

type EnsurePartPrimaryParams struct {
	PreviewCategory   string
	ThumbnailCategory string
	PartID            int
}

// EnsurePartPrimary points the part's primary at its first active attachment (lowest
// sort_order, ties by id), but only when the current primary is NULL or no longer
// active, so it is safe after every insert and soft-delete; with no active attachment
// left the primary is cleared (#121). The generated preview/thumbnail rows never
// become the primary.
func (q *Queries) EnsurePartPrimary(ctx context.Context, arg EnsurePartPrimaryParams) error {
	_, err := q.db.ExecContext(ctx, ensurePartPrimary, arg.PreviewCategory, arg.ThumbnailCategory, arg.PartID)
	return err
}

const findDuplicateCompanyAttachment = `-- name: FindDuplicateCompanyAttachment :one
SELECT a.supplier_attachment_id AS id, c.id AS owner_id, c.name AS label
FROM company_attachment a JOIN company c ON c.id = a.supplier_id
WHERE a.is_active = TRUE AND a.hash = $1::text AND a.supplier_attachment_id <> $2
ORDER BY a.supplier_attachment_id LIMIT 1
`

type FindDuplicateCompanyAttachmentParams struct {
	Hash      string
	ExcludeID int
}

type FindDuplicateCompanyAttachmentRow struct {
	ID      int
	OwnerID int
	Label   string
}

func (q *Queries) FindDuplicateCompanyAttachment(ctx context.Context, arg FindDuplicateCompanyAttachmentParams) (FindDuplicateCompanyAttachmentRow, error) {
	row := q.db.QueryRowContext(ctx, findDuplicateCompanyAttachment, arg.Hash, arg.ExcludeID)
	var i FindDuplicateCompanyAttachmentRow
	err := row.Scan(&i.ID, &i.OwnerID, &i.Label)
	return i, err
}

const findDuplicatePartAttachment = `-- name: FindDuplicatePartAttachment :one
SELECT a.id, p.id AS owner_id, p.part_number AS label
FROM part_attachment a JOIN part p ON p.id = a.part_id
WHERE a.is_active = TRUE AND a.hash = $1::text AND a.id <> $2
ORDER BY a.id LIMIT 1
`

type FindDuplicatePartAttachmentParams struct {
	Hash      string
	ExcludeID int
}

type FindDuplicatePartAttachmentRow struct {
	ID      int
	OwnerID int
	Label   string
}

func (q *Queries) FindDuplicatePartAttachment(ctx context.Context, arg FindDuplicatePartAttachmentParams) (FindDuplicatePartAttachmentRow, error) {
	row := q.db.QueryRowContext(ctx, findDuplicatePartAttachment, arg.Hash, arg.ExcludeID)
	var i FindDuplicatePartAttachmentRow
	err := row.Scan(&i.ID, &i.OwnerID, &i.Label)
	return i, err
}

const getCompanyAttachment = `-- name: GetCompanyAttachment :one
SELECT supplier_attachment_id, supplier_id, file_path, COALESCE(notes, '') AS notes, sort_order
FROM company_attachment WHERE supplier_attachment_id = $1
`

type GetCompanyAttachmentRow struct {
	SupplierAttachmentID int
	SupplierID           int
	FilePath             string
	Notes                string
	SortOrder            *int
}

func (q *Queries) GetCompanyAttachment(ctx context.Context, supplierAttachmentID int) (GetCompanyAttachmentRow, error) {
	row := q.db.QueryRowContext(ctx, getCompanyAttachment, supplierAttachmentID)
	var i GetCompanyAttachmentRow
	err := row.Scan(
		&i.SupplierAttachmentID,
		&i.SupplierID,
		&i.FilePath,
		&i.Notes,
		&i.SortOrder,
	)
	return i, err
}

const getCompanyAttachmentPath = `-- name: GetCompanyAttachmentPath :one
SELECT file_path FROM company_attachment WHERE supplier_attachment_id = $1 AND supplier_id = $2
`

type GetCompanyAttachmentPathParams struct {
	SupplierAttachmentID int
	SupplierID           int
}

func (q *Queries) GetCompanyAttachmentPath(ctx context.Context, arg GetCompanyAttachmentPathParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getCompanyAttachmentPath, arg.SupplierAttachmentID, arg.SupplierID)
	var file_path string
	err := row.Scan(&file_path)
	return file_path, err
}

const getGeneratedAttachment = `-- name: GetGeneratedAttachment :one
SELECT id, COALESCE(file_name, '') AS file_name FROM part_attachment
WHERE part_id = $1 AND category = $2::text AND is_active = TRUE
ORDER BY id LIMIT 1
`

type GetGeneratedAttachmentParams struct {
	PartID   int
	Category string
}

type GetGeneratedAttachmentRow struct {
	ID       int
	FileName string
}

func (q *Queries) GetGeneratedAttachment(ctx context.Context, arg GetGeneratedAttachmentParams) (GetGeneratedAttachmentRow, error) {
	row := q.db.QueryRowContext(ctx, getGeneratedAttachment, arg.PartID, arg.Category)
	var i GetGeneratedAttachmentRow
	err := row.Scan(&i.ID, &i.FileName)
	return i, err
}

const getPartAttachment = `-- name: GetPartAttachment :one
SELECT COALESCE(file_name, '') AS file_name, COALESCE(category, '') AS category,
       COALESCE(part_revision, '') AS part_revision, is_active
FROM part_attachment WHERE id = $1 AND part_id = $2
`

type GetPartAttachmentParams struct {
	ID     int
	PartID int
}

type GetPartAttachmentRow struct {
	FileName     string
	Category     string
	PartRevision string
	IsActive     bool
}

func (q *Queries) GetPartAttachment(ctx context.Context, arg GetPartAttachmentParams) (GetPartAttachmentRow, error) {
	row := q.db.QueryRowContext(ctx, getPartAttachment, arg.ID, arg.PartID)
	var i GetPartAttachmentRow
	err := row.Scan(
		&i.FileName,
		&i.Category,
		&i.PartRevision,
		&i.IsActive,
	)
	return i, err
}

const listCompanyAttachments = `-- name: ListCompanyAttachments :many

SELECT supplier_attachment_id, supplier_id, file_path, COALESCE(notes, '') AS notes, sort_order
FROM company_attachment WHERE supplier_id = $1 AND is_active = TRUE
ORDER BY sort_order, supplier_attachment_id
`

type ListCompanyAttachmentsRow struct {
	SupplierAttachmentID int
	SupplierID           int
	FilePath             string
	Notes                string
	SortOrder            *int
}

// ── company_attachment ───────────────────────────────────────────────────────
func (q *Queries) ListCompanyAttachments(ctx context.Context, supplierID int) ([]ListCompanyAttachmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompanyAttachments, supplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompanyAttachmentsRow
	for rows.Next() {
		var i ListCompanyAttachmentsRow
		if err := rows.Scan(
			&i.SupplierAttachmentID,
			&i.SupplierID,
			&i.FilePath,
			&i.Notes,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartAttachments = `-- name: ListPartAttachments :many

SELECT a.id, COALESCE(a.file_name, '') AS file_name, COALESCE(a.category, '') AS category,
       COALESCE(a.part_revision, '') AS part_revision, a.sort_order, COALESCE(a.comment, '') AS comment,
       a.supplier_part_id, a.mfg_part_id, COALESCE(sc.name, mc.name, '') AS vendor_name
FROM part_attachment a
LEFT JOIN supplier_part sp ON sp.id = a.supplier_part_id
LEFT JOIN company sc ON sc.id = sp.supplier_id
LEFT JOIN mfg_part mp ON mp.id = a.mfg_part_id
LEFT JOIN company mc ON mc.id = mp.mfg_id
WHERE a.part_id = $1 AND a.is_active = TRUE
ORDER BY a.sort_order, a.id
`

type ListPartAttachmentsRow struct {
	ID             int
	FileName       string
	Category       string
	PartRevision   string
	SortOrder      *int
	Comment        string
	SupplierPartID *int
	MfgPartID      *int
	VendorName     string
}

// ── part_attachment ──────────────────────────────────────────────────────────
func (q *Queries) ListPartAttachments(ctx context.Context, partID int) ([]ListPartAttachmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPartAttachments, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartAttachmentsRow
	for rows.Next() {
		var i ListPartAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Category,
			&i.PartRevision,
			&i.SortOrder,
			&i.Comment,
			&i.SupplierPartID,
			&i.MfgPartID,
			&i.VendorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mfgPartOfPart = `-- name: MfgPartOfPart :one
SELECT EXISTS (SELECT 1 FROM mfg_part WHERE id = $1 AND part_id = $2)
`

type MfgPartOfPartParams struct {
	ID     int
	PartID int
}

func (q *Queries) MfgPartOfPart(ctx context.Context, arg MfgPartOfPartParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, mfgPartOfPart, arg.ID, arg.PartID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const partFileInUse = `-- name: PartFileInUse :one
SELECT EXISTS (SELECT 1 FROM part_attachment
               WHERE file_name = $1::text AND is_active = TRUE AND id <> $2)
`

type PartFileInUseParams struct {
	FileName  string
	ExcludeID int
}

func (q *Queries) PartFileInUse(ctx context.Context, arg PartFileInUseParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, partFileInUse, arg.FileName, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const replacePartAttachmentPhoto = `-- name: ReplacePartAttachmentPhoto :exec
UPDATE part_attachment SET part_revision = $1::text, category = $2::text,
  sort_order = $3, comment = $4::text,
  file_name = $5::text, hash = $6::text
WHERE id = $7
`

type ReplacePartAttachmentPhotoParams struct {
	PartRevision string
	Category     string
	SortOrder    *int
	Comment      string
	FileName     string
	Hash         string
	ID           int
}

// ReplacePartAttachmentPhoto repoints a row at a pasted image; its vendor scope is kept.
func (q *Queries) ReplacePartAttachmentPhoto(ctx context.Context, arg ReplacePartAttachmentPhotoParams) error {
	_, err := q.db.ExecContext(ctx, replacePartAttachmentPhoto,
		arg.PartRevision,
		arg.Category,
		arg.SortOrder,
		arg.Comment,
		arg.FileName,
		arg.Hash,
		arg.ID,
	)
	return err
}

const setCompanyPrimary = `-- name: SetCompanyPrimary :exec
UPDATE company SET primary_attachment_id = $1 WHERE id = $2
`

type SetCompanyPrimaryParams struct {
	AttachmentID *int
	SupplierID   int
}

func (q *Queries) SetCompanyPrimary(ctx context.Context, arg SetCompanyPrimaryParams) error {
	_, err := q.db.ExecContext(ctx, setCompanyPrimary, arg.AttachmentID, arg.SupplierID)
	return err
}

const setPartPrimary = `-- name: SetPartPrimary :exec
UPDATE part SET primary_attachment_id = $1 WHERE id = $2
`

type SetPartPrimaryParams struct {
	AttachmentID *int
	PartID       int
}

func (q *Queries) SetPartPrimary(ctx context.Context, arg SetPartPrimaryParams) error {
	_, err := q.db.ExecContext(ctx, setPartPrimary, arg.AttachmentID, arg.PartID)
	return err
}

const softDeleteCompanyAttachment = `-- name: SoftDeleteCompanyAttachment :exec
UPDATE company_attachment SET is_active = FALSE WHERE supplier_attachment_id = $1 AND supplier_id = $2
`

type SoftDeleteCompanyAttachmentParams struct {
	SupplierAttachmentID int
	SupplierID           int
}

func (q *Queries) SoftDeleteCompanyAttachment(ctx context.Context, arg SoftDeleteCompanyAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteCompanyAttachment, arg.SupplierAttachmentID, arg.SupplierID)
	return err
}

const softDeletePartAttachment = `-- name: SoftDeletePartAttachment :exec
UPDATE part_attachment SET is_active = FALSE WHERE id = $1 AND part_id = $2
`

type SoftDeletePartAttachmentParams struct {
	ID     int
	PartID int
}

func (q *Queries) SoftDeletePartAttachment(ctx context.Context, arg SoftDeletePartAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, softDeletePartAttachment, arg.ID, arg.PartID)
	return err
}

const supplierPartOfPart = `-- name: SupplierPartOfPart :one
SELECT EXISTS (SELECT 1 FROM supplier_part WHERE id = $1 AND part_id = $2)
`

type SupplierPartOfPartParams struct {
	ID     int
	PartID int
}

func (q *Queries) SupplierPartOfPart(ctx context.Context, arg SupplierPartOfPartParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, supplierPartOfPart, arg.ID, arg.PartID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateCompanyAttachment = `-- name: UpdateCompanyAttachment :exec
UPDATE company_attachment SET notes = $1::text, sort_order = $2
WHERE supplier_attachment_id = $3 AND supplier_id = $4
`

type UpdateCompanyAttachmentParams struct {
	Notes      string
	SortOrder  *int
	ID         int
	SupplierID int
}

func (q *Queries) UpdateCompanyAttachment(ctx context.Context, arg UpdateCompanyAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, updateCompanyAttachment,
		arg.Notes,
		arg.SortOrder,
		arg.ID,
		arg.SupplierID,
	)
	return err
}

const updateCompanyAttachmentFile = `-- name: UpdateCompanyAttachmentFile :exec
UPDATE company_attachment SET notes = $1::text, sort_order = $2,
  file_path = $3, hash = $4::text
WHERE supplier_attachment_id = $5 AND supplier_id = $6
`

type UpdateCompanyAttachmentFileParams struct {
	Notes      string
	SortOrder  *int
	FilePath   string
	Hash       string
	ID         int
	SupplierID int
}

func (q *Queries) UpdateCompanyAttachmentFile(ctx context.Context, arg UpdateCompanyAttachmentFileParams) error {
	_, err := q.db.ExecContext(ctx, updateCompanyAttachmentFile,
		arg.Notes,
		arg.SortOrder,
		arg.FilePath,
		arg.Hash,
		arg.ID,
		arg.SupplierID,
	)
	return err
}

const updateGeneratedAttachment = `-- name: UpdateGeneratedAttachment :exec
UPDATE part_attachment SET file_name = $1::text, part_revision = $2::text,
  hash = $3::text
WHERE id = $4
`

type UpdateGeneratedAttachmentParams struct {
	FileName     string
	PartRevision string
	Hash         string
	ID           int
}

func (q *Queries) UpdateGeneratedAttachment(ctx context.Context, arg UpdateGeneratedAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, updateGeneratedAttachment,
		arg.FileName,
		arg.PartRevision,
		arg.Hash,
		arg.ID,
	)
	return err
}

const updatePartAttachment = `-- name: UpdatePartAttachment :exec
UPDATE part_attachment SET part_revision = $1::text, category = $2::text,
  sort_order = $3, comment = $4::text,
  supplier_part_id = $5, mfg_part_id = $6
WHERE id = $7
`

type UpdatePartAttachmentParams struct {
	PartRevision   string
	Category       string
	SortOrder      *int
	Comment        string
	SupplierPartID *int
	MfgPartID      *int
	ID             int
}

func (q *Queries) UpdatePartAttachment(ctx context.Context, arg UpdatePartAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, updatePartAttachment,
		arg.PartRevision,
		arg.Category,
		arg.SortOrder,
		arg.Comment,
		arg.SupplierPartID,
		arg.MfgPartID,
		arg.ID,
	)
	return err
}

const updatePartAttachmentFile = `-- name: UpdatePartAttachmentFile :exec
UPDATE part_attachment SET part_revision = $1::text, category = $2::text,
  sort_order = $3, comment = $4::text,
  supplier_part_id = $5, mfg_part_id = $6,
  file_name = $7::text, hash = $8::text
WHERE id = $9
`

type UpdatePartAttachmentFileParams struct {
	PartRevision   string
	Category       string
	SortOrder      *int
	Comment        string
	SupplierPartID *int
	MfgPartID      *int
	FileName       string
	Hash           string
	ID             int
}

func (q *Queries) UpdatePartAttachmentFile(ctx context.Context, arg UpdatePartAttachmentFileParams) error {
	_, err := q.db.ExecContext(ctx, updatePartAttachmentFile,
		arg.PartRevision,
		arg.Category,
		arg.SortOrder,
		arg.Comment,
		arg.SupplierPartID,
		arg.MfgPartID,
		arg.FileName,
		arg.Hash,
		arg.ID,
	)
	return err
}

const whereUsed = `-- name: WhereUsed :many

SELECT 'part'::text AS kind, p.id AS owner_id, COALESCE(p.part_number, '') AS code,
       COALESCE(p.description, '') AS label
FROM part_attachment fa JOIN part p ON p.id = fa.part_id
WHERE fa.is_active = TRUE AND fa.file_name = $1::text
UNION ALL
SELECT 'supplier'::text, c.id, '', COALESCE(c.name, '')
FROM company_attachment ca JOIN company c ON c.id = ca.supplier_id
WHERE ca.is_active = TRUE AND ca.file_path = $1::text
ORDER BY 1, 4
`

type WhereUsedRow struct {
	Kind    string
	OwnerID int
	Code    string
	Label   string
}

// ── both ─────────────────────────────────────────────────────────────────────
// WhereUsed lists every part and supplier with an active attachment of exactly this link.
func (q *Queries) WhereUsed(ctx context.Context, file string) ([]WhereUsedRow, error) {
	rows, err := q.db.QueryContext(ctx, whereUsed, file)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WhereUsedRow
	for rows.Next() {
		var i WhereUsedRow
		if err := rows.Scan(
			&i.Kind,
			&i.OwnerID,
			&i.Code,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
