// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbq

import (
	"context"
)

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*)::int FROM users WHERE is_active = TRUE
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int, error) {
	row := q.db.QueryRowContext(ctx, countActiveUsers)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (username, display_name, password_hash, is_admin)
VALUES ($1, $2, $3, $4::bool)
`

type CreateUserParams struct {
	Username     string
	DisplayName  string
	PasswordHash string
	IsAdmin      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	return err
}

const getActiveUserByID = `-- name: GetActiveUserByID :one

SELECT id, username, display_name, can_approve_po, can_approve_records, is_admin,
       default_po_contact_id, default_po_receiver_id,
       COALESCE(accent_color, '') AS accent_color, COALESCE(default_route, '') AS default_route, timezone
FROM users WHERE id = $1::int AND is_active = TRUE
`

type GetActiveUserByIDRow struct {
	ID                  int
	Username            string
	DisplayName         string
	CanApprovePo        bool
	CanApproveRecords   bool
	IsAdmin             bool
	DefaultPoContactID  *int
	DefaultPoReceiverID *int
	AccentColor         string
	DefaultRoute        string
	Timezone            string
}

// users: accounts, admin toggles and per-user preferences (#190, #251, #247). Sessions and CSRF live
// in the signed cookie, not the DB, so this is the whole auth data layer. Password hashing stays in
// the handler; these queries only store and return hashes.
func (q *Queries) GetActiveUserByID(ctx context.Context, id int) (GetActiveUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserByID, id)
	var i GetActiveUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.CanApprovePo,
		&i.CanApproveRecords,
		&i.IsAdmin,
		&i.DefaultPoContactID,
		&i.DefaultPoReceiverID,
		&i.AccentColor,
		&i.DefaultRoute,
		&i.Timezone,
	)
	return i, err
}

const getActiveUserByUsername = `-- name: GetActiveUserByUsername :one
SELECT id, username, display_name, password_hash, COALESCE(default_route, '') AS default_route
FROM users WHERE username = $1::text AND is_active = TRUE
`

type GetActiveUserByUsernameRow struct {
	ID           int
	Username     string
	DisplayName  string
	PasswordHash string
	DefaultRoute string
}

func (q *Queries) GetActiveUserByUsername(ctx context.Context, username string) (GetActiveUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserByUsername, username)
	var i GetActiveUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.DefaultRoute,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, is_active, can_approve_po, can_approve_records, is_admin
FROM users ORDER BY username
`

type ListUsersRow struct {
	ID                int
	Username          string
	DisplayName       string
	IsActive          bool
	CanApprovePo      bool
	CanApproveRecords bool
	IsAdmin           bool
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.IsActive,
			&i.CanApprovePo,
			&i.CanApproveRecords,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAccentColor = `-- name: SetUserAccentColor :exec

UPDATE users SET accent_color = $1::text WHERE id = $2::int
`

type SetUserAccentColorParams struct {
	AccentColor string
	ID          int
}

// The per-user preference updates below deliberately leave updated_at alone (as before the conversion).
func (q *Queries) SetUserAccentColor(ctx context.Context, arg SetUserAccentColorParams) error {
	_, err := q.db.ExecContext(ctx, setUserAccentColor, arg.AccentColor, arg.ID)
	return err
}

const setUserDefaultRoute = `-- name: SetUserDefaultRoute :exec
UPDATE users SET default_route = $1::text WHERE id = $2::int
`

type SetUserDefaultRouteParams struct {
	DefaultRoute string
	ID           int
}

func (q *Queries) SetUserDefaultRoute(ctx context.Context, arg SetUserDefaultRouteParams) error {
	_, err := q.db.ExecContext(ctx, setUserDefaultRoute, arg.DefaultRoute, arg.ID)
	return err
}

const setUserPODefaults = `-- name: SetUserPODefaults :exec
UPDATE users SET default_po_contact_id = $1::int, default_po_receiver_id = $2::int
WHERE id = $3::int
`

type SetUserPODefaultsParams struct {
	ContactID  *int
	ReceiverID *int
	ID         int
}

func (q *Queries) SetUserPODefaults(ctx context.Context, arg SetUserPODefaultsParams) error {
	_, err := q.db.ExecContext(ctx, setUserPODefaults, arg.ContactID, arg.ReceiverID, arg.ID)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2::int
`

type SetUserPasswordParams struct {
	PasswordHash string
	ID           int
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const setUserTimezone = `-- name: SetUserTimezone :exec
UPDATE users SET timezone = $1::text WHERE id = $2::int
`

type SetUserTimezoneParams struct {
	Timezone string
	ID       int
}

func (q *Queries) SetUserTimezone(ctx context.Context, arg SetUserTimezoneParams) error {
	_, err := q.db.ExecContext(ctx, setUserTimezone, arg.Timezone, arg.ID)
	return err
}

const toggleUserActive = `-- name: ToggleUserActive :exec
UPDATE users SET is_active = NOT is_active, updated_at = CURRENT_TIMESTAMP WHERE id = $1::int
`

func (q *Queries) ToggleUserActive(ctx context.Context, id int) error {
	_, err := q.db.ExecContext(ctx, toggleUserActive, id)
	return err
}

const toggleUserAdmin = `-- name: ToggleUserAdmin :exec
UPDATE users SET is_admin = NOT is_admin, updated_at = CURRENT_TIMESTAMP WHERE id = $1::int
`

func (q *Queries) ToggleUserAdmin(ctx context.Context, id int) error {
	_, err := q.db.ExecContext(ctx, toggleUserAdmin, id)
	return err
}

const toggleUserApprovePO = `-- name: ToggleUserApprovePO :exec
UPDATE users SET can_approve_po = NOT can_approve_po, updated_at = CURRENT_TIMESTAMP WHERE id = $1::int
`

func (q *Queries) ToggleUserApprovePO(ctx context.Context, id int) error {
	_, err := q.db.ExecContext(ctx, toggleUserApprovePO, id)
	return err
}

const toggleUserApproveRecords = `-- name: ToggleUserApproveRecords :exec
UPDATE users SET can_approve_records = NOT can_approve_records, updated_at = CURRENT_TIMESTAMP WHERE id = $1::int
`

func (q *Queries) ToggleUserApproveRecords(ctx context.Context, id int) error {
	_, err := q.db.ExecContext(ctx, toggleUserApproveRecords, id)
	return err
}
