// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package dbq

import (
	"context"
	"time"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contact (display_name, company_id, email, phone_1, phone_2, fax,
                     address, city, state, zipcode, country,
                     website, is_active, notes)
VALUES ($1, $2,
        $3::text, $4::text, $5::text, $6::text,
        $7::text, $8::text, $9::text,
        $10::text, $11::text,
        $12::text, $13::boolean, $14::text)
RETURNING id
`

type CreateContactParams struct {
	DisplayName string
	CompanyID   *int
	Email       string
	Phone1      string
	Phone2      string
	Fax         string
	Address     string
	City        string
	State       string
	Zipcode     string
	Country     string
	Website     string
	IsActive    bool
	Notes       string
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createContact,
		arg.DisplayName,
		arg.CompanyID,
		arg.Email,
		arg.Phone1,
		arg.Phone2,
		arg.Fax,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zipcode,
		arg.Country,
		arg.Website,
		arg.IsActive,
		arg.Notes,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const getContact = `-- name: GetContact :one
SELECT cn.id, cn.company_id, cn.display_name,
       COALESCE(cn.email, '') AS email,
       COALESCE(cn.phone_1, '') AS phone_1, COALESCE(cn.phone_2, '') AS phone_2,
       COALESCE(cn.fax, '') AS fax,
       COALESCE(cn.address, '') AS address, COALESCE(cn.city, '') AS city,
       COALESCE(cn.state, '') AS state, COALESCE(cn.zipcode, '') AS zipcode,
       COALESCE(cn.country, '') AS country,
       COALESCE(cn.website, '') AS website, COALESCE(cn.is_active, FALSE) AS is_active,
       COALESCE(cn.notes, '') AS notes, cn.updated_at,
       COALESCE(su.name, '') AS supplier_name
FROM contact cn
LEFT JOIN company su ON cn.company_id = su.id
WHERE cn.id = $1
`

type GetContactRow struct {
	ID           int
	CompanyID    *int
	DisplayName  string
	Email        string
	Phone1       string
	Phone2       string
	Fax          string
	Address      string
	City         string
	State        string
	Zipcode      string
	Country      string
	Website      string
	IsActive     bool
	Notes        string
	UpdatedAt    *time.Time
	SupplierName string
}

func (q *Queries) GetContact(ctx context.Context, id int) (GetContactRow, error) {
	row := q.db.QueryRowContext(ctx, getContact, id)
	var i GetContactRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DisplayName,
		&i.Email,
		&i.Phone1,
		&i.Phone2,
		&i.Fax,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zipcode,
		&i.Country,
		&i.Website,
		&i.IsActive,
		&i.Notes,
		&i.UpdatedAt,
		&i.SupplierName,
	)
	return i, err
}

const listContactPOs = `-- name: ListContactPOs :many
SELECT number,
       CASE WHEN supplier_contact_id = $1::int THEN 'Supplier' ELSE 'Receiver' END AS role,
       COALESCE(supplier_name, '') AS supplier_name, COALESCE(status, '') AS status, date_ordered,
       COALESCE(total_cost, 0)::float8 AS total_cost
FROM purchase_order
WHERE supplier_contact_id = $1::int OR receiver_contact_id = $1::int
ORDER BY date_ordered DESC, id DESC
`

type ListContactPOsRow struct {
	Number       string
	Role         string
	SupplierName string
	Status       string
	DateOrdered  *time.Time
	TotalCost    float64
}

func (q *Queries) ListContactPOs(ctx context.Context, contactID int) ([]ListContactPOsRow, error) {
	rows, err := q.db.QueryContext(ctx, listContactPOs, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactPOsRow
	for rows.Next() {
		var i ListContactPOsRow
		if err := rows.Scan(
			&i.Number,
			&i.Role,
			&i.SupplierName,
			&i.Status,
			&i.DateOrdered,
			&i.TotalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContacts = `-- name: ListContacts :many
SELECT cn.id, cn.company_id, cn.display_name,
       COALESCE(cn.email, '') AS email, COALESCE(cn.phone_1, '') AS phone_1,
       COALESCE(cn.city, '') AS city, COALESCE(cn.state, '') AS state,
       COALESCE(cn.country, '') AS country, COALESCE(cn.website, '') AS website,
       COALESCE(cn.is_active, FALSE) AS is_active, COALESCE(cn.notes, '') AS notes,
       cn.updated_at, COALESCE(su.name, '') AS supplier_name
FROM contact cn
LEFT JOIN company su ON cn.company_id = su.id
ORDER BY su.name, cn.display_name ASC
`

type ListContactsRow struct {
	ID           int
	CompanyID    *int
	DisplayName  string
	Email        string
	Phone1       string
	City         string
	State        string
	Country      string
	Website      string
	IsActive     bool
	Notes        string
	UpdatedAt    *time.Time
	SupplierName string
}

func (q *Queries) ListContacts(ctx context.Context) ([]ListContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listContacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactsRow
	for rows.Next() {
		var i ListContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DisplayName,
			&i.Email,
			&i.Phone1,
			&i.City,
			&i.State,
			&i.Country,
			&i.Website,
			&i.IsActive,
			&i.Notes,
			&i.UpdatedAt,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiblingContacts = `-- name: ListSiblingContacts :many
SELECT id, display_name FROM contact
WHERE company_id = $1::int AND id <> $2::int AND is_active = TRUE
ORDER BY display_name
`

type ListSiblingContactsParams struct {
	CompanyID int
	ExcludeID int
}

type ListSiblingContactsRow struct {
	ID          int
	DisplayName string
}

func (q *Queries) ListSiblingContacts(ctx context.Context, arg ListSiblingContactsParams) ([]ListSiblingContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSiblingContacts, arg.CompanyID, arg.ExcludeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSiblingContactsRow
	for rows.Next() {
		var i ListSiblingContactsRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :exec
UPDATE contact SET
  display_name = $1, company_id = $2,
  email = $3::text, phone_1 = $4::text,
  phone_2 = $5::text, fax = $6::text,
  address = $7::text, city = $8::text, state = $9::text,
  zipcode = $10::text, country = $11::text,
  website = $12::text, is_active = $13::boolean,
  notes = $14::text, updated_at = CURRENT_TIMESTAMP
WHERE id = $15
`

type UpdateContactParams struct {
	DisplayName string
	CompanyID   *int
	Email       string
	Phone1      string
	Phone2      string
	Fax         string
	Address     string
	City        string
	State       string
	Zipcode     string
	Country     string
	Website     string
	IsActive    bool
	Notes       string
	ID          int
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) error {
	_, err := q.db.ExecContext(ctx, updateContact,
		arg.DisplayName,
		arg.CompanyID,
		arg.Email,
		arg.Phone1,
		arg.Phone2,
		arg.Fax,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zipcode,
		arg.Country,
		arg.Website,
		arg.IsActive,
		arg.Notes,
		arg.ID,
	)
	return err
}
