// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package dbq

import (
	"context"
	"database/sql"
	"time"

	"github.com/shopspring/decimal"
)

const addPartStock = `-- name: AddPartStock :exec
UPDATE part SET stock_on_hand = stock_on_hand + $1 WHERE id = $2
`

type AddPartStockParams struct {
	Qty decimal.Decimal
	ID  int
}

// The part's cached on-hand, moved by the same signed qty as its ledger row.
func (q *Queries) AddPartStock(ctx context.Context, arg AddPartStockParams) error {
	_, err := q.db.ExecContext(ctx, addPartStock, arg.Qty, arg.ID)
	return err
}

const appendLotNote = `-- name: AppendLotNote :exec
UPDATE lot SET notes = CASE WHEN COALESCE(notes, '') = '' THEN $1::text
                            ELSE CONCAT(notes, $2::text) END
WHERE id = $3
`

type AppendLotNoteParams struct {
	Entry          string
	SeparatedEntry string
	ID             int
}

// entry starts the notes when empty; otherwise separated_entry (blank line + entry) is appended.
// Both are ::text — an untyped CONCAT argument is rejected by Postgres.
func (q *Queries) AppendLotNote(ctx context.Context, arg AppendLotNoteParams) error {
	_, err := q.db.ExecContext(ctx, appendLotNote, arg.Entry, arg.SeparatedEntry, arg.ID)
	return err
}

const countActivePartLot = `-- name: CountActivePartLot :one
SELECT COUNT(*) FROM lot WHERE id = $1 AND part_id = $2 AND is_active = TRUE
`

type CountActivePartLotParams struct {
	ID     int
	PartID int
}

// Whether the lot is an active lot of the part (the build/adjustment forged-selection guard).
func (q *Queries) CountActivePartLot(ctx context.Context, arg CountActivePartLotParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivePartLot, arg.ID, arg.PartID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLockedUnitRecords = `-- name: CountLockedUnitRecords :one
SELECT COUNT(*) FROM form_record WHERE unit_id = $1 AND is_locked = TRUE
`

// A unit's serial is frozen once any locked form_record points at it.
func (q *Queries) CountLockedUnitRecords(ctx context.Context, unitID *int) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLockedUnitRecords, unitID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPartBuild = `-- name: CountPartBuild :one
SELECT COUNT(*) FROM build WHERE id = $1 AND part_id = $2
`

type CountPartBuildParams struct {
	ID     int
	PartID int
}

func (q *Queries) CountPartBuild(ctx context.Context, arg CountPartBuildParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPartBuild, arg.ID, arg.PartID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPartLot = `-- name: CountPartLot :one
SELECT COUNT(*) FROM lot WHERE id = $1 AND part_id = $2
`

type CountPartLotParams struct {
	ID     int
	PartID int
}

// Ownership only: a test record may reference a since-retired lot.
func (q *Queries) CountPartLot(ctx context.Context, arg CountPartLotParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPartLot, arg.ID, arg.PartID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPartLots = `-- name: CountPartLots :one
SELECT COUNT(*) FROM lot WHERE part_id = $1
`

func (q *Queries) CountPartLots(ctx context.Context, partID int) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPartLots, partID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPartUnits = `-- name: CountPartUnits :one
SELECT COUNT(*) FROM unit WHERE part_id = $1
`

func (q *Queries) CountPartUnits(ctx context.Context, partID int) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPartUnits, partID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBuild = `-- name: CreateBuild :one
INSERT INTO build (part_id, qty, build_date, username, note)
VALUES ($1, $2, $3, $4, $5::text)
RETURNING id
`

type CreateBuildParams struct {
	PartID    int
	Qty       decimal.Decimal
	BuildDate time.Time
	Username  string
	Note      sql.NullString
}

func (q *Queries) CreateBuild(ctx context.Context, arg CreateBuildParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createBuild,
		arg.PartID,
		arg.Qty,
		arg.BuildDate,
		arg.Username,
		arg.Note,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const createGenealogyEdge = `-- name: CreateGenealogyEdge :exec
INSERT INTO genealogy (parent_lot_id, child_lot_id, qty_consumed)
VALUES ($1, $2, $3)
`

type CreateGenealogyEdgeParams struct {
	ParentLotID *int
	ChildLotID  *int
	QtyConsumed decimal.Decimal
}

// Lot→lot edge; unit endpoints are written by the record/unit flows.
func (q *Queries) CreateGenealogyEdge(ctx context.Context, arg CreateGenealogyEdgeParams) error {
	_, err := q.db.ExecContext(ctx, createGenealogyEdge, arg.ParentLotID, arg.ChildLotID, arg.QtyConsumed)
	return err
}

const createInventoryTxn = `-- name: CreateInventoryTxn :exec


INSERT INTO inventory_transaction (part_id, txn_type, qty, txn_date, username, reference, note, po_line_id, lot_id, build_id)
VALUES ($1, $2, $3, $4, $5,
        $6::text, $7::text, $8, $9, $10)
`

type CreateInventoryTxnParams struct {
	PartID    int
	TxnType   string
	Qty       decimal.Decimal
	TxnDate   time.Time
	Username  string
	Reference sql.NullString
	Note      sql.NullString
	PoLineID  *int
	LotID     *int
	BuildID   *int
}

// Inventory domain (#190, #222): the stock ledger, lots, builds, units and genealogy. sqlc
// generates internal/dbq/inventory.sql.go from this file; the service is inventory.go.
// ── Ledger ─────────────────────────────────────────────────────────────────────
func (q *Queries) CreateInventoryTxn(ctx context.Context, arg CreateInventoryTxnParams) error {
	_, err := q.db.ExecContext(ctx, createInventoryTxn,
		arg.PartID,
		arg.TxnType,
		arg.Qty,
		arg.TxnDate,
		arg.Username,
		arg.Reference,
		arg.Note,
		arg.PoLineID,
		arg.LotID,
		arg.BuildID,
	)
	return err
}

const createLot = `-- name: CreateLot :one

INSERT INTO lot (part_id, lot_number, lot_description, vendor_lot_number, po_line_id, is_active)
VALUES ($1, $2, $3, $4::text,
        $5, TRUE)
RETURNING id
`

type CreateLotParams struct {
	PartID          int
	LotNumber       string
	LotDescription  string
	VendorLotNumber sql.NullString
	PoLineID        *int
}

// ── Lots ───────────────────────────────────────────────────────────────────────
// source stays NULL (unclassified), as before.
func (q *Queries) CreateLot(ctx context.Context, arg CreateLotParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createLot,
		arg.PartID,
		arg.LotNumber,
		arg.LotDescription,
		arg.VendorLotNumber,
		arg.PoLineID,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const createManualUnit = `-- name: CreateManualUnit :one
INSERT INTO unit (part_id, serial_number, lot_id, build_id, source)
VALUES ($1, $2, $3, $4, 'manual')
RETURNING id
`

type CreateManualUnitParams struct {
	PartID       int
	SerialNumber string
	LotID        *int
	BuildID      *int
}

func (q *Queries) CreateManualUnit(ctx context.Context, arg CreateManualUnitParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createManualUnit,
		arg.PartID,
		arg.SerialNumber,
		arg.LotID,
		arg.BuildID,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const getBuild = `-- name: GetBuild :one
SELECT id, qty, build_date FROM build WHERE id = $1
`

type GetBuildRow struct {
	ID        int
	Qty       decimal.Decimal
	BuildDate time.Time
}

func (q *Queries) GetBuild(ctx context.Context, id int) (GetBuildRow, error) {
	row := q.db.QueryRowContext(ctx, getBuild, id)
	var i GetBuildRow
	err := row.Scan(&i.ID, &i.Qty, &i.BuildDate)
	return i, err
}

const getLot = `-- name: GetLot :one
SELECT l.id, l.lot_number, COALESCE(l.vendor_lot_number, '') AS vendor_lot, l.part_id,
       COALESCE(p.part_number, '') AS part_number, COALESCE(p.description, '') AS part_description,
       l.lot_description, COALESCE(l.notes, '') AS notes, l.created_at, l.is_active
FROM lot l JOIN part p ON p.id = l.part_id
WHERE l.id = $1
`

type GetLotRow struct {
	ID              int
	LotNumber       string
	VendorLot       string
	PartID          int
	PartNumber      string
	PartDescription string
	LotDescription  string
	Notes           string
	CreatedAt       time.Time
	IsActive        bool
}

func (q *Queries) GetLot(ctx context.Context, id int) (GetLotRow, error) {
	row := q.db.QueryRowContext(ctx, getLot, id)
	var i GetLotRow
	err := row.Scan(
		&i.ID,
		&i.LotNumber,
		&i.VendorLot,
		&i.PartID,
		&i.PartNumber,
		&i.PartDescription,
		&i.LotDescription,
		&i.Notes,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const getUnit = `-- name: GetUnit :one
SELECT u.id, u.serial_number, u.part_id, COALESCE(p.part_number, '') AS part_number,
       COALESCE(p.description, '') AS part_description, u.lot_id, COALESCE(l.lot_number, '') AS lot_number,
       u.build_id, u.is_active, u.created_at, u.source
FROM unit u
JOIN part p ON p.id = u.part_id
LEFT JOIN lot l ON l.id = u.lot_id
WHERE u.id = $1
`

type GetUnitRow struct {
	ID              int
	SerialNumber    string
	PartID          int
	PartNumber      string
	PartDescription string
	LotID           *int
	LotNumber       string
	BuildID         *int
	IsActive        bool
	CreatedAt       time.Time
	Source          string
}

func (q *Queries) GetUnit(ctx context.Context, id int) (GetUnitRow, error) {
	row := q.db.QueryRowContext(ctx, getUnit, id)
	var i GetUnitRow
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.PartID,
		&i.PartNumber,
		&i.PartDescription,
		&i.LotID,
		&i.LotNumber,
		&i.BuildID,
		&i.IsActive,
		&i.CreatedAt,
		&i.Source,
	)
	return i, err
}

const getUnitProvenance = `-- name: GetUnitProvenance :one
SELECT lot_id, build_id FROM unit WHERE id = $1
`

type GetUnitProvenanceRow struct {
	LotID   *int
	BuildID *int
}

func (q *Queries) GetUnitProvenance(ctx context.Context, id int) (GetUnitProvenanceRow, error) {
	row := q.db.QueryRowContext(ctx, getUnitProvenance, id)
	var i GetUnitProvenanceRow
	err := row.Scan(&i.LotID, &i.BuildID)
	return i, err
}

const linkRecordToBuild = `-- name: LinkRecordToBuild :execrows
UPDATE form_record SET lot_id = $1, build_id = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3 AND part_id = $4 AND is_locked = FALSE
`

type LinkRecordToBuildParams struct {
	LotID   *int
	BuildID *int
	ID      int
	PartID  *int
}

// #191: one conditional write, so a lock landing mid-build is honored.
func (q *Queries) LinkRecordToBuild(ctx context.Context, arg LinkRecordToBuildParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, linkRecordToBuild,
		arg.LotID,
		arg.BuildID,
		arg.ID,
		arg.PartID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listActiveLots = `-- name: ListActiveLots :many
SELECT id, lot_number, COALESCE(vendor_lot_number, '') AS vendor_lot
FROM lot WHERE part_id = $1 AND is_active = TRUE
ORDER BY created_at DESC, id DESC
`

type ListActiveLotsRow struct {
	ID        int
	LotNumber string
	VendorLot string
}

func (q *Queries) ListActiveLots(ctx context.Context, partID int) ([]ListActiveLotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLots, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveLotsRow
	for rows.Next() {
		var i ListActiveLotsRow
		if err := rows.Scan(&i.ID, &i.LotNumber, &i.VendorLot); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildComponents = `-- name: ListBuildComponents :many
SELECT b.component_part_id, COALESCE(p.part_number, '') AS part_number, COALESCE(p.description, '') AS description,
       COALESCE(p.category, '') AS category, b.qty, p.stock_on_hand, p.tracking_mode
FROM bom b JOIN part p ON b.component_part_id = p.id
WHERE b.parent_part_id = $1
ORDER BY b.line_number
`

type ListBuildComponentsRow struct {
	ComponentPartID int
	PartNumber      string
	Description     string
	Category        string
	Qty             decimal.Decimal
	StockOnHand     decimal.Decimal
	TrackingMode    string
}

func (q *Queries) ListBuildComponents(ctx context.Context, parentPartID int) ([]ListBuildComponentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBuildComponents, parentPartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildComponentsRow
	for rows.Next() {
		var i ListBuildComponentsRow
		if err := rows.Scan(
			&i.ComponentPartID,
			&i.PartNumber,
			&i.Description,
			&i.Category,
			&i.Qty,
			&i.StockOnHand,
			&i.TrackingMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildHistory = `-- name: ListBuildHistory :many
SELECT b.id, b.qty, b.build_date, b.username, COALESCE(b.note, '') AS note,
       (SELECT COUNT(*) FROM unit u WHERE u.build_id = b.id AND u.source <> 'manual')::int AS tested_count
FROM build b WHERE b.part_id = $1 ORDER BY b.build_date DESC, b.id DESC
`

type ListBuildHistoryRow struct {
	ID          int
	Qty         decimal.Decimal
	BuildDate   time.Time
	Username    string
	Note        string
	TestedCount int
}

// tested_count: serialized units minted for the build; manual back-filled units (#799) were never tested.
func (q *Queries) ListBuildHistory(ctx context.Context, partID int) ([]ListBuildHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listBuildHistory, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildHistoryRow
	for rows.Next() {
		var i ListBuildHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Qty,
			&i.BuildDate,
			&i.Username,
			&i.Note,
			&i.TestedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildLines = `-- name: ListBuildLines :many
SELECT b.component_part_id, COALESCE(p.part_number, '') AS part_number, b.qty,
       COALESCE(p.category, '') AS category, p.tracking_mode
FROM bom b JOIN part p ON b.component_part_id = p.id
WHERE b.parent_part_id = $1
ORDER BY b.component_part_id, b.line_number
`

type ListBuildLinesRow struct {
	ComponentPartID int
	PartNumber      string
	Qty             decimal.Decimal
	Category        string
	TrackingMode    string
}

// Ascending component id: the build locks each component's part row in this order, so two builds that share
// components can't lock them in opposite orders and deadlock (#268).
func (q *Queries) ListBuildLines(ctx context.Context, parentPartID int) ([]ListBuildLinesRow, error) {
	rows, err := q.db.QueryContext(ctx, listBuildLines, parentPartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildLinesRow
	for rows.Next() {
		var i ListBuildLinesRow
		if err := rows.Scan(
			&i.ComponentPartID,
			&i.PartNumber,
			&i.Qty,
			&i.Category,
			&i.TrackingMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLots = `-- name: ListLots :many
SELECT l.id, l.lot_number, COALESCE(l.vendor_lot_number, '') AS vendor_lot, l.part_id,
       COALESCE(p.part_number, '') AS part_number, COALESCE(p.description, '') AS part_description,
       l.lot_description, COALESCE(l.notes, '') AS notes, l.created_at, l.is_active
FROM lot l JOIN part p ON p.id = l.part_id
WHERE ($1::int IS NULL OR l.part_id = $1::int)
ORDER BY l.created_at DESC, l.id DESC
LIMIT $2::int
`

type ListLotsParams struct {
	PartID *int
	N      *int
}

type ListLotsRow struct {
	ID              int
	LotNumber       string
	VendorLot       string
	PartID          int
	PartNumber      string
	PartDescription string
	LotDescription  string
	Notes           string
	CreatedAt       time.Time
	IsActive        bool
}

// Newest first. A NULL part_id lists every part's lots; a NULL n means no limit.
func (q *Queries) ListLots(ctx context.Context, arg ListLotsParams) ([]ListLotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLots, arg.PartID, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLotsRow
	for rows.Next() {
		var i ListLotsRow
		if err := rows.Scan(
			&i.ID,
			&i.LotNumber,
			&i.VendorLot,
			&i.PartID,
			&i.PartNumber,
			&i.PartDescription,
			&i.LotDescription,
			&i.Notes,
			&i.CreatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartBuilds = `-- name: ListPartBuilds :many

SELECT id, qty, build_date FROM build WHERE part_id = $1 ORDER BY build_date DESC, id DESC
`

type ListPartBuildsRow struct {
	ID        int
	Qty       decimal.Decimal
	BuildDate time.Time
}

// ── Builds ─────────────────────────────────────────────────────────────────────
func (q *Queries) ListPartBuilds(ctx context.Context, partID int) ([]ListPartBuildsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPartBuilds, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartBuildsRow
	for rows.Next() {
		var i ListPartBuildsRow
		if err := rows.Scan(&i.ID, &i.Qty, &i.BuildDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartLedger = `-- name: ListPartLedger :many
SELECT it.txn_type, it.qty, it.txn_date, it.username,
       COALESCE(it.reference, '') AS reference, COALESCE(it.note, '') AS note,
       COALESCE(l.id, 0)::int AS lot_id, COALESCE(l.lot_number, '') AS lot_number
FROM inventory_transaction it
LEFT JOIN lot l ON l.id = it.lot_id
WHERE it.part_id = $1 ORDER BY it.txn_date ASC, it.id ASC
`

type ListPartLedgerRow struct {
	TxnType   string
	Qty       decimal.Decimal
	TxnDate   time.Time
	Username  string
	Reference string
	Note      string
	LotID     int
	LotNumber string
}

// Oldest first; the caller accumulates the running balance.
func (q *Queries) ListPartLedger(ctx context.Context, partID int) ([]ListPartLedgerRow, error) {
	rows, err := q.db.QueryContext(ctx, listPartLedger, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartLedgerRow
	for rows.Next() {
		var i ListPartLedgerRow
		if err := rows.Scan(
			&i.TxnType,
			&i.Qty,
			&i.TxnDate,
			&i.Username,
			&i.Reference,
			&i.Note,
			&i.LotID,
			&i.LotNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartUnits = `-- name: ListPartUnits :many

SELECT u.id, u.serial_number, u.part_id, COALESCE(p.part_number, '') AS part_number,
       COALESCE(p.description, '') AS part_description, u.lot_id, COALESCE(l.lot_number, '') AS lot_number,
       u.build_id, u.is_active, u.created_at, u.source
FROM unit u
JOIN part p ON p.id = u.part_id
LEFT JOIN lot l ON l.id = u.lot_id
WHERE u.part_id = $1 ORDER BY u.created_at DESC, u.id DESC
`

type ListPartUnitsRow struct {
	ID              int
	SerialNumber    string
	PartID          int
	PartNumber      string
	PartDescription string
	LotID           *int
	LotNumber       string
	BuildID         *int
	IsActive        bool
	CreatedAt       time.Time
	Source          string
}

// ── Units ──────────────────────────────────────────────────────────────────────
func (q *Queries) ListPartUnits(ctx context.Context, partID int) ([]ListPartUnitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPartUnits, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartUnitsRow
	for rows.Next() {
		var i ListPartUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumber,
			&i.PartID,
			&i.PartNumber,
			&i.PartDescription,
			&i.LotID,
			&i.LotNumber,
			&i.BuildID,
			&i.IsActive,
			&i.CreatedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPartUnits = `-- name: ListRecentPartUnits :many
SELECT u.id, u.serial_number, u.part_id, COALESCE(p.part_number, '') AS part_number,
       COALESCE(p.description, '') AS part_description, u.lot_id, COALESCE(l.lot_number, '') AS lot_number,
       u.build_id, u.is_active, u.created_at, u.source
FROM unit u
JOIN part p ON p.id = u.part_id
LEFT JOIN lot l ON l.id = u.lot_id
WHERE u.part_id = $1 ORDER BY u.created_at DESC, u.id DESC LIMIT $2::int
`

type ListRecentPartUnitsParams struct {
	PartID int
	N      int
}

type ListRecentPartUnitsRow struct {
	ID              int
	SerialNumber    string
	PartID          int
	PartNumber      string
	PartDescription string
	LotID           *int
	LotNumber       string
	BuildID         *int
	IsActive        bool
	CreatedAt       time.Time
	Source          string
}

func (q *Queries) ListRecentPartUnits(ctx context.Context, arg ListRecentPartUnitsParams) ([]ListRecentPartUnitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPartUnits, arg.PartID, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentPartUnitsRow
	for rows.Next() {
		var i ListRecentPartUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumber,
			&i.PartID,
			&i.PartNumber,
			&i.PartDescription,
			&i.LotID,
			&i.LotNumber,
			&i.BuildID,
			&i.IsActive,
			&i.CreatedAt,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTraceAncestors = `-- name: ListTraceAncestors :many

SELECT 'lot'::text AS node_type, l.id, l.lot_number AS number, COALESCE(l.vendor_lot_number, '') AS vendor_lot,
       COALESCE(l.notes, '') AS notes, (l.po_line_id IS NOT NULL)::boolean AS is_vendor_lot,
       p.id AS part_id, COALESCE(p.part_number, '') AS part_number, COALESCE(p.description, '') AS part_description,
       g.qty_consumed AS qty
FROM genealogy g
JOIN lot l ON l.id = g.parent_lot_id
JOIN part p ON p.id = l.part_id
WHERE g.child_lot_id = CASE WHEN $1::text = 'lot' THEN $2::int END
   OR g.child_unit_id = CASE WHEN $1::text = 'unit' THEN $2::int END
UNION ALL
SELECT 'unit'::text, u.id, u.serial_number, ''::text, ''::text, FALSE,
       p.id, COALESCE(p.part_number, ''), COALESCE(p.description, ''), g.qty_consumed
FROM genealogy g
JOIN unit u ON u.id = g.parent_unit_id
JOIN part p ON p.id = u.part_id
WHERE g.child_lot_id = CASE WHEN $1::text = 'lot' THEN $2::int END
   OR g.child_unit_id = CASE WHEN $1::text = 'unit' THEN $2::int END
ORDER BY 1, 2
`

type ListTraceAncestorsParams struct {
	NearType string
	ID       int
}

type ListTraceAncestorsRow struct {
	NodeType        string
	ID              int
	Number          string
	VendorLot       string
	Notes           string
	IsVendorLot     bool
	PartID          int
	PartNumber      string
	PartDescription string
	Qty             decimal.Decimal
}

// ── Genealogy trace ────────────────────────────────────────────────────────────
// One level of the walk. near_type ('lot'|'unit') and id name the near endpoint; the CASE arms
// keep each edge column's equality index-usable (= NULL never matches the other one). The far
// endpoint is a lot in the first branch and a unit in the second.
func (q *Queries) ListTraceAncestors(ctx context.Context, arg ListTraceAncestorsParams) ([]ListTraceAncestorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTraceAncestors, arg.NearType, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTraceAncestorsRow
	for rows.Next() {
		var i ListTraceAncestorsRow
		if err := rows.Scan(
			&i.NodeType,
			&i.ID,
			&i.Number,
			&i.VendorLot,
			&i.Notes,
			&i.IsVendorLot,
			&i.PartID,
			&i.PartNumber,
			&i.PartDescription,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTraceDescendants = `-- name: ListTraceDescendants :many
SELECT 'lot'::text AS node_type, l.id, l.lot_number AS number, COALESCE(l.vendor_lot_number, '') AS vendor_lot,
       COALESCE(l.notes, '') AS notes, (l.po_line_id IS NOT NULL)::boolean AS is_vendor_lot,
       p.id AS part_id, COALESCE(p.part_number, '') AS part_number, COALESCE(p.description, '') AS part_description,
       g.qty_consumed AS qty
FROM genealogy g
JOIN lot l ON l.id = g.child_lot_id
JOIN part p ON p.id = l.part_id
WHERE g.parent_lot_id = CASE WHEN $1::text = 'lot' THEN $2::int END
   OR g.parent_unit_id = CASE WHEN $1::text = 'unit' THEN $2::int END
UNION ALL
SELECT 'unit'::text, u.id, u.serial_number, ''::text, ''::text, FALSE,
       p.id, COALESCE(p.part_number, ''), COALESCE(p.description, ''), g.qty_consumed
FROM genealogy g
JOIN unit u ON u.id = g.child_unit_id
JOIN part p ON p.id = u.part_id
WHERE g.parent_lot_id = CASE WHEN $1::text = 'lot' THEN $2::int END
   OR g.parent_unit_id = CASE WHEN $1::text = 'unit' THEN $2::int END
ORDER BY 1, 2
`

type ListTraceDescendantsParams struct {
	NearType string
	ID       int
}

type ListTraceDescendantsRow struct {
	NodeType        string
	ID              int
	Number          string
	VendorLot       string
	Notes           string
	IsVendorLot     bool
	PartID          int
	PartNumber      string
	PartDescription string
	Qty             decimal.Decimal
}

func (q *Queries) ListTraceDescendants(ctx context.Context, arg ListTraceDescendantsParams) ([]ListTraceDescendantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTraceDescendants, arg.NearType, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTraceDescendantsRow
	for rows.Next() {
		var i ListTraceDescendantsRow
		if err := rows.Scan(
			&i.NodeType,
			&i.ID,
			&i.Number,
			&i.VendorLot,
			&i.Notes,
			&i.IsVendorLot,
			&i.PartID,
			&i.PartNumber,
			&i.PartDescription,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRecord = `-- name: LockRecord :one
SELECT id FROM form_record WHERE id = $1 FOR UPDATE
`

// #191: row lock on the test record a build was launched from, taken before any part row is locked.
func (q *Queries) LockRecord(ctx context.Context, id int) (int, error) {
	row := q.db.QueryRowContext(ctx, lockRecord, id)
	var id_2 int
	err := row.Scan(&id_2)
	return id_2, err
}

const setBuildOutputLot = `-- name: SetBuildOutputLot :exec
UPDATE build SET output_lot_id = $1 WHERE id = $2
`

type SetBuildOutputLotParams struct {
	OutputLotID *int
	ID          int
}

func (q *Queries) SetBuildOutputLot(ctx context.Context, arg SetBuildOutputLotParams) error {
	_, err := q.db.ExecContext(ctx, setBuildOutputLot, arg.OutputLotID, arg.ID)
	return err
}

const setLotNumber = `-- name: SetLotNumber :exec
UPDATE lot SET lot_number = $1 WHERE id = $2
`

type SetLotNumberParams struct {
	LotNumber string
	ID        int
}

func (q *Queries) SetLotNumber(ctx context.Context, arg SetLotNumberParams) error {
	_, err := q.db.ExecContext(ctx, setLotNumber, arg.LotNumber, arg.ID)
	return err
}

const setUnitActive = `-- name: SetUnitActive :exec
UPDATE unit SET is_active = $1 WHERE id = $2 AND part_id = $3
`

type SetUnitActiveParams struct {
	IsActive bool
	ID       int
	PartID   int
}

func (q *Queries) SetUnitActive(ctx context.Context, arg SetUnitActiveParams) error {
	_, err := q.db.ExecContext(ctx, setUnitActive, arg.IsActive, arg.ID, arg.PartID)
	return err
}

const updateLot = `-- name: UpdateLot :exec
UPDATE lot SET lot_description = $1, vendor_lot_number = $2::text,
       notes = $3::text
WHERE id = $4 AND part_id = $5
`

type UpdateLotParams struct {
	LotDescription  string
	VendorLotNumber sql.NullString
	Notes           sql.NullString
	ID              int
	PartID          int
}

func (q *Queries) UpdateLot(ctx context.Context, arg UpdateLotParams) error {
	_, err := q.db.ExecContext(ctx, updateLot,
		arg.LotDescription,
		arg.VendorLotNumber,
		arg.Notes,
		arg.ID,
		arg.PartID,
	)
	return err
}

const updateUnit = `-- name: UpdateUnit :exec
UPDATE unit SET is_active = $1, serial_number = $2
WHERE id = $3 AND part_id = $4
`

type UpdateUnitParams struct {
	IsActive     bool
	SerialNumber string
	ID           int
	PartID       int
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) error {
	_, err := q.db.ExecContext(ctx, updateUnit,
		arg.IsActive,
		arg.SerialNumber,
		arg.ID,
		arg.PartID,
	)
	return err
}

const upsertTestUnit = `-- name: UpsertTestUnit :one
INSERT INTO unit (part_id, serial_number, build_id, lot_id, source)
VALUES ($1, $2, $3, $4, 'test')
ON CONFLICT (part_id, serial_number) DO UPDATE SET serial_number = EXCLUDED.serial_number
RETURNING id
`

type UpsertTestUnitParams struct {
	PartID       int
	SerialNumber string
	BuildID      *int
	LotID        *int
}

// The no-op DO UPDATE makes RETURNING yield the existing id; provenance is set only on insert.
func (q *Queries) UpsertTestUnit(ctx context.Context, arg UpsertTestUnitParams) (int, error) {
	row := q.db.QueryRowContext(ctx, upsertTestUnit,
		arg.PartID,
		arg.SerialNumber,
		arg.BuildID,
		arg.LotID,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}
