// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parts.sql

package dbq

import (
	"context"
	"database/sql"
	"time"
)

const countPartsByCategory = `-- name: CountPartsByCategory :many
SELECT COALESCE(category, '') AS category, COUNT(*) AS part_count
FROM part
WHERE category IS NOT NULL
GROUP BY category
`

type CountPartsByCategoryRow struct {
	Category  string
	PartCount int64
}

func (q *Queries) CountPartsByCategory(ctx context.Context) ([]CountPartsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, countPartsByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountPartsByCategoryRow
	for rows.Next() {
		var i CountPartsByCategoryRow
		if err := rows.Scan(&i.Category, &i.PartCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createImportedAttachment = `-- name: CreateImportedAttachment :exec
INSERT INTO part_attachment (part_id, file_name, part_revision, category, comment, hash)
VALUES ($1, $2::text, '', $3::text, $4::text, $5::text)
`

type CreateImportedAttachmentParams struct {
	PartID   int
	FileName string
	Category string
	Comment  string
	Hash     string
}

func (q *Queries) CreateImportedAttachment(ctx context.Context, arg CreateImportedAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createImportedAttachment,
		arg.PartID,
		arg.FileName,
		arg.Category,
		arg.Comment,
		arg.Hash,
	)
	return err
}

const createManufacturer = `-- name: CreateManufacturer :one
INSERT INTO company (name, is_supplier, is_manufacturer) VALUES ($1, FALSE, TRUE)
ON CONFLICT (name) DO NOTHING
RETURNING id
`

// CreateManufacturer returns no row when a company already has the name.
func (q *Queries) CreateManufacturer(ctx context.Context, name string) (int, error) {
	row := q.db.QueryRowContext(ctx, createManufacturer, name)
	var id int
	err := row.Scan(&id)
	return id, err
}

const createMfgPart = `-- name: CreateMfgPart :exec
INSERT INTO mfg_part (part_id, mfg_id, mfg_part_number, description, is_active)
VALUES ($1, $2, $3, $4::text, TRUE)
`

type CreateMfgPartParams struct {
	PartID        int
	MfgID         int
	MfgPartNumber string
	Description   string
}

func (q *Queries) CreateMfgPart(ctx context.Context, arg CreateMfgPartParams) error {
	_, err := q.db.ExecContext(ctx, createMfgPart,
		arg.PartID,
		arg.MfgID,
		arg.MfgPartNumber,
		arg.Description,
	)
	return err
}

const createPart = `-- name: CreatePart :one
INSERT INTO part (part_number, revision, description, detail, category,
                  release_status, is_active, requested_by, notes, created_date, modified_date,
                  uom_id, current_cost, reorder_min,
                  user_field_1, user_field_2, user_field_3, user_field_4, user_field_5,
                  user_field_6, user_field_7, user_field_8, user_field_9, user_field_10, tracking_mode)
VALUES ($1, $2::text, $3::text, $4::text,
        NULLIF($5::text, ''), $6, $7::boolean,
        $8::text, $9::text, $10::date, $10::date,
        $11, $12::numeric, $13,
        $14::text, $15::text, $16::text,
        $17::text, $18::text, $19::text,
        $20::text, $21::text, $22::text,
        $23::text, $24)
RETURNING id
`

type CreatePartParams struct {
	PartNumber    string
	Revision      string
	Description   string
	Detail        string
	Category      string
	ReleaseStatus string
	IsActive      bool
	RequestedBy   string
	Notes         string
	Now           time.Time
	UomID         *int
	CurrentCost   float64
	ReorderMin    *float64
	UserField1    string
	UserField2    string
	UserField3    string
	UserField4    string
	UserField5    string
	UserField6    string
	UserField7    string
	UserField8    string
	UserField9    string
	UserField10   string
	TrackingMode  string
}

// A blank category is stored as NULL (uncategorized).
func (q *Queries) CreatePart(ctx context.Context, arg CreatePartParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createPart,
		arg.PartNumber,
		arg.Revision,
		arg.Description,
		arg.Detail,
		arg.Category,
		arg.ReleaseStatus,
		arg.IsActive,
		arg.RequestedBy,
		arg.Notes,
		arg.Now,
		arg.UomID,
		arg.CurrentCost,
		arg.ReorderMin,
		arg.UserField1,
		arg.UserField2,
		arg.UserField3,
		arg.UserField4,
		arg.UserField5,
		arg.UserField6,
		arg.UserField7,
		arg.UserField8,
		arg.UserField9,
		arg.UserField10,
		arg.TrackingMode,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const createSupplierPart = `-- name: CreateSupplierPart :exec
INSERT INTO supplier_part (supplier_id, part_id, preference, supplier_pn, supplier_desc, lead_time, min_increment, uom_id)
VALUES ($1, $2, $3, $4::text,
        $5::text, $6::text, $7, $8)
`

type CreateSupplierPartParams struct {
	SupplierID   int
	PartID       int
	Preference   *int
	SupplierPn   string
	SupplierDesc string
	LeadTime     string
	MinIncrement *float64
	UomID        *int
}

func (q *Queries) CreateSupplierPart(ctx context.Context, arg CreateSupplierPartParams) error {
	_, err := q.db.ExecContext(ctx, createSupplierPart,
		arg.SupplierID,
		arg.PartID,
		arg.Preference,
		arg.SupplierPn,
		arg.SupplierDesc,
		arg.LeadTime,
		arg.MinIncrement,
		arg.UomID,
	)
	return err
}

const deleteMfgPart = `-- name: DeleteMfgPart :exec
UPDATE mfg_part SET is_active = FALSE WHERE id = $1 AND part_id = $2
`

type DeleteMfgPartParams struct {
	ID     int
	PartID int
}

func (q *Queries) DeleteMfgPart(ctx context.Context, arg DeleteMfgPartParams) error {
	_, err := q.db.ExecContext(ctx, deleteMfgPart, arg.ID, arg.PartID)
	return err
}

const deletePartCategory = `-- name: DeletePartCategory :exec
DELETE FROM part_category WHERE code = $1
`

func (q *Queries) DeletePartCategory(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, deletePartCategory, code)
	return err
}

const deleteSupplierPart = `-- name: DeleteSupplierPart :exec
DELETE FROM supplier_part WHERE id = $1 AND part_id = $2
`

type DeleteSupplierPartParams struct {
	ID     int
	PartID int
}

func (q *Queries) DeleteSupplierPart(ctx context.Context, arg DeleteSupplierPartParams) error {
	_, err := q.db.ExecContext(ctx, deleteSupplierPart, arg.ID, arg.PartID)
	return err
}

const getMfgPart = `-- name: GetMfgPart :one
SELECT id, part_id, mfg_id, mfg_part_number, COALESCE(description, '') AS description
FROM mfg_part
WHERE id = $1 AND part_id = $2 AND is_active = TRUE
`

type GetMfgPartParams struct {
	ID     int
	PartID int
}

type GetMfgPartRow struct {
	ID            int
	PartID        int
	MfgID         int
	MfgPartNumber string
	Description   string
}

func (q *Queries) GetMfgPart(ctx context.Context, arg GetMfgPartParams) (GetMfgPartRow, error) {
	row := q.db.QueryRowContext(ctx, getMfgPart, arg.ID, arg.PartID)
	var i GetMfgPartRow
	err := row.Scan(
		&i.ID,
		&i.PartID,
		&i.MfgID,
		&i.MfgPartNumber,
		&i.Description,
	)
	return i, err
}

const getPart = `-- name: GetPart :one
SELECT p.id, p.part_number, COALESCE(p.revision, '') AS revision, COALESCE(p.description, '') AS description,
       COALESCE(p.detail, '') AS detail, COALESCE(p.category, '') AS category,
       EXISTS(SELECT 1 FROM bom c WHERE c.parent_part_id = p.id) AS has_bom,
       p.release_status, COALESCE(p.is_active, FALSE) AS is_active,
       COALESCE(p.requested_by, '') AS requested_by, COALESCE(p.notes, '') AS notes,
       p.created_date, p.modified_date, p.primary_attachment_id,
       COALESCE(p.current_cost, 0) AS current_cost, COALESCE(p.last_rollup_cost, 0) AS last_rollup_cost,
       p.last_rollup_at, COALESCE(p.attachment_count, 0) AS attachment_count,
       COALESCE(p.po_line_count, 0) AS po_line_count,
       p.uom_id, COALESCE(u.abbreviation, '') AS unit_abbr, p.stock_on_hand, p.reorder_min, p.tracking_mode,
       COALESCE(p.user_field_1, '') AS user_field_1, COALESCE(p.user_field_2, '') AS user_field_2,
       COALESCE(p.user_field_3, '') AS user_field_3, COALESCE(p.user_field_4, '') AS user_field_4,
       COALESCE(p.user_field_5, '') AS user_field_5, COALESCE(p.user_field_6, '') AS user_field_6,
       COALESCE(p.user_field_7, '') AS user_field_7, COALESCE(p.user_field_8, '') AS user_field_8,
       COALESCE(p.user_field_9, '') AS user_field_9, COALESCE(p.user_field_10, '') AS user_field_10
FROM part p LEFT JOIN uom u ON u.uom_id = p.uom_id
WHERE p.id = $1
`

type GetPartRow struct {
	ID                  int
	PartNumber          string
	Revision            string
	Description         string
	Detail              string
	Category            string
	HasBom              bool
	ReleaseStatus       string
	IsActive            bool
	RequestedBy         string
	Notes               string
	CreatedDate         *time.Time
	ModifiedDate        *time.Time
	PrimaryAttachmentID *int
	CurrentCost         float64
	LastRollupCost      float64
	LastRollupAt        *time.Time
	AttachmentCount     int
	PoLineCount         int
	UomID               *int
	UnitAbbr            string
	StockOnHand         float64
	ReorderMin          *float64
	TrackingMode        string
	UserField1          string
	UserField2          string
	UserField3          string
	UserField4          string
	UserField5          string
	UserField6          string
	UserField7          string
	UserField8          string
	UserField9          string
	UserField10         string
}

func (q *Queries) GetPart(ctx context.Context, id int) (GetPartRow, error) {
	row := q.db.QueryRowContext(ctx, getPart, id)
	var i GetPartRow
	err := row.Scan(
		&i.ID,
		&i.PartNumber,
		&i.Revision,
		&i.Description,
		&i.Detail,
		&i.Category,
		&i.HasBom,
		&i.ReleaseStatus,
		&i.IsActive,
		&i.RequestedBy,
		&i.Notes,
		&i.CreatedDate,
		&i.ModifiedDate,
		&i.PrimaryAttachmentID,
		&i.CurrentCost,
		&i.LastRollupCost,
		&i.LastRollupAt,
		&i.AttachmentCount,
		&i.PoLineCount,
		&i.UomID,
		&i.UnitAbbr,
		&i.StockOnHand,
		&i.ReorderMin,
		&i.TrackingMode,
		&i.UserField1,
		&i.UserField2,
		&i.UserField3,
		&i.UserField4,
		&i.UserField5,
		&i.UserField6,
		&i.UserField7,
		&i.UserField8,
		&i.UserField9,
		&i.UserField10,
	)
	return i, err
}

const getPartBasic = `-- name: GetPartBasic :one
SELECT p.id, p.part_number, COALESCE(p.description, '') AS description, COALESCE(p.category, '') AS category,
       EXISTS(SELECT 1 FROM bom c WHERE c.parent_part_id = p.id) AS has_bom,
       p.primary_attachment_id, p.stock_on_hand, p.tracking_mode,
       COALESCE((SELECT MIN(a.file_name) FROM part_attachment a
                 WHERE a.part_id = p.id AND a.is_active = TRUE AND a.category = $1::text), '')::text AS thumb_file
FROM part p WHERE p.id = $2
`

type GetPartBasicParams struct {
	ThumbCategory string
	ID            int
}

type GetPartBasicRow struct {
	ID                  int
	PartNumber          string
	Description         string
	Category            string
	HasBom              bool
	PrimaryAttachmentID *int
	StockOnHand         float64
	TrackingMode        string
	ThumbFile           string
}

// The part header behind every part sub-tab page; thumb_file as in ListParts.
func (q *Queries) GetPartBasic(ctx context.Context, arg GetPartBasicParams) (GetPartBasicRow, error) {
	row := q.db.QueryRowContext(ctx, getPartBasic, arg.ThumbCategory, arg.ID)
	var i GetPartBasicRow
	err := row.Scan(
		&i.ID,
		&i.PartNumber,
		&i.Description,
		&i.Category,
		&i.HasBom,
		&i.PrimaryAttachmentID,
		&i.StockOnHand,
		&i.TrackingMode,
		&i.ThumbFile,
	)
	return i, err
}

const getSupplierPart = `-- name: GetSupplierPart :one
SELECT sp.id, sp.supplier_id, sp.part_id, sp.preference, COALESCE(sp.supplier_pn, '') AS supplier_pn,
       COALESCE(sp.supplier_desc, '') AS supplier_desc, COALESCE(sp.lead_time, '') AS lead_time,
       sp.min_increment, sp.uom_id, c.name AS supplier_name
FROM supplier_part sp
JOIN company c ON sp.supplier_id = c.id
WHERE sp.id = $1 AND sp.part_id = $2
`

type GetSupplierPartParams struct {
	ID     int
	PartID int
}

type GetSupplierPartRow struct {
	ID           int
	SupplierID   int
	PartID       int
	Preference   *int
	SupplierPn   string
	SupplierDesc string
	LeadTime     string
	MinIncrement *float64
	UomID        *int
	SupplierName string
}

func (q *Queries) GetSupplierPart(ctx context.Context, arg GetSupplierPartParams) (GetSupplierPartRow, error) {
	row := q.db.QueryRowContext(ctx, getSupplierPart, arg.ID, arg.PartID)
	var i GetSupplierPartRow
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.PartID,
		&i.Preference,
		&i.SupplierPn,
		&i.SupplierDesc,
		&i.LeadTime,
		&i.MinIncrement,
		&i.UomID,
		&i.SupplierName,
	)
	return i, err
}

const importMfgPart = `-- name: ImportMfgPart :exec
INSERT INTO mfg_part (part_id, mfg_id, mfg_part_number, is_active)
VALUES ($1, $2, $3, TRUE)
ON CONFLICT (part_id, mfg_id, mfg_part_number) WHERE is_active DO NOTHING
`

type ImportMfgPartParams struct {
	PartID        int
	MfgID         int
	MfgPartNumber string
}

// ImportMfgPart leaves an existing active (part, manufacturer, MPN) alone.
func (q *Queries) ImportMfgPart(ctx context.Context, arg ImportMfgPartParams) error {
	_, err := q.db.ExecContext(ctx, importMfgPart, arg.PartID, arg.MfgID, arg.MfgPartNumber)
	return err
}

const importPrice = `-- name: ImportPrice :execrows
INSERT INTO price (part_id, supplier_id, pack_size, price_ea, price_pack, effective_date, is_active)
VALUES ($1, $2, $3::numeric, $4::numeric,
        $5::numeric, $6::text::date, TRUE)
ON CONFLICT (part_id, supplier_id, pack_size) WHERE is_active DO NOTHING
`

type ImportPriceParams struct {
	PartID        int
	SupplierID    int
	PackSize      float64
	PriceEa       float64
	PricePack     float64
	EffectiveDate string
}

// ImportPrice skips (0 rows) a pack size that already has an active price.
func (q *Queries) ImportPrice(ctx context.Context, arg ImportPriceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, importPrice,
		arg.PartID,
		arg.SupplierID,
		arg.PackSize,
		arg.PriceEa,
		arg.PricePack,
		arg.EffectiveDate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listActivePrices = `-- name: ListActivePrices :many
SELECT supplier_id, price_ea, price_pack, pack_size, effective_date
FROM price
WHERE part_id = $1 AND is_active = TRUE
ORDER BY supplier_id, pack_size
`

type ListActivePricesRow struct {
	SupplierID    int
	PriceEa       *float64
	PricePack     *float64
	PackSize      *float64
	EffectiveDate *time.Time
}

func (q *Queries) ListActivePrices(ctx context.Context, partID int) ([]ListActivePricesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivePrices, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePricesRow
	for rows.Next() {
		var i ListActivePricesRow
		if err := rows.Scan(
			&i.SupplierID,
			&i.PriceEa,
			&i.PricePack,
			&i.PackSize,
			&i.EffectiveDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBOMComponents = `-- name: ListBOMComponents :many
SELECT pn.id, pl.qty, pn.part_number, COALESCE(pn.description, '') AS description,
       COALESCE(pn.revision, '') AS revision, COALESCE(pn.category, '') AS category,
       pn.stock_on_hand, pn.reorder_min, pn.default_supplier_id,
       EXISTS(SELECT 1 FROM bom c WHERE c.parent_part_id = pn.id) AS has_bom
FROM bom pl
JOIN part pn ON pl.component_part_id = pn.id
WHERE pl.parent_part_id = $1
`

type ListBOMComponentsRow struct {
	ID                int
	Qty               float64
	PartNumber        string
	Description       string
	Revision          string
	Category          string
	StockOnHand       float64
	ReorderMin        *float64
	DefaultSupplierID *int
	HasBom            bool
}

// ListBOMComponents is one BOM level below a parent: each component's part data and whether it
// has its own BOM (the RFQ planner, #99).
func (q *Queries) ListBOMComponents(ctx context.Context, parentPartID int) ([]ListBOMComponentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBOMComponents, parentPartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBOMComponentsRow
	for rows.Next() {
		var i ListBOMComponentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Qty,
			&i.PartNumber,
			&i.Description,
			&i.Revision,
			&i.Category,
			&i.StockOnHand,
			&i.ReorderMin,
			&i.DefaultSupplierID,
			&i.HasBom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManufacturers = `-- name: ListManufacturers :many
SELECT id, name FROM company
WHERE is_manufacturer = TRUE AND is_active = TRUE
ORDER BY name
`

type ListManufacturersRow struct {
	ID   int
	Name string
}

func (q *Queries) ListManufacturers(ctx context.Context) ([]ListManufacturersRow, error) {
	rows, err := q.db.QueryContext(ctx, listManufacturers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManufacturersRow
	for rows.Next() {
		var i ListManufacturersRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMfgParts = `-- name: ListMfgParts :many
SELECT mp.id, mp.part_id, mp.mfg_id, mp.mfg_part_number, COALESCE(mp.description, '') AS description,
       mp.is_active, c.name AS mfg_name
FROM mfg_part mp
JOIN company c ON mp.mfg_id = c.id
WHERE mp.part_id = $1 AND mp.is_active = TRUE
ORDER BY c.name, mp.mfg_part_number
`

type ListMfgPartsRow struct {
	ID            int
	PartID        int
	MfgID         int
	MfgPartNumber string
	Description   string
	IsActive      bool
	MfgName       string
}

func (q *Queries) ListMfgParts(ctx context.Context, partID int) ([]ListMfgPartsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMfgParts, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMfgPartsRow
	for rows.Next() {
		var i ListMfgPartsRow
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.MfgID,
			&i.MfgPartNumber,
			&i.Description,
			&i.IsActive,
			&i.MfgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartCategories = `-- name: ListPartCategories :many
SELECT code, label, is_purchased, is_bom_visible, is_orders_visible, is_pricing_visible,
       is_mfg_parts_visible, is_suppliers_visible, is_inventory_visible
FROM part_category
ORDER BY sort_order, code
`

type ListPartCategoriesRow struct {
	Code               string
	Label              string
	IsPurchased        bool
	IsBomVisible       bool
	IsOrdersVisible    bool
	IsPricingVisible   bool
	IsMfgPartsVisible  bool
	IsSuppliersVisible bool
	IsInventoryVisible bool
}

func (q *Queries) ListPartCategories(ctx context.Context) ([]ListPartCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPartCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartCategoriesRow
	for rows.Next() {
		var i ListPartCategoriesRow
		if err := rows.Scan(
			&i.Code,
			&i.Label,
			&i.IsPurchased,
			&i.IsBomVisible,
			&i.IsOrdersVisible,
			&i.IsPricingVisible,
			&i.IsMfgPartsVisible,
			&i.IsSuppliersVisible,
			&i.IsInventoryVisible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartCategoryCodes = `-- name: ListPartCategoryCodes :many
SELECT code FROM part_category
`

func (q *Queries) ListPartCategoryCodes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPartCategoryCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartNumbers = `-- name: ListPartNumbers :many
SELECT part_number FROM part
`

func (q *Queries) ListPartNumbers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPartNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var part_number string
		if err := rows.Scan(&part_number); err != nil {
			return nil, err
		}
		items = append(items, part_number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParts = `-- name: ListParts :many
SELECT p.id, p.part_number, COALESCE(p.revision, '') AS revision,
       COALESCE(p.description, '') AS description, COALESCE(p.detail, '') AS detail,
       COALESCE(p.requested_by, '') AS requested_by, p.created_date,
       COALESCE(p.category, '') AS category, p.modified_date,
       COALESCE(p.is_active, TRUE) AS is_active,
       COALESCE(p.attachment_count, 0) AS attachment_count,
       COALESCE(p.po_line_count, 0) AS po_line_count,
       (p.reorder_min IS NOT NULL AND p.stock_on_hand < p.reorder_min) AS below_min,
       COALESCE((SELECT MIN(a.file_name) FROM part_attachment a
                 WHERE a.part_id = p.id AND a.is_active = TRUE AND a.category = $1::text), '')::text AS thumb_file
FROM part p ORDER BY p.part_number
`

type ListPartsRow struct {
	ID              int
	PartNumber      string
	Revision        string
	Description     string
	Detail          string
	RequestedBy     string
	CreatedDate     *time.Time
	Category        string
	ModifiedDate    *time.Time
	IsActive        bool
	AttachmentCount int
	PoLineCount     int
	BelowMin        sql.NullBool
	ThumbFile       string
}

// The /parts grid and CSV export. thumb_file is the part's generated PDF
// thumbnail (#696); MIN() is an arbitrary tie-break since the app enforces
// one active Thumbnail row per part.
func (q *Queries) ListParts(ctx context.Context, thumbCategory string) ([]ListPartsRow, error) {
	rows, err := q.db.QueryContext(ctx, listParts, thumbCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartsRow
	for rows.Next() {
		var i ListPartsRow
		if err := rows.Scan(
			&i.ID,
			&i.PartNumber,
			&i.Revision,
			&i.Description,
			&i.Detail,
			&i.RequestedBy,
			&i.CreatedDate,
			&i.Category,
			&i.ModifiedDate,
			&i.IsActive,
			&i.AttachmentCount,
			&i.PoLineCount,
			&i.BelowMin,
			&i.ThumbFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierParts = `-- name: ListSupplierParts :many
SELECT sp.id, sp.supplier_id, sp.part_id, sp.preference, COALESCE(sp.supplier_pn, '') AS supplier_pn,
       COALESCE(sp.supplier_desc, '') AS supplier_desc, COALESCE(sp.lead_time, '') AS lead_time,
       sp.min_increment, sp.uom_id, c.name AS supplier_name,
       COALESCE(pu.abbreviation, bu.abbreviation, '') AS purchase_unit_abbr,
       (sp.uom_id IS NOT NULL)::boolean AS purchase_unit_is_explicit
FROM supplier_part sp
JOIN company c  ON sp.supplier_id = c.id
LEFT JOIN uom pu ON sp.uom_id   = pu.uom_id
LEFT JOIN part p ON sp.part_id  = p.id
LEFT JOIN uom bu ON p.uom_id    = bu.uom_id
WHERE sp.part_id = $1
ORDER BY c.name, sp.supplier_pn
`

type ListSupplierPartsRow struct {
	ID                     int
	SupplierID             int
	PartID                 int
	Preference             *int
	SupplierPn             string
	SupplierDesc           string
	LeadTime               string
	MinIncrement           *float64
	UomID                  *int
	SupplierName           string
	PurchaseUnitAbbr       string
	PurchaseUnitIsExplicit bool
}

func (q *Queries) ListSupplierParts(ctx context.Context, partID int) ([]ListSupplierPartsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSupplierParts, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplierPartsRow
	for rows.Next() {
		var i ListSupplierPartsRow
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.PartID,
			&i.Preference,
			&i.SupplierPn,
			&i.SupplierDesc,
			&i.LeadTime,
			&i.MinIncrement,
			&i.UomID,
			&i.SupplierName,
			&i.PurchaseUnitAbbr,
			&i.PurchaseUnitIsExplicit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMfgPart = `-- name: UpdateMfgPart :exec
UPDATE mfg_part SET mfg_id = $1, mfg_part_number = $2,
  description = $3::text
WHERE id = $4 AND part_id = $5 AND is_active = TRUE
`

type UpdateMfgPartParams struct {
	MfgID         int
	MfgPartNumber string
	Description   string
	ID            int
	PartID        int
}

func (q *Queries) UpdateMfgPart(ctx context.Context, arg UpdateMfgPartParams) error {
	_, err := q.db.ExecContext(ctx, updateMfgPart,
		arg.MfgID,
		arg.MfgPartNumber,
		arg.Description,
		arg.ID,
		arg.PartID,
	)
	return err
}

const updatePart = `-- name: UpdatePart :exec
UPDATE part SET
  part_number = $1, revision = $2::text, description = $3::text,
  detail = $4::text, category = NULLIF($5::text, ''),
  release_status = $6, is_active = $7::boolean,
  requested_by = $8::text, notes = $9::text, modified_date = $10::date,
  uom_id = $11, current_cost = $12::numeric, reorder_min = $13,
  user_field_1 = $14::text, user_field_2 = $15::text,
  user_field_3 = $16::text, user_field_4 = $17::text,
  user_field_5 = $18::text, user_field_6 = $19::text,
  user_field_7 = $20::text, user_field_8 = $21::text,
  user_field_9 = $22::text, user_field_10 = $23::text,
  tracking_mode = $24
WHERE id = $25
`

type UpdatePartParams struct {
	PartNumber    string
	Revision      string
	Description   string
	Detail        string
	Category      string
	ReleaseStatus string
	IsActive      bool
	RequestedBy   string
	Notes         string
	Now           time.Time
	UomID         *int
	CurrentCost   float64
	ReorderMin    *float64
	UserField1    string
	UserField2    string
	UserField3    string
	UserField4    string
	UserField5    string
	UserField6    string
	UserField7    string
	UserField8    string
	UserField9    string
	UserField10   string
	TrackingMode  string
	ID            int
}

func (q *Queries) UpdatePart(ctx context.Context, arg UpdatePartParams) error {
	_, err := q.db.ExecContext(ctx, updatePart,
		arg.PartNumber,
		arg.Revision,
		arg.Description,
		arg.Detail,
		arg.Category,
		arg.ReleaseStatus,
		arg.IsActive,
		arg.RequestedBy,
		arg.Notes,
		arg.Now,
		arg.UomID,
		arg.CurrentCost,
		arg.ReorderMin,
		arg.UserField1,
		arg.UserField2,
		arg.UserField3,
		arg.UserField4,
		arg.UserField5,
		arg.UserField6,
		arg.UserField7,
		arg.UserField8,
		arg.UserField9,
		arg.UserField10,
		arg.TrackingMode,
		arg.ID,
	)
	return err
}

const updateSupplierPart = `-- name: UpdateSupplierPart :exec
UPDATE supplier_part SET supplier_id = $1, preference = $2,
  supplier_pn = $3::text, supplier_desc = $4::text,
  lead_time = $5::text, min_increment = $6, uom_id = $7
WHERE id = $8 AND part_id = $9
`

type UpdateSupplierPartParams struct {
	SupplierID   int
	Preference   *int
	SupplierPn   string
	SupplierDesc string
	LeadTime     string
	MinIncrement *float64
	UomID        *int
	ID           int
	PartID       int
}

func (q *Queries) UpdateSupplierPart(ctx context.Context, arg UpdateSupplierPartParams) error {
	_, err := q.db.ExecContext(ctx, updateSupplierPart,
		arg.SupplierID,
		arg.Preference,
		arg.SupplierPn,
		arg.SupplierDesc,
		arg.LeadTime,
		arg.MinIncrement,
		arg.UomID,
		arg.ID,
		arg.PartID,
	)
	return err
}

const upsertPartCategory = `-- name: UpsertPartCategory :exec
INSERT INTO part_category (code, label, is_purchased, is_bom_visible, is_orders_visible, is_pricing_visible,
                           is_mfg_parts_visible, is_suppliers_visible, is_inventory_visible, sort_order)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9, $10)
ON CONFLICT (code) DO UPDATE SET label=EXCLUDED.label, is_purchased=EXCLUDED.is_purchased,
  is_bom_visible=EXCLUDED.is_bom_visible, is_orders_visible=EXCLUDED.is_orders_visible,
  is_pricing_visible=EXCLUDED.is_pricing_visible, is_mfg_parts_visible=EXCLUDED.is_mfg_parts_visible,
  is_suppliers_visible=EXCLUDED.is_suppliers_visible, is_inventory_visible=EXCLUDED.is_inventory_visible,
  sort_order=EXCLUDED.sort_order, updated_at=now()
`

type UpsertPartCategoryParams struct {
	Code               string
	Label              string
	IsPurchased        bool
	IsBomVisible       bool
	IsOrdersVisible    bool
	IsPricingVisible   bool
	IsMfgPartsVisible  bool
	IsSuppliersVisible bool
	IsInventoryVisible bool
	SortOrder          int
}

func (q *Queries) UpsertPartCategory(ctx context.Context, arg UpsertPartCategoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertPartCategory,
		arg.Code,
		arg.Label,
		arg.IsPurchased,
		arg.IsBomVisible,
		arg.IsOrdersVisible,
		arg.IsPricingVisible,
		arg.IsMfgPartsVisible,
		arg.IsSuppliersVisible,
		arg.IsInventoryVisible,
		arg.SortOrder,
	)
	return err
}
