// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parts.sql

package dbq

import (
	"context"
)

const countPartsByCategory = `-- name: CountPartsByCategory :many
SELECT COALESCE(category, '') AS category, COUNT(*) AS part_count
FROM part
WHERE category IS NOT NULL
GROUP BY category
`

type CountPartsByCategoryRow struct {
	Category  string
	PartCount int64
}

func (q *Queries) CountPartsByCategory(ctx context.Context) ([]CountPartsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, countPartsByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountPartsByCategoryRow
	for rows.Next() {
		var i CountPartsByCategoryRow
		if err := rows.Scan(&i.Category, &i.PartCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMfgPart = `-- name: CreateMfgPart :exec
INSERT INTO mfg_part (part_id, mfg_id, mfg_part_number, description, is_active)
VALUES ($1, $2, $3, $4::text, TRUE)
`

type CreateMfgPartParams struct {
	PartID        int
	MfgID         int
	MfgPartNumber string
	Description   string
}

func (q *Queries) CreateMfgPart(ctx context.Context, arg CreateMfgPartParams) error {
	_, err := q.db.ExecContext(ctx, createMfgPart,
		arg.PartID,
		arg.MfgID,
		arg.MfgPartNumber,
		arg.Description,
	)
	return err
}

const deleteMfgPart = `-- name: DeleteMfgPart :exec
UPDATE mfg_part SET is_active = FALSE WHERE id = $1 AND part_id = $2
`

type DeleteMfgPartParams struct {
	ID     int
	PartID int
}

func (q *Queries) DeleteMfgPart(ctx context.Context, arg DeleteMfgPartParams) error {
	_, err := q.db.ExecContext(ctx, deleteMfgPart, arg.ID, arg.PartID)
	return err
}

const deletePartCategory = `-- name: DeletePartCategory :exec
DELETE FROM part_category WHERE code = $1
`

func (q *Queries) DeletePartCategory(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, deletePartCategory, code)
	return err
}

const getMfgPart = `-- name: GetMfgPart :one
SELECT id, part_id, mfg_id, mfg_part_number, COALESCE(description, '') AS description
FROM mfg_part
WHERE id = $1 AND part_id = $2 AND is_active = TRUE
`

type GetMfgPartParams struct {
	ID     int
	PartID int
}

type GetMfgPartRow struct {
	ID            int
	PartID        int
	MfgID         int
	MfgPartNumber string
	Description   string
}

func (q *Queries) GetMfgPart(ctx context.Context, arg GetMfgPartParams) (GetMfgPartRow, error) {
	row := q.db.QueryRowContext(ctx, getMfgPart, arg.ID, arg.PartID)
	var i GetMfgPartRow
	err := row.Scan(
		&i.ID,
		&i.PartID,
		&i.MfgID,
		&i.MfgPartNumber,
		&i.Description,
	)
	return i, err
}

const listManufacturers = `-- name: ListManufacturers :many
SELECT id, name FROM company
WHERE is_manufacturer = TRUE AND is_active = TRUE
ORDER BY name
`

type ListManufacturersRow struct {
	ID   int
	Name string
}

func (q *Queries) ListManufacturers(ctx context.Context) ([]ListManufacturersRow, error) {
	rows, err := q.db.QueryContext(ctx, listManufacturers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManufacturersRow
	for rows.Next() {
		var i ListManufacturersRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMfgParts = `-- name: ListMfgParts :many
SELECT mp.id, mp.part_id, mp.mfg_id, mp.mfg_part_number, COALESCE(mp.description, '') AS description,
       mp.is_active, c.name AS mfg_name
FROM mfg_part mp
JOIN company c ON mp.mfg_id = c.id
WHERE mp.part_id = $1 AND mp.is_active = TRUE
ORDER BY c.name, mp.mfg_part_number
`

type ListMfgPartsRow struct {
	ID            int
	PartID        int
	MfgID         int
	MfgPartNumber string
	Description   string
	IsActive      bool
	MfgName       string
}

func (q *Queries) ListMfgParts(ctx context.Context, partID int) ([]ListMfgPartsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMfgParts, partID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMfgPartsRow
	for rows.Next() {
		var i ListMfgPartsRow
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.MfgID,
			&i.MfgPartNumber,
			&i.Description,
			&i.IsActive,
			&i.MfgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartCategories = `-- name: ListPartCategories :many
SELECT code, label, is_purchased, is_bom_visible, is_orders_visible, is_pricing_visible,
       is_mfg_parts_visible, is_suppliers_visible, is_inventory_visible
FROM part_category
ORDER BY sort_order, code
`

type ListPartCategoriesRow struct {
	Code               string
	Label              string
	IsPurchased        bool
	IsBomVisible       bool
	IsOrdersVisible    bool
	IsPricingVisible   bool
	IsMfgPartsVisible  bool
	IsSuppliersVisible bool
	IsInventoryVisible bool
}

func (q *Queries) ListPartCategories(ctx context.Context) ([]ListPartCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPartCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartCategoriesRow
	for rows.Next() {
		var i ListPartCategoriesRow
		if err := rows.Scan(
			&i.Code,
			&i.Label,
			&i.IsPurchased,
			&i.IsBomVisible,
			&i.IsOrdersVisible,
			&i.IsPricingVisible,
			&i.IsMfgPartsVisible,
			&i.IsSuppliersVisible,
			&i.IsInventoryVisible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartCategoryCodes = `-- name: ListPartCategoryCodes :many
SELECT code FROM part_category
`

func (q *Queries) ListPartCategoryCodes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPartCategoryCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMfgPart = `-- name: UpdateMfgPart :exec
UPDATE mfg_part SET mfg_id = $1, mfg_part_number = $2,
  description = $3::text
WHERE id = $4 AND part_id = $5 AND is_active = TRUE
`

type UpdateMfgPartParams struct {
	MfgID         int
	MfgPartNumber string
	Description   string
	ID            int
	PartID        int
}

func (q *Queries) UpdateMfgPart(ctx context.Context, arg UpdateMfgPartParams) error {
	_, err := q.db.ExecContext(ctx, updateMfgPart,
		arg.MfgID,
		arg.MfgPartNumber,
		arg.Description,
		arg.ID,
		arg.PartID,
	)
	return err
}

const upsertPartCategory = `-- name: UpsertPartCategory :exec
INSERT INTO part_category (code, label, is_purchased, is_bom_visible, is_orders_visible, is_pricing_visible,
                           is_mfg_parts_visible, is_suppliers_visible, is_inventory_visible, sort_order)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9, $10)
ON CONFLICT (code) DO UPDATE SET label=EXCLUDED.label, is_purchased=EXCLUDED.is_purchased,
  is_bom_visible=EXCLUDED.is_bom_visible, is_orders_visible=EXCLUDED.is_orders_visible,
  is_pricing_visible=EXCLUDED.is_pricing_visible, is_mfg_parts_visible=EXCLUDED.is_mfg_parts_visible,
  is_suppliers_visible=EXCLUDED.is_suppliers_visible, is_inventory_visible=EXCLUDED.is_inventory_visible,
  sort_order=EXCLUDED.sort_order, updated_at=now()
`

type UpsertPartCategoryParams struct {
	Code               string
	Label              string
	IsPurchased        bool
	IsBomVisible       bool
	IsOrdersVisible    bool
	IsPricingVisible   bool
	IsMfgPartsVisible  bool
	IsSuppliersVisible bool
	IsInventoryVisible bool
	SortOrder          int
}

func (q *Queries) UpsertPartCategory(ctx context.Context, arg UpsertPartCategoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertPartCategory,
		arg.Code,
		arg.Label,
		arg.IsPurchased,
		arg.IsBomVisible,
		arg.IsOrdersVisible,
		arg.IsPricingVisible,
		arg.IsMfgPartsVisible,
		arg.IsSuppliersVisible,
		arg.IsInventoryVisible,
		arg.SortOrder,
	)
	return err
}
