// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purchasing.sql

package dbq

import (
	"context"
	"time"
)

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO company (name, supplier_code, default_contact, is_active, is_supplier, is_manufacturer, notes)
VALUES ($1, $2::text, $3,
        $4::boolean, $5::boolean, $6::boolean,
        $7::text)
RETURNING id
`

type CreateSupplierParams struct {
	Name           string
	SupplierCode   string
	DefaultContact *int
	IsActive       bool
	IsSupplier     bool
	IsManufacturer bool
	Notes          string
}

// The bulk-order options keep their column defaults.
func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createSupplier,
		arg.Name,
		arg.SupplierCode,
		arg.DefaultContact,
		arg.IsActive,
		arg.IsSupplier,
		arg.IsManufacturer,
		arg.Notes,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const getSupplier = `-- name: GetSupplier :one
SELECT su.id, su.name, COALESCE(su.supplier_code, '') AS supplier_code, COALESCE(su.notes, '') AS notes,
       su.default_contact, COALESCE(su.is_active, FALSE) AS is_active,
       COALESCE(su.is_supplier, FALSE) AS is_supplier, COALESCE(su.is_manufacturer, FALSE) AS is_manufacturer,
       COALESCE(su.supplier_part_count, 0) AS supplier_part_count, COALESCE(su.po_count, 0) AS po_count,
       su.date_modified, su.primary_attachment_id,
       su.bulk_order_delimiter, su.bulk_order_pn_source,
       COALESCE(cn.display_name, '') AS contact_name, COALESCE(cn.phone_1, '') AS contact_phone,
       COALESCE(cn.email, '') AS contact_email, COALESCE(cn.city, '') AS contact_city
FROM company su
LEFT JOIN contact cn ON su.default_contact = cn.id
WHERE su.id = $1
`

type GetSupplierRow struct {
	ID                  int
	Name                string
	SupplierCode        string
	Notes               string
	DefaultContact      *int
	IsActive            bool
	IsSupplier          bool
	IsManufacturer      bool
	SupplierPartCount   int
	PoCount             int
	DateModified        *time.Time
	PrimaryAttachmentID *int
	BulkOrderDelimiter  string
	BulkOrderPnSource   string
	ContactName         string
	ContactPhone        string
	ContactEmail        string
	ContactCity         string
}

func (q *Queries) GetSupplier(ctx context.Context, id int) (GetSupplierRow, error) {
	row := q.db.QueryRowContext(ctx, getSupplier, id)
	var i GetSupplierRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SupplierCode,
		&i.Notes,
		&i.DefaultContact,
		&i.IsActive,
		&i.IsSupplier,
		&i.IsManufacturer,
		&i.SupplierPartCount,
		&i.PoCount,
		&i.DateModified,
		&i.PrimaryAttachmentID,
		&i.BulkOrderDelimiter,
		&i.BulkOrderPnSource,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.ContactCity,
	)
	return i, err
}

const listSupplierLinkedParts = `-- name: ListSupplierLinkedParts :many
SELECT sp.id, sp.part_id, sp.preference, COALESCE(sp.supplier_pn, '') AS supplier_pn,
       COALESCE(sp.supplier_desc, '') AS supplier_desc, COALESCE(sp.lead_time, '') AS lead_time,
       sp.min_increment,
       pn.part_number, COALESCE(pn.description, '') AS description, COALESCE(pn.revision, '') AS revision,
       COALESCE(pn.category, '') AS category,
       sp.uom_id,
       COALESCE(pu.abbreviation, bu.abbreviation, '')::text AS effective_unit,
       (sp.uom_id IS NOT NULL)::boolean AS unit_is_explicit,
       COALESCE((SELECT MIN(file_name) FROM part_attachment a
                 WHERE a.part_id = pn.id AND a.is_active = TRUE AND a.category = $1::text), '')::text AS thumb_file
FROM supplier_part sp
JOIN part pn ON sp.part_id = pn.id
LEFT JOIN uom pu ON sp.uom_id = pu.uom_id
LEFT JOIN uom bu ON pn.uom_id = bu.uom_id
WHERE sp.supplier_id = $2::int
ORDER BY pn.part_number
`

type ListSupplierLinkedPartsParams struct {
	ThumbCategory string
	SupplierID    int
}

type ListSupplierLinkedPartsRow struct {
	ID             int
	PartID         int
	Preference     *int
	SupplierPn     string
	SupplierDesc   string
	LeadTime       string
	MinIncrement   *float64
	PartNumber     string
	Description    string
	Revision       string
	Category       string
	UomID          *int
	EffectiveUnit  string
	UnitIsExplicit bool
	ThumbFile      string
}

// The supplier's Parts tab. effective_unit is the explicit purchase unit, else the part's base
// unit; thumb_file as in parts.ListParts.
func (q *Queries) ListSupplierLinkedParts(ctx context.Context, arg ListSupplierLinkedPartsParams) ([]ListSupplierLinkedPartsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSupplierLinkedParts, arg.ThumbCategory, arg.SupplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplierLinkedPartsRow
	for rows.Next() {
		var i ListSupplierLinkedPartsRow
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.Preference,
			&i.SupplierPn,
			&i.SupplierDesc,
			&i.LeadTime,
			&i.MinIncrement,
			&i.PartNumber,
			&i.Description,
			&i.Revision,
			&i.Category,
			&i.UomID,
			&i.EffectiveUnit,
			&i.UnitIsExplicit,
			&i.ThumbFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierPOLinks = `-- name: ListSupplierPOLinks :many
SELECT pol.part_id, po.number
FROM po_line pol
JOIN purchase_order po ON pol.po_id = po.id
WHERE po.supplier_id = $1::int AND po.rfq_group_id IS NULL
ORDER BY po.number DESC
`

type ListSupplierPOLinksRow struct {
	PartID *int
	Number string
}

// (part, PO number) pairs for a supplier's non-RFQ PO lines, PO number descending.
func (q *Queries) ListSupplierPOLinks(ctx context.Context, supplierID int) ([]ListSupplierPOLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listSupplierPOLinks, supplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplierPOLinksRow
	for rows.Next() {
		var i ListSupplierPOLinksRow
		if err := rows.Scan(&i.PartID, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierPOs = `-- name: ListSupplierPOs :many
SELECT number, COALESCE(status, '') AS status, date_ordered, COALESCE(total_cost, 0)::float8 AS total_cost
FROM purchase_order
WHERE supplier_id = $1::int
ORDER BY date_ordered DESC, id DESC
LIMIT $2::int
`

type ListSupplierPOsParams struct {
	SupplierID int
	N          *int
}

type ListSupplierPOsRow struct {
	Number      string
	Status      string
	DateOrdered *time.Time
	TotalCost   float64
}

// A supplier's POs (RFQ quotes included), most recent first; a NULL n means no limit.
func (q *Queries) ListSupplierPOs(ctx context.Context, arg ListSupplierPOsParams) ([]ListSupplierPOsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSupplierPOs, arg.SupplierID, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplierPOsRow
	for rows.Next() {
		var i ListSupplierPOsRow
		if err := rows.Scan(
			&i.Number,
			&i.Status,
			&i.DateOrdered,
			&i.TotalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierRows = `-- name: ListSupplierRows :many
SELECT su.id, su.name, COALESCE(su.supplier_code, '') AS supplier_code,
       COALESCE(su.supplier_part_count, 0) AS supplier_part_count, COALESCE(su.po_count, 0) AS po_count,
       COALESCE(su.is_active, FALSE) AS is_active,
       COALESCE(cn.display_name, '') AS contact_name, COALESCE(cn.country, '') AS contact_country
FROM company su
LEFT JOIN contact cn ON su.default_contact = cn.id
ORDER BY su.name ASC
`

type ListSupplierRowsRow struct {
	ID                int
	Name              string
	SupplierCode      string
	SupplierPartCount int
	PoCount           int
	IsActive          bool
	ContactName       string
	ContactCountry    string
}

// The /suppliers grid: every company with its default contact's name/country.
func (q *Queries) ListSupplierRows(ctx context.Context) ([]ListSupplierRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSupplierRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplierRowsRow
	for rows.Next() {
		var i ListSupplierRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SupplierCode,
			&i.SupplierPartCount,
			&i.PoCount,
			&i.IsActive,
			&i.ContactName,
			&i.ContactCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopSupplierParts = `-- name: ListTopSupplierParts :many
SELECT pn.id, pn.part_number, COALESCE(pn.description, '') AS description
FROM supplier_part sp
JOIN part pn ON sp.part_id = pn.id
WHERE sp.supplier_id = $1::int
ORDER BY pn.part_number
LIMIT $2::int
`

type ListTopSupplierPartsParams struct {
	SupplierID int
	N          int
}

type ListTopSupplierPartsRow struct {
	ID          int
	PartNumber  string
	Description string
}

func (q *Queries) ListTopSupplierParts(ctx context.Context, arg ListTopSupplierPartsParams) ([]ListTopSupplierPartsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopSupplierParts, arg.SupplierID, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopSupplierPartsRow
	for rows.Next() {
		var i ListTopSupplierPartsRow
		if err := rows.Scan(&i.ID, &i.PartNumber, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSuppliers = `-- name: SearchSuppliers :many
SELECT su.id, su.name, COALESCE(cn.city, '') AS city
FROM company su
LEFT JOIN contact cn ON su.default_contact = cn.id
WHERE su.name LIKE $1::text AND su.is_active = TRUE
  AND (NOT $2::boolean OR su.is_supplier = TRUE)
ORDER BY su.name
LIMIT $3::int
`

type SearchSuppliersParams struct {
	Pattern      string
	SupplierOnly bool
	N            int
}

type SearchSuppliersRow struct {
	ID   int
	Name string
	City string
}

// Typeahead: active companies whose name is LIKE pattern, with the default contact's city.
func (q *Queries) SearchSuppliers(ctx context.Context, arg SearchSuppliersParams) ([]SearchSuppliersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchSuppliers, arg.Pattern, arg.SupplierOnly, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSuppliersRow
	for rows.Next() {
		var i SearchSuppliersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.City); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSupplier = `-- name: UpdateSupplier :exec
UPDATE company SET name = $1, supplier_code = $2::text,
       default_contact = $3,
       is_active = $4::boolean, is_supplier = $5::boolean,
       is_manufacturer = $6::boolean,
       notes = $7::text, date_modified = CURRENT_TIMESTAMP,
       bulk_order_delimiter = $8, bulk_order_pn_source = $9
WHERE id = $10
`

type UpdateSupplierParams struct {
	Name               string
	SupplierCode       string
	DefaultContact     *int
	IsActive           bool
	IsSupplier         bool
	IsManufacturer     bool
	Notes              string
	BulkOrderDelimiter string
	BulkOrderPnSource  string
	ID                 int
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) error {
	_, err := q.db.ExecContext(ctx, updateSupplier,
		arg.Name,
		arg.SupplierCode,
		arg.DefaultContact,
		arg.IsActive,
		arg.IsSupplier,
		arg.IsManufacturer,
		arg.Notes,
		arg.BulkOrderDelimiter,
		arg.BulkOrderPnSource,
		arg.ID,
	)
	return err
}
