// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: records.sql

package dbq

import (
	"context"
)

const getRecordHeader = `-- name: GetRecordHeader :one

SELECT COALESCE(r.serial_number, '') AS serial_number, r.is_locked, pn.part_number
FROM form_record r
JOIN form f ON r.form_id = f.id
JOIN part pn ON f.part_number_id = pn.id
WHERE r.id = $1
`

type GetRecordHeaderRow struct {
	SerialNumber string
	IsLocked     bool
	PartNumber   string
}

// Test-record domain (#190, #248; grows with #223). sqlc generates internal/dbq/records.sql.go
// from this file; the service is records.go.
// A record's serial, lock state and its form's part number (the paste-image guard reads this).
func (q *Queries) GetRecordHeader(ctx context.Context, id int) (GetRecordHeaderRow, error) {
	row := q.db.QueryRowContext(ctx, getRecordHeader, id)
	var i GetRecordHeaderRow
	err := row.Scan(&i.SerialNumber, &i.IsLocked, &i.PartNumber)
	return i, err
}
