// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: records.sql

package dbq

import (
	"context"
	"database/sql"
	"time"
)

const approveRecord = `-- name: ApproveRecord :execrows
UPDATE form_record SET is_approved = TRUE, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND is_locked = TRUE AND is_approved = FALSE
`

func (q *Queries) ApproveRecord(ctx context.Context, id int) (int64, error) {
	result, err := q.db.ExecContext(ctx, approveRecord, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimRecord = `-- name: ClaimRecord :execrows
UPDATE form_record SET updated_at = CURRENT_TIMESTAMP WHERE id = $1 AND is_locked = FALSE
`

// Takes a WIP record's row lock for the rest of the tx (#191); 0 rows = locked or missing.
func (q *Queries) ClaimRecord(ctx context.Context, id int) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimRecord, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeRecord = `-- name: CompleteRecord :execrows
UPDATE form_record SET is_locked = TRUE, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND is_locked = FALSE
  AND ($2::int IS NULL OR form_id = $2::int)
`

type CompleteRecordParams struct {
	ID     int
	FormID *int
}

// WIP → Complete; takes the record's row lock. A non-NULL form_id scopes a bulk complete to that form.
func (q *Queries) CompleteRecord(ctx context.Context, arg CompleteRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeRecord, arg.ID, arg.FormID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const copyRecordResults = `-- name: CopyRecordResults :exec
INSERT INTO result (form_record_id, form_row_id, type, parameter, specification, spec_min, spec_nom, spec_max,
                    spec_units, pf_type, format, hide_formula, default_result, result, comment, pass_fail, updated_at)
SELECT $1, s.form_row_id, s.type, s.parameter, s.specification, s.spec_min, s.spec_nom,
       s.spec_max, s.spec_units, s.pf_type, s.format, s.hide_formula, s.default_result, s.result, s.comment,
       s.pass_fail, CURRENT_TIMESTAMP
FROM result s
WHERE s.form_record_id = $2
`

type CopyRecordResultsParams struct {
	ToRecordID   int
	FromRecordID int
}

// Copies every result row (snapshot and recorded value) of one record onto another.
func (q *Queries) CopyRecordResults(ctx context.Context, arg CopyRecordResultsParams) error {
	_, err := q.db.ExecContext(ctx, copyRecordResults, arg.ToRecordID, arg.FromRecordID)
	return err
}

const copyStep = `-- name: CopyStep :one
INSERT INTO form_row (form_id, type, parameter, specification, spec_nom, spec_min, spec_max, spec_units, pf_type,
                      default_result, hide_formula, category, sheet_name, instrument_types, format, comment,
                      archive_id, revision)
SELECT $1, COALESCE(s.type, 0), COALESCE(s.parameter, ''), COALESCE(s.specification, ''),
       s.spec_nom, s.spec_min, s.spec_max, s.spec_units, s.pf_type, s.default_result, s.hide_formula, s.category,
       s.sheet_name, s.instrument_types, s.format, s.comment, s.archive_id, s.revision
FROM form_row s
WHERE s.id = $2 AND s.form_id = $3
RETURNING id
`

type CopyStepParams struct {
	ToFormID   int
	StepID     int
	FromFormID int
}

// Copies one step of from_form_id into another form (no row when the step isn't one of from_form_id's). archived
// is not copied (a copy starts active); a NULL type / parameter / specification becomes 0 / ”.
func (q *Queries) CopyStep(ctx context.Context, arg CopyStepParams) (int, error) {
	row := q.db.QueryRowContext(ctx, copyStep, arg.ToFormID, arg.StepID, arg.FromFormID)
	var id int
	err := row.Scan(&id)
	return id, err
}

const countFormSteps = `-- name: CountFormSteps :one
SELECT COUNT(*)::int FROM form_row WHERE form_id = $1
`

func (q *Queries) CountFormSteps(ctx context.Context, formID int) (int, error) {
	row := q.db.QueryRowContext(ctx, countFormSteps, formID)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const duplicateRecord = `-- name: DuplicateRecord :one
INSERT INTO form_record (form_id, part_id, serial_number, subject_part_number, subject_pn_description,
                         record_type, instrument_type, test_order, record_date, created_at, is_active, is_locked,
                         is_approved, form_revision, unit_id)
SELECT s.form_id, s.part_id, s.serial_number, s.subject_part_number, s.subject_pn_description,
       s.record_type, COALESCE(s.instrument_type, ''), s.test_order, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, FALSE,
       FALSE, f.revision, s.unit_id
FROM form_record s
JOIN form f ON f.id = s.form_id
WHERE s.id = $1
RETURNING id
`

// A fresh WIP re-test of a record: same form, part, serial, subject, type, instrument and step order, dated now,
// stamped with the form's current revision (#260), unit carried over (#745). No row = no such record.
func (q *Queries) DuplicateRecord(ctx context.Context, id int) (int, error) {
	row := q.db.QueryRowContext(ctx, duplicateRecord, id)
	var id_2 int
	err := row.Scan(&id_2)
	return id_2, err
}

const getActiveNamedQuery = `-- name: GetActiveNamedQuery :one
SELECT sql, result_type FROM named_queries WHERE name = $1 AND is_active = TRUE
`

type GetActiveNamedQueryRow struct {
	Sql        string
	ResultType string
}

func (q *Queries) GetActiveNamedQuery(ctx context.Context, name string) (GetActiveNamedQueryRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveNamedQuery, name)
	var i GetActiveNamedQueryRow
	err := row.Scan(&i.Sql, &i.ResultType)
	return i, err
}

const getFormHeader = `-- name: GetFormHeader :one
SELECT f.id, f.part_number_id, f.is_locked, COALESCE(f.test_order, '') AS test_order, f.revision,
       pn.part_number, COALESCE(pn.description, '') AS description,
       COALESCE(f.record_types, '') AS record_types, COALESCE(f.instrument_types, '') AS instrument_types
FROM form f
JOIN part pn ON f.part_number_id = pn.id
WHERE f.id = $1
`

type GetFormHeaderRow struct {
	ID              int
	PartNumberID    int
	IsLocked        bool
	TestOrder       string
	Revision        int
	PartNumber      string
	Description     string
	RecordTypes     string
	InstrumentTypes string
}

// A form with its part's number/description; every page that shows a form header reads this.
func (q *Queries) GetFormHeader(ctx context.Context, id int) (GetFormHeaderRow, error) {
	row := q.db.QueryRowContext(ctx, getFormHeader, id)
	var i GetFormHeaderRow
	err := row.Scan(
		&i.ID,
		&i.PartNumberID,
		&i.IsLocked,
		&i.TestOrder,
		&i.Revision,
		&i.PartNumber,
		&i.Description,
		&i.RecordTypes,
		&i.InstrumentTypes,
	)
	return i, err
}

const getFormStep = `-- name: GetFormStep :one
SELECT id, form_id, COALESCE(parameter, '') AS parameter, COALESCE(specification, '') AS specification,
       COALESCE(spec_units, '') AS spec_units, COALESCE(format, '') AS format
FROM form_row
WHERE id = $1
`

type GetFormStepRow struct {
	ID            int
	FormID        int
	Parameter     string
	Specification string
	SpecUnits     string
	Format        string
}

// One step's report header fields; the caller checks form_id belongs to the form in the URL.
func (q *Queries) GetFormStep(ctx context.Context, id int) (GetFormStepRow, error) {
	row := q.db.QueryRowContext(ctx, getFormStep, id)
	var i GetFormStepRow
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Parameter,
		&i.Specification,
		&i.SpecUnits,
		&i.Format,
	)
	return i, err
}

const getFormStepFormat = `-- name: GetFormStepFormat :one
SELECT COALESCE(format, '')::text AS format
FROM form_row
WHERE id = $1 AND form_id = $2
`

type GetFormStepFormatParams struct {
	ID     int
	FormID int
}

// A step's display format, scoped to its form (a step of another form is no row).
func (q *Queries) GetFormStepFormat(ctx context.Context, arg GetFormStepFormatParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getFormStepFormat, arg.ID, arg.FormID)
	var format string
	err := row.Scan(&format)
	return format, err
}

const getPartLabel = `-- name: GetPartLabel :one
SELECT part_number, COALESCE(description, '') AS description
FROM part
WHERE id = $1
`

type GetPartLabelRow struct {
	PartNumber  string
	Description string
}

// The part number / description denormalized onto a new record as its subject.
func (q *Queries) GetPartLabel(ctx context.Context, id int) (GetPartLabelRow, error) {
	row := q.db.QueryRowContext(ctx, getPartLabel, id)
	var i GetPartLabelRow
	err := row.Scan(&i.PartNumber, &i.Description)
	return i, err
}

const getPartTracking = `-- name: GetPartTracking :one
SELECT p.tracking_mode, (SELECT COUNT(*) FROM bom b WHERE b.parent_part_id = p.id)::int AS bom_count
FROM part p
WHERE p.id = $1
`

type GetPartTrackingRow struct {
	TrackingMode string
	BomCount     int
}

// The tested part's tracking mode and how many BOM lines it has as a parent (buildable if > 0).
func (q *Queries) GetPartTracking(ctx context.Context, id int) (GetPartTrackingRow, error) {
	row := q.db.QueryRowContext(ctx, getPartTracking, id)
	var i GetPartTrackingRow
	err := row.Scan(&i.TrackingMode, &i.BomCount)
	return i, err
}

const getRecord = `-- name: GetRecord :one

SELECT id, form_id, COALESCE(part_id, 0)::int AS part_id, COALESCE(serial_number, '') AS serial_number,
       COALESCE(subject_part_number, '') AS subject_part_number,
       COALESCE(subject_pn_description, '') AS subject_pn_description,
       record_date, COALESCE(record_type, '') AS record_type, COALESCE(notes, '') AS notes,
       COALESCE(instrument_type, '') AS instrument_type, is_locked, is_approved, is_active,
       COALESCE(test_order, '') AS test_order, lot_id, build_id, unit_id
FROM form_record
WHERE id = $1
`

type GetRecordRow struct {
	ID                   int
	FormID               int
	PartID               int
	SerialNumber         string
	SubjectPartNumber    string
	SubjectPnDescription string
	RecordDate           sql.NullTime
	RecordType           string
	Notes                string
	InstrumentType       string
	IsLocked             bool
	IsApproved           bool
	IsActive             bool
	TestOrder            string
	LotID                *int
	BuildID              *int
	UnitID               *int
}

// ── Records ──────────────────────────────────────────────────────────────────
func (q *Queries) GetRecord(ctx context.Context, id int) (GetRecordRow, error) {
	row := q.db.QueryRowContext(ctx, getRecord, id)
	var i GetRecordRow
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.PartID,
		&i.SerialNumber,
		&i.SubjectPartNumber,
		&i.SubjectPnDescription,
		&i.RecordDate,
		&i.RecordType,
		&i.Notes,
		&i.InstrumentType,
		&i.IsLocked,
		&i.IsApproved,
		&i.IsActive,
		&i.TestOrder,
		&i.LotID,
		&i.BuildID,
		&i.UnitID,
	)
	return i, err
}

const getRecordHeader = `-- name: GetRecordHeader :one

SELECT COALESCE(r.serial_number, '') AS serial_number, r.is_locked, pn.part_number
FROM form_record r
JOIN form f ON r.form_id = f.id
JOIN part pn ON f.part_number_id = pn.id
WHERE r.id = $1
`

type GetRecordHeaderRow struct {
	SerialNumber string
	IsLocked     bool
	PartNumber   string
}

// Test-record domain (#190, #248, #249; grows with #223). sqlc generates internal/dbq/records.sql.go
// from this file; the service is records.go.
// A record's serial, lock state and its form's part number (the paste-image guard reads this).
func (q *Queries) GetRecordHeader(ctx context.Context, id int) (GetRecordHeaderRow, error) {
	row := q.db.QueryRowContext(ctx, getRecordHeader, id)
	var i GetRecordHeaderRow
	err := row.Scan(&i.SerialNumber, &i.IsLocked, &i.PartNumber)
	return i, err
}

const getRecordNeighbors = `-- name: GetRecordNeighbors :one
WITH ordered AS (
    SELECT id,
           LAG(id)  OVER (ORDER BY (CASE WHEN serial_number ~ '^[0-9]+$' THEN CAST(serial_number AS INTEGER) END) DESC, record_date DESC) AS prev_id,
           LEAD(id) OVER (ORDER BY (CASE WHEN serial_number ~ '^[0-9]+$' THEN CAST(serial_number AS INTEGER) END) DESC, record_date DESC) AS next_id
    FROM form_record
    WHERE form_id = $2 AND is_active = TRUE
)
SELECT COALESCE(prev_id, 0)::int AS prev_id, COALESCE(next_id, 0)::int AS next_id
FROM ordered
WHERE id = $1
`

type GetRecordNeighborsParams struct {
	RecordID int
	FormID   int
}

type GetRecordNeighborsRow struct {
	PrevID int
	NextID int
}

// Previous / next active record id (0 = none) in the records-table order; no row when the record
// is not an active record of the form.
func (q *Queries) GetRecordNeighbors(ctx context.Context, arg GetRecordNeighborsParams) (GetRecordNeighborsRow, error) {
	row := q.db.QueryRowContext(ctx, getRecordNeighbors, arg.RecordID, arg.FormID)
	var i GetRecordNeighborsRow
	err := row.Scan(&i.PrevID, &i.NextID)
	return i, err
}

const insertEventResult = `-- name: InsertEventResult :exec
INSERT INTO record_event_results (event_id, form_row_id, parameter, specification, spec_units, result, pass_fail, comment)
VALUES ($1, $2, $3::text, $4::text,
        $5::text, $6::text, $7::bool, $8::text)
`

type InsertEventResultParams struct {
	EventID       int
	FormRowID     int
	Parameter     string
	Specification string
	SpecUnits     string
	Result        string
	PassFail      sql.NullBool
	Comment       string
}

func (q *Queries) InsertEventResult(ctx context.Context, arg InsertEventResultParams) error {
	_, err := q.db.ExecContext(ctx, insertEventResult,
		arg.EventID,
		arg.FormRowID,
		arg.Parameter,
		arg.Specification,
		arg.SpecUnits,
		arg.Result,
		arg.PassFail,
		arg.Comment,
	)
	return err
}

const insertForm = `-- name: InsertForm :one
INSERT INTO form (part_number_id, is_active, is_locked, test_order, record_types, instrument_types)
VALUES ($1, TRUE, FALSE, '',
        (SELECT s.record_types FROM form s WHERE s.id = $2),
        (SELECT s.instrument_types FROM form s WHERE s.id = $2))
RETURNING id
`

type InsertFormParams struct {
	PartNumberID int
	SourceID     int
}

// A new active, unlocked form with an empty step order. Record / instrument types come from the source form
// (NULL when there is none).
func (q *Queries) InsertForm(ctx context.Context, arg InsertFormParams) (int, error) {
	row := q.db.QueryRowContext(ctx, insertForm, arg.PartNumberID, arg.SourceID)
	var id int
	err := row.Scan(&id)
	return id, err
}

const insertFormEvent = `-- name: InsertFormEvent :exec
INSERT INTO form_events (form_id, event_type, username, event_date, comments)
VALUES ($1, $2, $3::text, CURRENT_TIMESTAMP, $4::text)
`

type InsertFormEventParams struct {
	FormID    int
	EventType string
	Username  string
	Comments  sql.NullString
}

func (q *Queries) InsertFormEvent(ctx context.Context, arg InsertFormEventParams) error {
	_, err := q.db.ExecContext(ctx, insertFormEvent,
		arg.FormID,
		arg.EventType,
		arg.Username,
		arg.Comments,
	)
	return err
}

const insertNamedQuery = `-- name: InsertNamedQuery :one
INSERT INTO named_queries (name, description, sql, params, result_type, is_active)
VALUES ($1, $2::text, $3, $4::text, $5,
        $6)
RETURNING id
`

type InsertNamedQueryParams struct {
	Name        string
	Description string
	Sql         string
	Params      string
	ResultType  string
	IsActive    bool
}

func (q *Queries) InsertNamedQuery(ctx context.Context, arg InsertNamedQueryParams) (int, error) {
	row := q.db.QueryRowContext(ctx, insertNamedQuery,
		arg.Name,
		arg.Description,
		arg.Sql,
		arg.Params,
		arg.ResultType,
		arg.IsActive,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const insertRecord = `-- name: InsertRecord :one
INSERT INTO form_record (form_id, part_id, serial_number, subject_part_number, subject_pn_description,
                         record_type, instrument_type, test_order, record_date, created_at, is_active, is_locked,
                         form_revision)
VALUES ($1, $2, $3::text, $4::text,
        $5::text, $6::text, $7::text,
        $8::text, $9::timestamp, CURRENT_TIMESTAMP, TRUE, FALSE,
        $10::int)
RETURNING id
`

type InsertRecordParams struct {
	FormID               int
	PartID               *int
	SerialNumber         string
	SubjectPartNumber    string
	SubjectPnDescription string
	RecordType           string
	InstrumentType       string
	TestOrder            string
	RecordDate           time.Time
	FormRevision         int
}

func (q *Queries) InsertRecord(ctx context.Context, arg InsertRecordParams) (int, error) {
	row := q.db.QueryRowContext(ctx, insertRecord,
		arg.FormID,
		arg.PartID,
		arg.SerialNumber,
		arg.SubjectPartNumber,
		arg.SubjectPnDescription,
		arg.RecordType,
		arg.InstrumentType,
		arg.TestOrder,
		arg.RecordDate,
		arg.FormRevision,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const insertRecordEvent = `-- name: InsertRecordEvent :one
INSERT INTO record_events (form_record_id, event_type, username, event_date, comments)
VALUES ($1, $2, $3::text, CURRENT_TIMESTAMP, $4::text)
RETURNING id
`

type InsertRecordEventParams struct {
	RecordID  int
	EventType string
	Username  string
	Comments  sql.NullString
}

func (q *Queries) InsertRecordEvent(ctx context.Context, arg InsertRecordEventParams) (int, error) {
	row := q.db.QueryRowContext(ctx, insertRecordEvent,
		arg.RecordID,
		arg.EventType,
		arg.Username,
		arg.Comments,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const insertResult = `-- name: InsertResult :exec
INSERT INTO result (form_record_id, form_row_id, type, parameter, specification, spec_min, spec_nom, spec_max,
                    spec_units, pf_type, format, hide_formula, default_result, result, comment, pass_fail, updated_at)
VALUES ($1, $2, $3::int, $4::text,
        $5::text, $6::text, $7::text, $8::text,
        $9::text, $10::text, $11::text, $12::text,
        $13::text, $14::text, $15::text, $16::bool,
        CURRENT_TIMESTAMP)
`

type InsertResultParams struct {
	RecordID      int
	StepID        int
	Type          int
	Parameter     string
	Specification string
	SpecMin       string
	SpecNom       string
	SpecMax       string
	SpecUnits     string
	PfType        string
	Format        string
	HideFormula   string
	DefaultResult string
	Result        sql.NullString
	Comment       sql.NullString
	PassFail      sql.NullBool
}

// One result row materialized from a (baked) step definition; result / comment / pass_fail NULL for a fresh row.
func (q *Queries) InsertResult(ctx context.Context, arg InsertResultParams) error {
	_, err := q.db.ExecContext(ctx, insertResult,
		arg.RecordID,
		arg.StepID,
		arg.Type,
		arg.Parameter,
		arg.Specification,
		arg.SpecMin,
		arg.SpecNom,
		arg.SpecMax,
		arg.SpecUnits,
		arg.PfType,
		arg.Format,
		arg.HideFormula,
		arg.DefaultResult,
		arg.Result,
		arg.Comment,
		arg.PassFail,
	)
	return err
}

const insertStep = `-- name: InsertStep :one
INSERT INTO form_row (form_id, type, parameter, specification, spec_nom, spec_min, spec_max, spec_units, pf_type,
                      default_result, hide_formula, category, sheet_name, instrument_types, format, comment,
                      created_at, updated_at)
VALUES ($1, $2::int, $3::text, $4::text,
        $5::text, $6::text, $7::text, $8::text,
        $9::text, $10::text, $11::text,
        $12::text, $13::text, $14::text,
        $15::text, $16::text, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id
`

type InsertStepParams struct {
	FormID          int
	Type            int
	Parameter       string
	Specification   sql.NullString
	SpecNom         sql.NullString
	SpecMin         sql.NullString
	SpecMax         sql.NullString
	SpecUnits       sql.NullString
	PfType          sql.NullString
	DefaultResult   sql.NullString
	HideFormula     sql.NullString
	Category        sql.NullString
	SheetName       sql.NullString
	InstrumentTypes sql.NullString
	Format          sql.NullString
	Comment         sql.NullString
}

func (q *Queries) InsertStep(ctx context.Context, arg InsertStepParams) (int, error) {
	row := q.db.QueryRowContext(ctx, insertStep,
		arg.FormID,
		arg.Type,
		arg.Parameter,
		arg.Specification,
		arg.SpecNom,
		arg.SpecMin,
		arg.SpecMax,
		arg.SpecUnits,
		arg.PfType,
		arg.DefaultResult,
		arg.HideFormula,
		arg.Category,
		arg.SheetName,
		arg.InstrumentTypes,
		arg.Format,
		arg.Comment,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const isFormPart = `-- name: IsFormPart :one
SELECT EXISTS (SELECT 1 FROM part WHERE id = $1 AND category = 'FORM' AND is_active = TRUE)::bool
`

// Whether a part may own a new form: an active FORM-category part.
func (q *Queries) IsFormPart(ctx context.Context, id int) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFormPart, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listActiveForms = `-- name: ListActiveForms :many

SELECT f.id, f.part_number_id, f.is_locked, f.revision, pn.part_number,
       COALESCE(pn.description, '') AS description
FROM form f
JOIN part pn ON f.part_number_id = pn.id
WHERE pn.category = 'FORM' AND pn.is_active = TRUE AND f.is_active = TRUE
ORDER BY pn.part_number ASC
`

type ListActiveFormsRow struct {
	ID           int
	PartNumberID int
	IsLocked     bool
	Revision     int
	PartNumber   string
	Description  string
}

// ── Forms ────────────────────────────────────────────────────────────────────
// The records index: every active form whose part is an active FORM-category part.
func (q *Queries) ListActiveForms(ctx context.Context) ([]ListActiveFormsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveForms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveFormsRow
	for rows.Next() {
		var i ListActiveFormsRow
		if err := rows.Scan(
			&i.ID,
			&i.PartNumberID,
			&i.IsLocked,
			&i.Revision,
			&i.PartNumber,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveNamedQueries = `-- name: ListActiveNamedQueries :many

SELECT name, COALESCE(description, '') AS description, COALESCE(params, '') AS params, result_type
FROM named_queries
WHERE is_active = TRUE
ORDER BY name
`

type ListActiveNamedQueriesRow struct {
	Name        string
	Description string
	Params      string
	ResultType  string
}

// ── Named queries (#250) ─────────────────────────────────────────────────────
// The admin-authored SQL itself runs raw in arx_go's execQuery; only the named_queries table is here.
func (q *Queries) ListActiveNamedQueries(ctx context.Context) ([]ListActiveNamedQueriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveNamedQueries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveNamedQueriesRow
	for rows.Next() {
		var i ListActiveNamedQueriesRow
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.Params,
			&i.ResultType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBOMParts = `-- name: ListBOMParts :many
SELECT pn.id, pn.part_number, COALESCE(pn.description, '') AS description
FROM bom pl
JOIN part pn ON pl.component_part_id = pn.id
WHERE pl.parent_part_id = $1
ORDER BY pn.description
`

type ListBOMPartsRow struct {
	ID          int
	PartNumber  string
	Description string
}

// Components under a part in the BOM (the new-record subject picker).
func (q *Queries) ListBOMParts(ctx context.Context, parentPartID int) ([]ListBOMPartsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBOMParts, parentPartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBOMPartsRow
	for rows.Next() {
		var i ListBOMPartsRow
		if err := rows.Scan(&i.ID, &i.PartNumber, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailureModes = `-- name: ListFailureModes :many
SELECT COALESCE((SELECT r2.parameter FROM result r2
                 WHERE r2.form_row_id = res.form_row_id
                 ORDER BY r2.id DESC LIMIT 1), '')::text AS parameter,
       COALESCE(SUM(CASE WHEN res.pass_fail = FALSE THEN 1 ELSE 0 END), 0)::int AS failure_count,
       COUNT(res.pass_fail)::int AS total_tested
FROM result res
JOIN form_record trec ON res.form_record_id = trec.id
WHERE trec.form_id = $1 AND trec.is_active = TRUE AND res.pass_fail IS NOT NULL
  AND ($2::timestamp IS NULL OR trec.record_date >= $2::timestamp)
  AND ($3::date IS NULL OR trec.record_date < ($3::date + 1))
GROUP BY res.form_row_id
ORDER BY failure_count DESC, parameter ASC
`

type ListFailureModesParams struct {
	FormID   int
	FromDate sql.NullTime
	ToDate   *time.Time
}

type ListFailureModesRow struct {
	Parameter    string
	FailureCount int
	TotalTested  int
}

// Each step's failure count and tested count over the form's active records in the date range,
// most failures first. The label is the step's most recently written result-row parameter.
func (q *Queries) ListFailureModes(ctx context.Context, arg ListFailureModesParams) ([]ListFailureModesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFailureModes, arg.FormID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFailureModesRow
	for rows.Next() {
		var i ListFailureModesRow
		if err := rows.Scan(&i.Parameter, &i.FailureCount, &i.TotalTested); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormHistoryStamps = `-- name: ListFormHistoryStamps :many
SELECT changed_at, form_row_id
FROM form_row_history
WHERE form_row_id IN (SELECT id FROM form_row WHERE form_id = $1)
ORDER BY changed_at ASC
`

type ListFormHistoryStampsRow struct {
	ChangedAt time.Time
	FormRowID int
}

// Change timestamps of a form's steps, oldest first (the definition page's timeline dots).
func (q *Queries) ListFormHistoryStamps(ctx context.Context, formID int) ([]ListFormHistoryStampsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFormHistoryStamps, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormHistoryStampsRow
	for rows.Next() {
		var i ListFormHistoryStampsRow
		if err := rows.Scan(&i.ChangedAt, &i.FormRowID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormPartOptions = `-- name: ListFormPartOptions :many
SELECT id, part_number, COALESCE(description, '') AS description
FROM part
WHERE category = 'FORM' AND is_active = TRUE
  AND NOT EXISTS (SELECT 1 FROM form WHERE part_number_id = part.id AND is_active = TRUE)
ORDER BY part_number
`

type ListFormPartOptionsRow struct {
	ID          int
	PartNumber  string
	Description string
}

// FORM-category parts that don't already have an active form (new / duplicate form PN picker).
func (q *Queries) ListFormPartOptions(ctx context.Context) ([]ListFormPartOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFormPartOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormPartOptionsRow
	for rows.Next() {
		var i ListFormPartOptionsRow
		if err := rows.Scan(&i.ID, &i.PartNumber, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormRecords = `-- name: ListFormRecords :many
SELECT id, COALESCE(part_id, 0)::int AS part_id, COALESCE(serial_number, '') AS serial_number,
       COALESCE(subject_part_number, '') AS subject_part_number,
       COALESCE(subject_pn_description, '') AS subject_pn_description,
       record_date, COALESCE(record_type, '') AS record_type, is_locked, is_approved, form_revision
FROM form_record
WHERE form_id = $1 AND is_active = TRUE
ORDER BY (CASE WHEN serial_number ~ '^[0-9]+$' THEN CAST(serial_number AS INTEGER) END) DESC, record_date DESC
`

type ListFormRecordsRow struct {
	ID                   int
	PartID               int
	SerialNumber         string
	SubjectPartNumber    string
	SubjectPnDescription string
	RecordDate           sql.NullTime
	RecordType           string
	IsLocked             bool
	IsApproved           bool
	FormRevision         *int
}

// Active records of a form for the records table: numeric serials descending (a non-numeric
// serial sorts first), newest date first within a serial.
func (q *Queries) ListFormRecords(ctx context.Context, formID int) ([]ListFormRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFormRecords, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormRecordsRow
	for rows.Next() {
		var i ListFormRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.SerialNumber,
			&i.SubjectPartNumber,
			&i.SubjectPnDescription,
			&i.RecordDate,
			&i.RecordType,
			&i.IsLocked,
			&i.IsApproved,
			&i.FormRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormSteps = `-- name: ListFormSteps :many
SELECT id, form_id, COALESCE(parameter, '') AS parameter, COALESCE(specification, '') AS specification,
       COALESCE(default_result, '') AS default_result, COALESCE(hide_formula, '') AS hide_formula,
       COALESCE(type, 0)::int AS type, COALESCE(spec_min, '') AS spec_min, COALESCE(spec_max, '') AS spec_max,
       COALESCE(pf_type, '') AS pf_type, archived, archive_id, revision,
       COALESCE(category, '') AS category, COALESCE(sheet_name, '') AS sheet_name,
       COALESCE(spec_units, '') AS spec_units, COALESCE(spec_nom, '') AS spec_nom,
       COALESCE(instrument_types, '') AS instrument_types, COALESCE(format, '') AS format,
       COALESCE(comment, '') AS comment, created_at, updated_at
FROM form_row
WHERE form_id = $1
`

type ListFormStepsRow struct {
	ID              int
	FormID          int
	Parameter       string
	Specification   string
	DefaultResult   string
	HideFormula     string
	Type            int
	SpecMin         string
	SpecMax         string
	PfType          string
	Archived        bool
	ArchiveID       *int
	Revision        *int
	Category        string
	SheetName       string
	SpecUnits       string
	SpecNom         string
	InstrumentTypes string
	Format          string
	Comment         string
	CreatedAt       *time.Time
	UpdatedAt       *time.Time
}

// Every form_row of a form with all rendering fields (definition view, edit page, live fallback
// for un-materialized record rows). Order comes from form.test_order, not from this query.
func (q *Queries) ListFormSteps(ctx context.Context, formID int) ([]ListFormStepsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFormSteps, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormStepsRow
	for rows.Next() {
		var i ListFormStepsRow
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Parameter,
			&i.Specification,
			&i.DefaultResult,
			&i.HideFormula,
			&i.Type,
			&i.SpecMin,
			&i.SpecMax,
			&i.PfType,
			&i.Archived,
			&i.ArchiveID,
			&i.Revision,
			&i.Category,
			&i.SheetName,
			&i.SpecUnits,
			&i.SpecNom,
			&i.InstrumentTypes,
			&i.Format,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormStepsAt = `-- name: ListFormStepsAt :many
SELECT t.id,
       (CASE WHEN h.form_row_id IS NOT NULL THEN COALESCE(h.type, 0)            ELSE COALESCE(t.type, 0)            END)::int  AS type,
       (CASE WHEN h.form_row_id IS NOT NULL THEN COALESCE(h.parameter, '')      ELSE COALESCE(t.parameter, '')      END)::text AS parameter,
       (CASE WHEN h.form_row_id IS NOT NULL THEN COALESCE(h.spec_nom, '')       ELSE COALESCE(t.spec_nom, '')       END)::text AS spec_nom,
       (CASE WHEN h.form_row_id IS NOT NULL THEN COALESCE(h.spec_min, '')       ELSE COALESCE(t.spec_min, '')       END)::text AS spec_min,
       (CASE WHEN h.form_row_id IS NOT NULL THEN COALESCE(h.spec_max, '')       ELSE COALESCE(t.spec_max, '')       END)::text AS spec_max,
       (CASE WHEN h.form_row_id IS NOT NULL THEN COALESCE(h.spec_units, '')     ELSE COALESCE(t.spec_units, '')     END)::text AS spec_units,
       (CASE WHEN h.form_row_id IS NOT NULL THEN COALESCE(h.pf_type, '')        ELSE COALESCE(t.pf_type, '')        END)::text AS pf_type,
       (CASE WHEN h.form_row_id IS NOT NULL THEN COALESCE(h.default_result, '') ELSE COALESCE(t.default_result, '') END)::text AS default_result,
       (CASE WHEN h.form_row_id IS NOT NULL THEN COALESCE(h.hide_formula, '')   ELSE COALESCE(t.hide_formula, '')   END)::text AS hide_formula,
       (h.form_row_id IS NOT NULL)::bool AS changed
FROM form_row t
LEFT JOIN (
    SELECT form_row_id, type, parameter, spec_nom, spec_min, spec_max,
           spec_units, pf_type, default_result, hide_formula
    FROM form_row_history
    WHERE changed_at >= $1::timestamptz AND changed_at < $2::timestamptz
) h ON h.form_row_id = t.id
WHERE t.form_id = $3
`

type ListFormStepsAtParams struct {
	DayStart time.Time
	DayEnd   time.Time
	FormID   int
}

type ListFormStepsAtRow struct {
	ID            int
	Type          int
	Parameter     string
	SpecNom       string
	SpecMin       string
	SpecMax       string
	SpecUnits     string
	PfType        string
	DefaultResult string
	HideFormula   string
	Changed       bool
}

// A form's steps as they stood on one day: a step with history in [day_start, day_end) shows its
// pre-change values (changed = true), any other its current ones.
func (q *Queries) ListFormStepsAt(ctx context.Context, arg ListFormStepsAtParams) ([]ListFormStepsAtRow, error) {
	rows, err := q.db.QueryContext(ctx, listFormStepsAt, arg.DayStart, arg.DayEnd, arg.FormID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormStepsAtRow
	for rows.Next() {
		var i ListFormStepsAtRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Parameter,
			&i.SpecNom,
			&i.SpecMin,
			&i.SpecMax,
			&i.SpecUnits,
			&i.PfType,
			&i.DefaultResult,
			&i.HideFormula,
			&i.Changed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNamedQueries = `-- name: ListNamedQueries :many
SELECT id, name, COALESCE(description, '') AS description, sql, COALESCE(params, '') AS params, result_type,
       is_active, updated_at
FROM named_queries
ORDER BY name
`

type ListNamedQueriesRow struct {
	ID          int
	Name        string
	Description string
	Sql         string
	Params      string
	ResultType  string
	IsActive    bool
	UpdatedAt   *time.Time
}

func (q *Queries) ListNamedQueries(ctx context.Context) ([]ListNamedQueriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNamedQueries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNamedQueriesRow
	for rows.Next() {
		var i ListNamedQueriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Sql,
			&i.Params,
			&i.ResultType,
			&i.IsActive,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordEventResults = `-- name: ListRecordEventResults :many
SELECT rer.event_id, rer.form_row_id, COALESCE(rer.parameter, '') AS parameter,
       COALESCE(rer.specification, '') AS specification, COALESCE(rer.spec_units, '') AS spec_units,
       COALESCE(rer.result, '') AS result, rer.pass_fail, COALESCE(rer.comment, '') AS comment
FROM record_event_results rer
JOIN record_events re ON re.id = rer.event_id
WHERE re.form_record_id = $1
ORDER BY re.event_date ASC, re.id ASC, rer.id ASC
`

type ListRecordEventResultsRow struct {
	EventID       int
	FormRowID     int
	Parameter     string
	Specification string
	SpecUnits     string
	Result        string
	PassFail      sql.NullBool
	Comment       string
}

// The per-completion result snapshots of a record, in event order (the handler diffs them).
func (q *Queries) ListRecordEventResults(ctx context.Context, recordID int) ([]ListRecordEventResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecordEventResults, recordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordEventResultsRow
	for rows.Next() {
		var i ListRecordEventResultsRow
		if err := rows.Scan(
			&i.EventID,
			&i.FormRowID,
			&i.Parameter,
			&i.Specification,
			&i.SpecUnits,
			&i.Result,
			&i.PassFail,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordEvents = `-- name: ListRecordEvents :many
SELECT id, form_record_id, event_type, COALESCE(username, '') AS username, event_date,
       COALESCE(comments, '') AS comments
FROM record_events
WHERE form_record_id = $1
ORDER BY event_date ASC, id ASC
`

type ListRecordEventsRow struct {
	ID           int
	FormRecordID int
	EventType    string
	Username     string
	EventDate    time.Time
	Comments     string
}

// Lifecycle audit trail (complete / approve / unlock), oldest first.
func (q *Queries) ListRecordEvents(ctx context.Context, recordID int) ([]ListRecordEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecordEvents, recordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordEventsRow
	for rows.Next() {
		var i ListRecordEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.FormRecordID,
			&i.EventType,
			&i.Username,
			&i.EventDate,
			&i.Comments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordResults = `-- name: ListRecordResults :many
SELECT id, form_record_id, form_row_id,
       COALESCE(parameter, '') AS parameter, COALESCE(specification, '') AS specification,
       COALESCE(result, '') AS result, pass_fail, COALESCE(comment, '') AS comment,
       COALESCE(spec_min, '') AS spec_min, COALESCE(spec_nom, '') AS spec_nom, COALESCE(spec_max, '') AS spec_max,
       COALESCE(spec_units, '') AS spec_units, COALESCE(pf_type, '') AS pf_type, COALESCE(format, '') AS format,
       COALESCE(type, 0)::int AS type, COALESCE(hide_formula, '') AS hide_formula,
       COALESCE(default_result, '') AS default_result, updated_at
FROM result
WHERE form_record_id = $1
`

type ListRecordResultsRow struct {
	ID            int
	FormRecordID  int
	FormRowID     int
	Parameter     string
	Specification string
	Result        string
	PassFail      sql.NullBool
	Comment       string
	SpecMin       string
	SpecNom       string
	SpecMax       string
	SpecUnits     string
	PfType        string
	Format        string
	Type          int
	HideFormula   string
	DefaultResult string
	UpdatedAt     *time.Time
}

// A record's materialized result rows (the frozen snapshot of each step).
func (q *Queries) ListRecordResults(ctx context.Context, recordID int) ([]ListRecordResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecordResults, recordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordResultsRow
	for rows.Next() {
		var i ListRecordResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.FormRecordID,
			&i.FormRowID,
			&i.Parameter,
			&i.Specification,
			&i.Result,
			&i.PassFail,
			&i.Comment,
			&i.SpecMin,
			&i.SpecNom,
			&i.SpecMax,
			&i.SpecUnits,
			&i.PfType,
			&i.Format,
			&i.Type,
			&i.HideFormula,
			&i.DefaultResult,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordTypes = `-- name: ListRecordTypes :many
SELECT DISTINCT COALESCE(record_type, '')::text AS record_type
FROM form_record
WHERE is_active = TRUE AND record_type <> ''
  AND ($1::int IS NULL OR form_id = $1::int)
  AND ($2::int IS NULL OR part_id = $2::int)
  AND ($3::int IS NULL OR lot_id = $3::int)
  AND ($4::int IS NULL OR unit_id = $4::int)
ORDER BY 1
`

type ListRecordTypesParams struct {
	FormID *int
	PartID *int
	LotID  *int
	UnitID *int
}

// Distinct non-empty record types of the active records in one scope (filter datalists); exactly
// one of the four ids is non-NULL.
func (q *Queries) ListRecordTypes(ctx context.Context, arg ListRecordTypesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRecordTypes,
		arg.FormID,
		arg.PartID,
		arg.LotID,
		arg.UnitID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var record_type string
		if err := rows.Scan(&record_type); err != nil {
			return nil, err
		}
		items = append(items, record_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopedRecords = `-- name: ListScopedRecords :many
SELECT r.id, COALESCE(r.part_id, 0)::int AS part_id, COALESCE(r.serial_number, '') AS serial_number,
       COALESCE(r.subject_part_number, '') AS subject_part_number,
       COALESCE(r.subject_pn_description, '') AS subject_pn_description,
       r.record_date, COALESCE(r.record_type, '') AS record_type, r.is_locked, r.is_approved,
       r.form_revision, r.form_id, fp.part_number AS form_part_number,
       COALESCE(fp.description, '') AS form_description
FROM form_record r
JOIN form f ON f.id = r.form_id
JOIN part fp ON fp.id = f.part_number_id
WHERE r.is_active = TRUE
  AND ($1::int IS NULL OR r.part_id = $1::int)
  AND ($2::int IS NULL OR r.lot_id = $2::int)
  AND ($3::int IS NULL OR r.unit_id = $3::int)
ORDER BY r.record_date DESC
`

type ListScopedRecordsParams struct {
	PartID *int
	LotID  *int
	UnitID *int
}

type ListScopedRecordsRow struct {
	ID                   int
	PartID               int
	SerialNumber         string
	SubjectPartNumber    string
	SubjectPnDescription string
	RecordDate           sql.NullTime
	RecordType           string
	IsLocked             bool
	IsApproved           bool
	FormRevision         *int
	FormID               int
	FormPartNumber       string
	FormDescription      string
}

// Active records across forms for the Part/Lot/Unit records tables: exactly one of the three ids is
// non-NULL (the service picks it from a fixed scope), the others don't filter.
func (q *Queries) ListScopedRecords(ctx context.Context, arg ListScopedRecordsParams) ([]ListScopedRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listScopedRecords, arg.PartID, arg.LotID, arg.UnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScopedRecordsRow
	for rows.Next() {
		var i ListScopedRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.PartID,
			&i.SerialNumber,
			&i.SubjectPartNumber,
			&i.SubjectPnDescription,
			&i.RecordDate,
			&i.RecordType,
			&i.IsLocked,
			&i.IsApproved,
			&i.FormRevision,
			&i.FormID,
			&i.FormPartNumber,
			&i.FormDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceForms = `-- name: ListSourceForms :many
SELECT f.id, pn.part_number, COALESCE(pn.description, '') AS description
FROM form f
JOIN part pn ON f.part_number_id = pn.id
WHERE f.is_active = TRUE
ORDER BY pn.part_number
`

type ListSourceFormsRow struct {
	ID          int
	PartNumber  string
	Description string
}

// Active forms to copy steps from (new-form page).
func (q *Queries) ListSourceForms(ctx context.Context) ([]ListSourceFormsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourceForms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceFormsRow
	for rows.Next() {
		var i ListSourceFormsRow
		if err := rows.Scan(&i.ID, &i.PartNumber, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepReportRows = `-- name: ListStepReportRows :many
SELECT trec.id, COALESCE(trec.serial_number, '') AS serial_number,
       COALESCE(trec.subject_part_number, '') AS subject_part_number,
       COALESCE(trec.part_id, 0)::int AS part_id, trec.record_date,
       COALESCE(res.result, '') AS result, res.pass_fail, COALESCE(res.comment, '') AS comment,
       res.updated_at
FROM result res
JOIN form_record trec ON res.form_record_id = trec.id
WHERE res.form_row_id = $1 AND trec.form_id = $2 AND trec.is_active = TRUE
ORDER BY (CASE WHEN trec.serial_number ~ '^[0-9]+$' THEN CAST(trec.serial_number AS INTEGER) END) DESC, trec.record_date DESC
`

type ListStepReportRowsParams struct {
	StepID int
	FormID int
}

type ListStepReportRowsRow struct {
	ID                int
	SerialNumber      string
	SubjectPartNumber string
	PartID            int
	RecordDate        sql.NullTime
	Result            string
	PassFail          sql.NullBool
	Comment           string
	UpdatedAt         *time.Time
}

// Every active record's recorded result for one step, in the records-table order.
func (q *Queries) ListStepReportRows(ctx context.Context, arg ListStepReportRowsParams) ([]ListStepReportRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStepReportRows, arg.StepID, arg.FormID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStepReportRowsRow
	for rows.Next() {
		var i ListStepReportRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumber,
			&i.SubjectPartNumber,
			&i.PartID,
			&i.RecordDate,
			&i.Result,
			&i.PassFail,
			&i.Comment,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listYieldRecords = `-- name: ListYieldRecords :many

SELECT trec.record_date, COALESCE(BOOL_OR(res.pass_fail = FALSE), FALSE)::bool AS any_fail
FROM form_record trec
LEFT JOIN result res ON res.form_record_id = trec.id
WHERE trec.form_id = $1 AND trec.is_active = TRUE
  AND ($2::timestamp IS NULL OR trec.record_date >= $2::timestamp)
  AND ($3::date IS NULL OR trec.record_date < ($3::date + 1))
GROUP BY trec.id, trec.record_date
`

type ListYieldRecordsParams struct {
	FormID   int
	FromDate sql.NullTime
	ToDate   *time.Time
}

type ListYieldRecordsRow struct {
	RecordDate sql.NullTime
	AnyFail    bool
}

// ── Reports ──────────────────────────────────────────────────────────────────
// One row per active record of the form in the date range: its date and whether any result failed.
// from_date / to_date are optional; to_date is inclusive of the whole day.
func (q *Queries) ListYieldRecords(ctx context.Context, arg ListYieldRecordsParams) ([]ListYieldRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listYieldRecords, arg.FormID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListYieldRecordsRow
	for rows.Next() {
		var i ListYieldRecordsRow
		if err := rows.Scan(&i.RecordDate, &i.AnyFail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockForm = `-- name: LockForm :execrows
UPDATE form SET is_locked = TRUE, revision = revision + 1 WHERE id = $1 AND is_locked = FALSE
`

// Release: lock and bump the revision (#260).
func (q *Queries) LockForm(ctx context.Context, id int) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockForm, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const lockSerialAllocation = `-- name: LockSerialAllocation :exec

SELECT pg_advisory_xact_lock($1::int, $2::int)
`

type LockSerialAllocationParams struct {
	Namespace int
	FormID    int
}

// ── Record writes ────────────────────────────────────────────────────────────
// Serializes auto serial allocation for one form until the tx ends (#369, #33).
func (q *Queries) LockSerialAllocation(ctx context.Context, arg LockSerialAllocationParams) error {
	_, err := q.db.ExecContext(ctx, lockSerialAllocation, arg.Namespace, arg.FormID)
	return err
}

const nextFormSerial = `-- name: NextFormSerial :one
SELECT COALESCE(MAX(CASE WHEN serial_number ~ '^[0-9]+$' THEN CAST(serial_number AS INTEGER) END) + 1, 1)::int AS next_serial
FROM form_record
WHERE form_id = $1
`

// Suggested next serial: the largest all-digit serial of the form (any state) + 1, or 1.
func (q *Queries) NextFormSerial(ctx context.Context, formID int) (int, error) {
	row := q.db.QueryRowContext(ctx, nextFormSerial, formID)
	var next_serial int
	err := row.Scan(&next_serial)
	return next_serial, err
}

const refreshResult = `-- name: RefreshResult :exec
UPDATE result
SET type = $1::int, parameter = $2::text, specification = $3::text,
    spec_min = $4::text, spec_nom = $5::text, spec_max = $6::text,
    spec_units = $7::text, pf_type = $8::text, format = $9::text,
    hide_formula = $10::text, default_result = $11::text,
    pass_fail = $12::bool, updated_at = CURRENT_TIMESTAMP
WHERE id = $13
`

type RefreshResultParams struct {
	Type          int
	Parameter     string
	Specification string
	SpecMin       string
	SpecNom       string
	SpecMax       string
	SpecUnits     string
	PfType        string
	Format        string
	HideFormula   string
	DefaultResult string
	PassFail      sql.NullBool
	ID            int
}

// Re-pulls a step's live definition into an existing snapshot row (resync) with a recomputed pass_fail.
func (q *Queries) RefreshResult(ctx context.Context, arg RefreshResultParams) error {
	_, err := q.db.ExecContext(ctx, refreshResult,
		arg.Type,
		arg.Parameter,
		arg.Specification,
		arg.SpecMin,
		arg.SpecNom,
		arg.SpecMax,
		arg.SpecUnits,
		arg.PfType,
		arg.Format,
		arg.HideFormula,
		arg.DefaultResult,
		arg.PassFail,
		arg.ID,
	)
	return err
}

const resyncRecordHeader = `-- name: ResyncRecordHeader :exec
UPDATE form_record
SET test_order = $1::text, form_revision = $2::int, updated_at = CURRENT_TIMESTAMP
WHERE id = $3
`

type ResyncRecordHeaderParams struct {
	TestOrder    string
	FormRevision int
	ID           int
}

func (q *Queries) ResyncRecordHeader(ctx context.Context, arg ResyncRecordHeaderParams) error {
	_, err := q.db.ExecContext(ctx, resyncRecordHeader, arg.TestOrder, arg.FormRevision, arg.ID)
	return err
}

const setAuditUser = `-- name: SetAuditUser :exec

SELECT set_config('arx.username', $1::text, true)
`

// ── Form writes ──────────────────────────────────────────────────────────────
// Transaction-local acting username that trg_form_row_history reads via current_setting('arx.username').
func (q *Queries) SetAuditUser(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, setAuditUser, username)
	return err
}

const setFormTestOrder = `-- name: SetFormTestOrder :exec
UPDATE form SET test_order = $1::text WHERE id = $2
`

type SetFormTestOrderParams struct {
	TestOrder string
	ID        int
}

func (q *Queries) SetFormTestOrder(ctx context.Context, arg SetFormTestOrderParams) error {
	_, err := q.db.ExecContext(ctx, setFormTestOrder, arg.TestOrder, arg.ID)
	return err
}

const setFormTypes = `-- name: SetFormTypes :exec
UPDATE form SET record_types = $1::text, instrument_types = $2::text
WHERE id = $3
`

type SetFormTypesParams struct {
	RecordTypes     sql.NullString
	InstrumentTypes sql.NullString
	ID              int
}

func (q *Queries) SetFormTypes(ctx context.Context, arg SetFormTypesParams) error {
	_, err := q.db.ExecContext(ctx, setFormTypes, arg.RecordTypes, arg.InstrumentTypes, arg.ID)
	return err
}

const setStepArchived = `-- name: SetStepArchived :exec
UPDATE form_row SET archived = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2 AND form_id = $3
`

type SetStepArchivedParams struct {
	Archived bool
	ID       int
	FormID   int
}

func (q *Queries) SetStepArchived(ctx context.Context, arg SetStepArchivedParams) error {
	_, err := q.db.ExecContext(ctx, setStepArchived, arg.Archived, arg.ID, arg.FormID)
	return err
}

const unlockForm = `-- name: UnlockForm :execrows
UPDATE form SET is_locked = FALSE WHERE id = $1 AND is_locked = TRUE
`

func (q *Queries) UnlockForm(ctx context.Context, id int) (int64, error) {
	result, err := q.db.ExecContext(ctx, unlockForm, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const unlockRecord = `-- name: UnlockRecord :execrows
UPDATE form_record SET is_locked = FALSE, is_approved = FALSE, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND is_locked = TRUE AND (is_approved = FALSE OR $2::bool)
`

type UnlockRecordParams struct {
	ID                int
	MayUnlockApproved bool
}

// Locked → WIP, clearing approval. An approved record unlocks only for a reviewer (#249); the check sits in
// the WHERE so an approval that lands while the unlock waits on the row lock still wins.
func (q *Queries) UnlockRecord(ctx context.Context, arg UnlockRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unlockRecord, arg.ID, arg.MayUnlockApproved)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateNamedQuery = `-- name: UpdateNamedQuery :execrows
UPDATE named_queries
SET name = $1, description = $2::text, sql = $3,
    params = $4::text, result_type = $5, is_active = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $7
`

type UpdateNamedQueryParams struct {
	Name        string
	Description string
	Sql         string
	Params      string
	ResultType  string
	IsActive    bool
	ID          int
}

func (q *Queries) UpdateNamedQuery(ctx context.Context, arg UpdateNamedQueryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateNamedQuery,
		arg.Name,
		arg.Description,
		arg.Sql,
		arg.Params,
		arg.ResultType,
		arg.IsActive,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRecordAfterSave = `-- name: UpdateRecordAfterSave :exec
UPDATE form_record
SET record_date = COALESCE($1::timestamp, record_date), record_type = $2::text,
    notes = $3::text, instrument_type = $4::text,
    lot_id = $5::int, build_id = $6::int, unit_id = $7::int,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $8
`

type UpdateRecordAfterSaveParams struct {
	RecordDate     sql.NullTime
	RecordType     string
	Notes          sql.NullString
	InstrumentType string
	LotID          *int
	BuildID        *int
	UnitID         *int
	ID             int
}

// The record-level fields of a results save; a NULL record_date keeps the stored one.
func (q *Queries) UpdateRecordAfterSave(ctx context.Context, arg UpdateRecordAfterSaveParams) error {
	_, err := q.db.ExecContext(ctx, updateRecordAfterSave,
		arg.RecordDate,
		arg.RecordType,
		arg.Notes,
		arg.InstrumentType,
		arg.LotID,
		arg.BuildID,
		arg.UnitID,
		arg.ID,
	)
	return err
}

const updateResultValue = `-- name: UpdateResultValue :exec
UPDATE result
SET result = $1::text, comment = $2::text, pass_fail = $3::bool,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $4
`

type UpdateResultValueParams struct {
	Result   string
	Comment  string
	PassFail sql.NullBool
	ID       int
}

func (q *Queries) UpdateResultValue(ctx context.Context, arg UpdateResultValueParams) error {
	_, err := q.db.ExecContext(ctx, updateResultValue,
		arg.Result,
		arg.Comment,
		arg.PassFail,
		arg.ID,
	)
	return err
}

const updateStep = `-- name: UpdateStep :exec
UPDATE form_row
SET type = $1::int, parameter = $2::text, specification = $3::text,
    spec_nom = $4::text, spec_min = $5::text, spec_max = $6::text,
    spec_units = $7::text, pf_type = $8::text,
    default_result = $9::text, hide_formula = $10::text,
    category = $11::text, sheet_name = $12::text,
    instrument_types = $13::text, format = $14::text,
    comment = $15::text, updated_at = CURRENT_TIMESTAMP
WHERE id = $16 AND form_id = $17
`

type UpdateStepParams struct {
	Type            int
	Parameter       string
	Specification   string
	SpecNom         sql.NullString
	SpecMin         sql.NullString
	SpecMax         sql.NullString
	SpecUnits       sql.NullString
	PfType          sql.NullString
	DefaultResult   sql.NullString
	HideFormula     sql.NullString
	Category        sql.NullString
	SheetName       sql.NullString
	InstrumentTypes sql.NullString
	Format          sql.NullString
	Comment         sql.NullString
	ID              int
	FormID          int
}

func (q *Queries) UpdateStep(ctx context.Context, arg UpdateStepParams) error {
	_, err := q.db.ExecContext(ctx, updateStep,
		arg.Type,
		arg.Parameter,
		arg.Specification,
		arg.SpecNom,
		arg.SpecMin,
		arg.SpecMax,
		arg.SpecUnits,
		arg.PfType,
		arg.DefaultResult,
		arg.HideFormula,
		arg.Category,
		arg.SheetName,
		arg.InstrumentTypes,
		arg.Format,
		arg.Comment,
		arg.ID,
		arg.FormID,
	)
	return err
}
