// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package dbq

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const countOpenPOs = `-- name: CountOpenPOs :one


SELECT COUNT(*)::int FROM purchase_order WHERE status = 'open'
`

// Reports domain (#190, #246, #225): the Reports dashboard/report queries and the Settings ->
// Utilities data-integrity checks. sqlc generates internal/dbq/reports.sql.go from this file;
// the service is reports.go. Read-only throughout.
// ── Dashboard cards ────────────────────────────────────────────────────────────
func (q *Queries) CountOpenPOs(ctx context.Context) (int, error) {
	row := q.db.QueryRowContext(ctx, countOpenPOs)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const countPOsReceivedThisMonth = `-- name: CountPOsReceivedThisMonth :one
SELECT COUNT(DISTINCT po_id)::int FROM po_line
WHERE date_received >= date_trunc('month', $1::date)::date
`

func (q *Queries) CountPOsReceivedThisMonth(ctx context.Context, today time.Time) (int, error) {
	row := q.db.QueryRowContext(ctx, countPOsReceivedThisMonth, today)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const listActiveFormOptions = `-- name: ListActiveFormOptions :many
SELECT f.id, pn.part_number, COALESCE(pn.description, '') AS description
FROM form f
JOIN part pn ON f.part_number_id = pn.id
WHERE pn.category = 'FORM' AND pn.is_active = TRUE AND f.is_active = TRUE
ORDER BY pn.part_number ASC
`

type ListActiveFormOptionsRow struct {
	ID          int
	PartNumber  string
	Description string
}

func (q *Queries) ListActiveFormOptions(ctx context.Context) ([]ListActiveFormOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveFormOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveFormOptionsRow
	for rows.Next() {
		var i ListActiveFormOptionsRow
		if err := rows.Scan(&i.ID, &i.PartNumber, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBelowReorderParts = `-- name: ListBelowReorderParts :many
SELECT id AS part_id, part_number, stock_on_hand::numeric AS stock_on_hand, reorder_min::numeric AS reorder_min
FROM part
WHERE reorder_min IS NOT NULL AND stock_on_hand < reorder_min
ORDER BY (stock_on_hand - reorder_min) ASC LIMIT $1::int
`

type ListBelowReorderPartsRow struct {
	PartID      int
	PartNumber  string
	StockOnHand decimal.Decimal
	ReorderMin  decimal.Decimal
}

func (q *Queries) ListBelowReorderParts(ctx context.Context, rowLimit int) ([]ListBelowReorderPartsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBelowReorderParts, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBelowReorderPartsRow
	for rows.Next() {
		var i ListBelowReorderPartsRow
		if err := rows.Scan(
			&i.PartID,
			&i.PartNumber,
			&i.StockOnHand,
			&i.ReorderMin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompaniesWithDeletedPrimary = `-- name: ListCompaniesWithDeletedPrimary :many
SELECT c.id, c.name AS label
FROM company c JOIN company_attachment a ON a.supplier_attachment_id = c.primary_attachment_id
WHERE c.primary_attachment_id > 0 AND a.is_active = FALSE
`

type ListCompaniesWithDeletedPrimaryRow struct {
	ID    int
	Label string
}

func (q *Queries) ListCompaniesWithDeletedPrimary(ctx context.Context) ([]ListCompaniesWithDeletedPrimaryRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompaniesWithDeletedPrimary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompaniesWithDeletedPrimaryRow
	for rows.Next() {
		var i ListCompaniesWithDeletedPrimaryRow
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyAttachmentLinks = `-- name: ListCompanyAttachmentLinks :many
SELECT a.file_path AS link, c.id, c.name AS label
FROM company_attachment a JOIN company c ON a.supplier_id = c.id
WHERE a.is_active = TRUE
`

type ListCompanyAttachmentLinksRow struct {
	Link  string
	ID    int
	Label string
}

func (q *Queries) ListCompanyAttachmentLinks(ctx context.Context) ([]ListCompanyAttachmentLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompanyAttachmentLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompanyAttachmentLinksRow
	for rows.Next() {
		var i ListCompanyAttachmentLinksRow
		if err := rows.Scan(&i.Link, &i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanDefaultSuppliers = `-- name: ListOrphanDefaultSuppliers :many
SELECT p.id, p.part_number, p.default_supplier_id::int AS value
FROM part p
WHERE p.default_supplier_id > 0
  AND NOT EXISTS (SELECT 1 FROM company t WHERE t.id = p.default_supplier_id)
`

type ListOrphanDefaultSuppliersRow struct {
	ID         int
	PartNumber string
	Value      int
}

// The three orphan checks are enforced FKs today (#735), so they return nothing on a healthy schema.
func (q *Queries) ListOrphanDefaultSuppliers(ctx context.Context) ([]ListOrphanDefaultSuppliersRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrphanDefaultSuppliers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphanDefaultSuppliersRow
	for rows.Next() {
		var i ListOrphanDefaultSuppliersRow
		if err := rows.Scan(&i.ID, &i.PartNumber, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanPrices = `-- name: ListOrphanPrices :many
SELECT p.id, p.part_number, p.price_id::int AS value
FROM part p
WHERE p.price_id > 0
  AND NOT EXISTS (SELECT 1 FROM price t WHERE t.id = p.price_id)
`

type ListOrphanPricesRow struct {
	ID         int
	PartNumber string
	Value      int
}

func (q *Queries) ListOrphanPrices(ctx context.Context) ([]ListOrphanPricesRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrphanPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphanPricesRow
	for rows.Next() {
		var i ListOrphanPricesRow
		if err := rows.Scan(&i.ID, &i.PartNumber, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanPrimaryAttachments = `-- name: ListOrphanPrimaryAttachments :many
SELECT p.id, p.part_number, p.primary_attachment_id::int AS value
FROM part p
WHERE p.primary_attachment_id > 0
  AND NOT EXISTS (SELECT 1 FROM part_attachment t WHERE t.id = p.primary_attachment_id)
`

type ListOrphanPrimaryAttachmentsRow struct {
	ID         int
	PartNumber string
	Value      int
}

func (q *Queries) ListOrphanPrimaryAttachments(ctx context.Context) ([]ListOrphanPrimaryAttachmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrphanPrimaryAttachments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphanPrimaryAttachmentsRow
	for rows.Next() {
		var i ListOrphanPrimaryAttachmentsRow
		if err := rows.Scan(&i.ID, &i.PartNumber, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPOActiveStates = `-- name: ListPOActiveStates :many
SELECT id, number, COALESCE(status, '') AS status, COALESCE(is_active, FALSE) AS is_active
FROM purchase_order
`

type ListPOActiveStatesRow struct {
	ID       int
	Number   string
	Status   string
	IsActive bool
}

// status and is_active are nullable on legacy rows: NULL reads as ” / FALSE rather than
// aborting the whole check.
func (q *Queries) ListPOActiveStates(ctx context.Context) ([]ListPOActiveStatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPOActiveStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPOActiveStatesRow
	for rows.Next() {
		var i ListPOActiveStatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartAttachmentLinks = `-- name: ListPartAttachmentLinks :many

SELECT COALESCE(f.file_name, '') AS link, p.id, p.part_number AS label
FROM part_attachment f JOIN part p ON f.part_id = p.id
WHERE f.is_active = TRUE
`

type ListPartAttachmentLinksRow struct {
	Link  string
	ID    int
	Label string
}

// ── Utilities (Settings -> Utilities data-integrity checks) ─────────────────────
func (q *Queries) ListPartAttachmentLinks(ctx context.Context) ([]ListPartAttachmentLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listPartAttachmentLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartAttachmentLinksRow
	for rows.Next() {
		var i ListPartAttachmentLinksRow
		if err := rows.Scan(&i.Link, &i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartsMissingDefaultSupplier = `-- name: ListPartsMissingDefaultSupplier :many
SELECT part_number, COALESCE(description, '') AS description, COALESCE(category, '') AS category
FROM part
WHERE is_active = TRUE AND category = 'BUY' AND default_supplier_id IS NULL
ORDER BY part_number ASC
`

type ListPartsMissingDefaultSupplierRow struct {
	PartNumber  string
	Description string
	Category    string
}

func (q *Queries) ListPartsMissingDefaultSupplier(ctx context.Context) ([]ListPartsMissingDefaultSupplierRow, error) {
	rows, err := q.db.QueryContext(ctx, listPartsMissingDefaultSupplier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartsMissingDefaultSupplierRow
	for rows.Next() {
		var i ListPartsMissingDefaultSupplierRow
		if err := rows.Scan(&i.PartNumber, &i.Description, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartsNoAttachments = `-- name: ListPartsNoAttachments :many

SELECT part_number, COALESCE(description, '') AS description, COALESCE(category, '') AS category
FROM part
WHERE is_active = TRUE AND category IN ('BUY','ASM','DWG') AND attachment_count = 0
ORDER BY part_number ASC
`

type ListPartsNoAttachmentsRow struct {
	PartNumber  string
	Description string
	Category    string
}

// ── Data-quality gaps ──────────────────────────────────────────────────────────
// part.attachment_count is trigger-maintained, so it is read directly.
func (q *Queries) ListPartsNoAttachments(ctx context.Context) ([]ListPartsNoAttachmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPartsNoAttachments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartsNoAttachmentsRow
	for rows.Next() {
		var i ListPartsNoAttachmentsRow
		if err := rows.Scan(&i.PartNumber, &i.Description, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartsStaleRollup = `-- name: ListPartsStaleRollup :many
SELECT part_number, COALESCE(description, '') AS description, COALESCE(category, '') AS category
FROM part
WHERE is_active = TRUE AND (last_rollup_cost IS NULL OR last_rollup_at IS NULL)
ORDER BY part_number ASC
`

type ListPartsStaleRollupRow struct {
	PartNumber  string
	Description string
	Category    string
}

// Never rolled up: NULL-only, no age threshold.
func (q *Queries) ListPartsStaleRollup(ctx context.Context) ([]ListPartsStaleRollupRow, error) {
	rows, err := q.db.QueryContext(ctx, listPartsStaleRollup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartsStaleRollupRow
	for rows.Next() {
		var i ListPartsStaleRollupRow
		if err := rows.Scan(&i.PartNumber, &i.Description, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartsWithDeletedPrimary = `-- name: ListPartsWithDeletedPrimary :many
SELECT p.id, p.part_number AS label
FROM part p JOIN part_attachment f ON f.id = p.primary_attachment_id
WHERE p.primary_attachment_id > 0 AND f.is_active = FALSE
`

type ListPartsWithDeletedPrimaryRow struct {
	ID    int
	Label string
}

func (q *Queries) ListPartsWithDeletedPrimary(ctx context.Context) ([]ListPartsWithDeletedPrimaryRow, error) {
	rows, err := q.db.QueryContext(ctx, listPartsWithDeletedPrimary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartsWithDeletedPrimaryRow
	for rows.Next() {
		var i ListPartsWithDeletedPrimaryRow
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovalPOs = `-- name: ListPendingApprovalPOs :many
SELECT po.number, COALESCE(h.changed_at, 'epoch'::timestamptz)::timestamptz AS submitted_at,
       (h.changed_at IS NOT NULL)::boolean AS has_submitted
FROM purchase_order po
LEFT JOIN LATERAL (SELECT x.changed_at FROM purchase_order_history x
                   WHERE x.po_id = po.id AND x.event_type = 'approval' AND x.action = 'submitted'
                   ORDER BY x.changed_at DESC LIMIT 1) h ON TRUE
WHERE po.approval_status = 'pending'
ORDER BY h.changed_at ASC LIMIT $1::int
`

type ListPendingApprovalPOsRow struct {
	Number       string
	SubmittedAt  time.Time
	HasSubmitted bool
}

// submitted_at is the PO's latest 'submitted' approval event; has_submitted is false (and
// submitted_at the epoch) when there is none. sqlc can't type a nullable aggregate/lateral column.
func (q *Queries) ListPendingApprovalPOs(ctx context.Context, rowLimit int) ([]ListPendingApprovalPOsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingApprovalPOs, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingApprovalPOsRow
	for rows.Next() {
		var i ListPendingApprovalPOsRow
		if err := rows.Scan(&i.Number, &i.SubmittedAt, &i.HasSubmitted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentModifiedParts = `-- name: ListRecentModifiedParts :many
SELECT id, part_number, COALESCE(description, '') AS description, modified_date
FROM part WHERE modified_date IS NOT NULL ORDER BY modified_date DESC LIMIT $1::int
`

type ListRecentModifiedPartsRow struct {
	ID           int
	PartNumber   string
	Description  string
	ModifiedDate *time.Time
}

func (q *Queries) ListRecentModifiedParts(ctx context.Context, rowLimit int) ([]ListRecentModifiedPartsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentModifiedParts, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentModifiedPartsRow
	for rows.Next() {
		var i ListRecentModifiedPartsRow
		if err := rows.Scan(
			&i.ID,
			&i.PartNumber,
			&i.Description,
			&i.ModifiedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPOEvents = `-- name: ListRecentPOEvents :many
SELECT h.po_id, po.number, h.event_type, COALESCE(h.to_status, '') AS to_status,
       COALESCE(h.action, '') AS action, h.changed_at
FROM purchase_order_history h JOIN purchase_order po ON h.po_id = po.id
ORDER BY h.changed_at DESC LIMIT $1::int
`

type ListRecentPOEventsRow struct {
	PoID      int
	Number    string
	EventType string
	ToStatus  string
	Action    string
	ChangedAt time.Time
}

func (q *Queries) ListRecentPOEvents(ctx context.Context, rowLimit int) ([]ListRecentPOEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPOEvents, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentPOEventsRow
	for rows.Next() {
		var i ListRecentPOEventsRow
		if err := rows.Scan(
			&i.PoID,
			&i.Number,
			&i.EventType,
			&i.ToStatus,
			&i.Action,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordFailFlags = `-- name: ListRecordFailFlags :many
SELECT trec.form_id, pn.part_number,
       MAX(CASE WHEN res.pass_fail = FALSE THEN 1 ELSE 0 END)::int AS any_fail
FROM form_record trec
JOIN form f ON trec.form_id = f.id
JOIN part pn ON f.part_number_id = pn.id
LEFT JOIN result res ON res.form_record_id = trec.id
WHERE trec.is_active = TRUE
GROUP BY trec.id, trec.form_id, pn.part_number
`

type ListRecordFailFlagsRow struct {
	FormID     int
	PartNumber string
	AnyFail    int
}

// One row per active record: 1 when any of its results failed. The per-form yield is tallied in Go.
func (q *Queries) ListRecordFailFlags(ctx context.Context) ([]ListRecordFailFlagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecordFailFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordFailFlagsRow
	for rows.Next() {
		var i ListRecordFailFlagsRow
		if err := rows.Scan(&i.FormID, &i.PartNumber, &i.AnyFail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleWIPRecords = `-- name: ListStaleWIPRecords :many
SELECT trec.id, trec.form_id, pn.part_number, trec.created_at
FROM form_record trec
JOIN form f ON trec.form_id = f.id
JOIN part pn ON f.part_number_id = pn.id
WHERE trec.is_active = TRUE AND trec.is_locked = FALSE
  AND trec.created_at <= CURRENT_TIMESTAMP - make_interval(days => $1::int)
ORDER BY trec.created_at ASC LIMIT $2::int
`

type ListStaleWIPRecordsParams struct {
	StaleDays int
	RowLimit  int
}

type ListStaleWIPRecordsRow struct {
	ID         int
	FormID     int
	PartNumber string
	CreatedAt  *time.Time
}

// Unlocked records at least stale_days old, oldest first.
func (q *Queries) ListStaleWIPRecords(ctx context.Context, arg ListStaleWIPRecordsParams) ([]ListStaleWIPRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStaleWIPRecords, arg.StaleDays, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleWIPRecordsRow
	for rows.Next() {
		var i ListStaleWIPRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.PartNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopFailureModes = `-- name: ListTopFailureModes :many
SELECT f.id AS form_id, pn.part_number,
       COALESCE((SELECT r2.parameter FROM result r2
                 WHERE r2.form_row_id = res.form_row_id
                 ORDER BY r2.id DESC LIMIT 1), '')::text AS parameter,
       SUM(CASE WHEN res.pass_fail = FALSE THEN 1 ELSE 0 END)::int AS failure_count
FROM result res
JOIN form_record trec ON res.form_record_id = trec.id
JOIN form f ON trec.form_id = f.id
JOIN part pn ON f.part_number_id = pn.id
WHERE trec.is_active = TRUE AND res.pass_fail IS NOT NULL
GROUP BY f.id, pn.part_number, res.form_row_id
HAVING SUM(CASE WHEN res.pass_fail = FALSE THEN 1 ELSE 0 END) > 0
ORDER BY failure_count DESC LIMIT $1::int
`

type ListTopFailureModesRow struct {
	FormID       int
	PartNumber   string
	Parameter    string
	FailureCount int
}

// Failing steps across all forms, all-time, most-failed first.
func (q *Queries) ListTopFailureModes(ctx context.Context, rowLimit int) ([]ListTopFailureModesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopFailureModes, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopFailureModesRow
	for rows.Next() {
		var i ListTopFailureModesRow
		if err := rows.Scan(
			&i.FormID,
			&i.PartNumber,
			&i.Parameter,
			&i.FailureCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const onTimeDeliveryBySupplier = `-- name: OnTimeDeliveryBySupplier :many
SELECT COALESCE(po.supplier_name, '') AS supplier_name,
       COUNT(*)::int AS total_lines,
       SUM(CASE WHEN pol.date_received <= po.date_ordered + pol.lead_time_days THEN 1 ELSE 0 END)::int AS on_time_lines,
       COALESCE(AVG(CAST(pol.date_received - (po.date_ordered + pol.lead_time_days) AS DOUBLE PRECISION)), 0)::float8 AS avg_days_late
FROM po_line pol
JOIN purchase_order po ON pol.po_id = po.id
WHERE pol.lead_time_days IS NOT NULL
  AND pol.date_received IS NOT NULL
  AND po.date_ordered IS NOT NULL
  AND ($1::date IS NULL OR po.date_ordered >= $1::date)
  AND ($2::date   IS NULL OR po.date_ordered <  $2::date)
GROUP BY po.supplier_name
`

type OnTimeDeliveryBySupplierParams struct {
	DateFrom *time.Time
	DateTo   *time.Time
}

type OnTimeDeliveryBySupplierRow struct {
	SupplierName string
	TotalLines   int
	OnTimeLines  int
	AvgDaysLate  float64
}

// Only lines with a quoted lead time and a receipt date on a dated PO are evaluated.
func (q *Queries) OnTimeDeliveryBySupplier(ctx context.Context, arg OnTimeDeliveryBySupplierParams) ([]OnTimeDeliveryBySupplierRow, error) {
	rows, err := q.db.QueryContext(ctx, onTimeDeliveryBySupplier, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OnTimeDeliveryBySupplierRow
	for rows.Next() {
		var i OnTimeDeliveryBySupplierRow
		if err := rows.Scan(
			&i.SupplierName,
			&i.TotalLines,
			&i.OnTimeLines,
			&i.AvgDaysLate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pOCycleTimeByStage = `-- name: POCycleTimeByStage :many
WITH stage_durations AS (
    SELECT poh.po_id,
           poh.to_status AS stage,
           poh.changed_at AS entered_at,
           LEAD(poh.changed_at) OVER (PARTITION BY poh.po_id ORDER BY poh.changed_at, poh.id) AS exited_at
    FROM purchase_order_history poh
    WHERE poh.event_type = 'status'
      AND poh.to_status IN ('draft','open','sent','partially_received','closed')
)
SELECT stage::text AS stage,
       COUNT(*)::int AS po_count,
       COALESCE(AVG(CAST(EXTRACT(EPOCH FROM (date_trunc('hour', exited_at AT TIME ZONE 'UTC') - date_trunc('hour', entered_at AT TIME ZONE 'UTC'))) AS DOUBLE PRECISION) / 3600.0 / 24.0), 0)::float8 AS avg_days
FROM stage_durations
WHERE exited_at IS NOT NULL
  AND ($1::timestamptz IS NULL OR entered_at >= $1::timestamptz)
  AND ($2::timestamptz   IS NULL OR entered_at <  $2::timestamptz)
GROUP BY stage
ORDER BY CASE stage
    WHEN 'draft' THEN 1
    WHEN 'open' THEN 2
    WHEN 'sent' THEN 3
    WHEN 'partially_received' THEN 4
    WHEN 'closed' THEN 5
END
`

type POCycleTimeByStageParams struct {
	EnteredFrom *time.Time
	EnteredTo   *time.Time
}

type POCycleTimeByStageRow struct {
	Stage   string
	PoCount int
	AvgDays float64
}

// The window filters entered_at in the outer query, after LEAD() has paired each stage with its
// exit over the PO's full history (filtering inside the CTE would mis-pair stages near the edge).
func (q *Queries) POCycleTimeByStage(ctx context.Context, arg POCycleTimeByStageParams) ([]POCycleTimeByStageRow, error) {
	rows, err := q.db.QueryContext(ctx, pOCycleTimeByStage, arg.EnteredFrom, arg.EnteredTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []POCycleTimeByStageRow
	for rows.Next() {
		var i POCycleTimeByStageRow
		if err := rows.Scan(&i.Stage, &i.PoCount, &i.AvgDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendByPart = `-- name: SpendByPart :many
SELECT COALESCE(p.part_number, pol.part_number_snapshot, '')::text AS part_number,
       COALESCE(p.description, '') AS description,
       COALESCE(SUM(pol.qty * pol.unit_cost), 0)::numeric AS total_spend
FROM po_line pol
JOIN purchase_order po ON pol.po_id = po.id
LEFT JOIN part p ON pol.part_id = p.id
WHERE ($1::date IS NULL OR po.date_ordered >= $1::date)
  AND ($2::date   IS NULL OR po.date_ordered <  $2::date)
GROUP BY COALESCE(CAST(pol.part_id AS VARCHAR(20)), CONCAT('snap:', pol.part_number_snapshot)),
         p.part_number, p.description, pol.part_number_snapshot
ORDER BY total_spend DESC
`

type SpendByPartParams struct {
	DateFrom *time.Time
	DateTo   *time.Time
}

type SpendByPartRow struct {
	PartNumber  string
	Description string
	TotalSpend  decimal.Decimal
}

// Lines with no part_id (freeform) are grouped by their part_number_snapshot so the spend stays counted.
func (q *Queries) SpendByPart(ctx context.Context, arg SpendByPartParams) ([]SpendByPartRow, error) {
	rows, err := q.db.QueryContext(ctx, spendByPart, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpendByPartRow
	for rows.Next() {
		var i SpendByPartRow
		if err := rows.Scan(&i.PartNumber, &i.Description, &i.TotalSpend); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendBySupplier = `-- name: SpendBySupplier :many

SELECT COALESCE(po.supplier_name, '') AS supplier_name,
       COALESCE(SUM(pol.qty * pol.unit_cost), 0)::numeric AS total_spend
FROM po_line pol
JOIN purchase_order po ON pol.po_id = po.id
WHERE ($1::date IS NULL OR po.date_ordered >= $1::date)
  AND ($2::date   IS NULL OR po.date_ordered <  $2::date)
GROUP BY po.supplier_name
ORDER BY total_spend DESC
`

type SpendBySupplierParams struct {
	DateFrom *time.Time
	DateTo   *time.Time
}

type SpendBySupplierRow struct {
	SupplierName string
	TotalSpend   decimal.Decimal
}

// ── Spend / on-time / cycle time ───────────────────────────────────────────────
// date_from is inclusive and date_to exclusive; NULL leaves that side open.
func (q *Queries) SpendBySupplier(ctx context.Context, arg SpendBySupplierParams) ([]SpendBySupplierRow, error) {
	rows, err := q.db.QueryContext(ctx, spendBySupplier, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpendBySupplierRow
	for rows.Next() {
		var i SpendBySupplierRow
		if err := rows.Scan(&i.SupplierName, &i.TotalSpend); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
