// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package dbq

import (
	"context"
)

const deleteAttachmentCategories = `-- name: DeleteAttachmentCategories :exec
DELETE FROM attachment_category
`

func (q *Queries) DeleteAttachmentCategories(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAttachmentCategories)
	return err
}

const insertAttachmentCategory = `-- name: InsertAttachmentCategory :exec
INSERT INTO attachment_category (display_name, sort_order) VALUES ($1, $2::int)
`

type InsertAttachmentCategoryParams struct {
	DisplayName string
	SortOrder   int
}

func (q *Queries) InsertAttachmentCategory(ctx context.Context, arg InsertAttachmentCategoryParams) error {
	_, err := q.db.ExecContext(ctx, insertAttachmentCategory, arg.DisplayName, arg.SortOrder)
	return err
}

const listAttachmentCategories = `-- name: ListAttachmentCategories :many
SELECT display_name FROM attachment_category ORDER BY sort_order, display_name
`

func (q *Queries) ListAttachmentCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var display_name string
		if err := rows.Scan(&display_name); err != nil {
			return nil, err
		}
		items = append(items, display_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactOptions = `-- name: ListContactOptions :many

SELECT id, display_name FROM contact
WHERE is_active = TRUE AND ($1::int <= 0 OR company_id = $1::int)
ORDER BY display_name
`

type ListContactOptionsRow struct {
	ID          int
	DisplayName string
}

// Settings page reads and the attachment-category list (#190, #247). The backup's table read is not
// here: its table name is dynamic, so Service.QueryTable runs an allowlist-checked raw query.
// company_id <= 0 means every company.
func (q *Queries) ListContactOptions(ctx context.Context, companyID int) ([]ListContactOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listContactOptions, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactOptionsRow
	for rows.Next() {
		var i ListContactOptionsRow
		if err := rows.Scan(&i.ID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierOptions = `-- name: ListSupplierOptions :many
SELECT id, name FROM company WHERE is_active = TRUE ORDER BY name
`

type ListSupplierOptionsRow struct {
	ID   int
	Name string
}

func (q *Queries) ListSupplierOptions(ctx context.Context) ([]ListSupplierOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSupplierOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplierOptionsRow
	for rows.Next() {
		var i ListSupplierOptionsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
