-- bom: Bill of Materials. Each row is one component line in an assembly.
-- parent_part_id / component_part_id both FK to part.id.

DROP TABLE IF EXISTS bom CASCADE;

CREATE TABLE bom (
  id                 INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_part_id     INTEGER        NOT NULL,           -- FK to part.id (parent assembly).
  component_part_id  INTEGER        NOT NULL,           -- FK to part.id (component part).
  line_number        INTEGER        NOT NULL DEFAULT 0, -- Line item number within the assembly.
  qty                NUMERIC(15,5)  NOT NULL DEFAULT 1  -- Quantity required.
);

ALTER TABLE bom ADD CONSTRAINT FK_bom_PN_parent    FOREIGN KEY (parent_part_id)    REFERENCES part (id);
ALTER TABLE bom ADD CONSTRAINT FK_bom_PN_component FOREIGN KEY (component_part_id) REFERENCES part (id);
-- No UNIQUE on (parent_part_id, line_number) - item numbers are user-assigned.
